### ISSUE TITLE
Python 3 Port

### ISSUE THREAD

**Issue by cschwem2er** [seikur0/PGO-mapscan-opt#1]
Hi,

first of all thank you for the nice application :) Do you have any tips for a python 3 port? As far as I understand a simple `2to3` conversion of every file won't be enough and I don't really want to use Python 2 anymore.

Cheers

**Comment by seikur0** [comment]
Hey,
it's actually the first time I've been using Python, I just went with 2.7 since the original api demo code by Tejado was in it.
I guess just compile it and fix the code from the error messages.

**Comment by ygongdev** [comment]
I got it working for Python 3, Specifically Python 3.4. I could share it if people still need it
