### ISSUE TITLE
Frage....

### ISSUE THREAD

**Issue by mancmanGER** [seikur0/PGO-mapscan-opt#10]
Hallo seikur0,

Klasse Arbeit die Du hier gemacht hast, ist viel schneller und genauer als die andere Version.

Könntest du dieselbe Funktionalität integrieren wie bei AHAAAAAAA/PokemonGo-Map,
d.h. neuer Ort über die Map-Seite und ein forward nach draußen, sodass ich im Felde mit dem Handy darauf zugreifen kann??

Sorry kann dies leider nicht selbst und weiß auch nicht ob es überhaupt geht, da ich nicht programmieren kann.

**Comment by mancmanGER** [comment]
ok forward geht mit ngrok....sorry hätte es vorher ausprobieren sollen

data1 bis 6.json sagt er immer 404 file not found

**Comment by seikur0** [comment]
Ich bin immer glücklich, wenn sich Probleme von selbst lösen :) Das mit den data files ist normal, ich werde es in der nächsten version ändern, jeder 2. sagt das und denkt, irgendwas ist falsch, aber die einzige Möglichkeit über html zu checken, ob die Datei da ist, ist nunmal, diesen Fehler in Kauf zu nehmen, wenn sie es nicht ist. Die miesten Leute brauchen sowieso nur eine Instanz und ich kann es als setting in die settings.json des nächsten Updates aufnehmen.

**Comment by mancmanGER** [comment]
Danke für Deine schnelle Antwort. Willst du in Zukunft das ganze so zur Verfügung stellen wie das andere script mit freier Ortswahl und Pokestops etc. oder lässt Du es so wie es ist.

Das forward geht so lala da die Icons sehr groß sind dauert es ne Zeit bis alles geladen ist, das ist aber nun "stöhnen" auf hohem Niveau ;o)

**Comment by seikur0** [comment]
Ich lasse es im Großen und Ganzen wie es ist, aber ich plane als nächstes Projekt im Hinterkopf schon einen Mapscanner mit intelligentem Scanmuster, der statt der Teilgebiete Spawnercluster scannt, da würde ich dann auch die Pokestops abgreifen. Freie Ortswahl hast du ja schon, also ich plane jedenfalls nicht, einen Server für andere weltweit zu hosten, das muss schon jeder selbst machen.

Wegen der Icons kann ich vielleicht nochmal was machen, aber das steht nicht unbedingt oben auf meiner Liste. Du kannst siie austauschen, wenn du willst und entsprechend die Größendefinition in der html file ändern.

**Comment by mancmanGER** [comment]
Mit freier Ortswahl meinte ich ein Suchfeld in der Map, sodass mann schneller das Suchgebiet ändern kann, vor allem wenn man draußen unterwegs ist. 
Also so wie in dem Script von "AHAAAAAAA/PokemonGo-Map" wo man in der Map selbst nach dem neuen Ort suchen kann also ohne manuelle Eingabe im code.

Perfekt wäre dein super genial schnelles Skript mit der usability von dem obigen.

Wünsche, Wünsche, Wünsche.....  ;o)

**Comment by seikur0** [comment]
Nein, das ist nicht geplant. Durch soetwas könnte Niantic theoretisch auch den Scanort mit den Benutzerortsdaten korrelieren und dadurch folgern, wer der Benutzer der Map ist. 

Aber es steht dir frei, selbst meinen Code zu forken und selbst sowas einzubauen.
