### ISSUE TITLE
Request: Pogo Account Load?

### ISSUE THREAD

**Issue by c00ni** [seikur0/PGO-mapscan-opt#100]
Is there any way of displaying or visualising how many pogo accounts are in use, or maybe a stat like how long an account was dormant for before going to the next spawn point (after spawn point data has been learned)
Want to cut down on accounts but can't really tell how much is too much.

**Comment by seikur0** [comment]
If the time in the catching up phase 2 doesn't decrease you don't have enough accounts. You can also do an estimate, number of spawnpoints gives you the needed scans per hour, every account can scan 3600/time_hb times per hour. I guess I can include that estimate as message. The less accounts you use, the longer the catching up phase will take.

**Comment by c00ni** [comment]
For my r 26 scan, it took quite a while to be able to see what the remaining catchup time was. Actually even with the r 8 one I use.
Can the current delay be shown more often?

**Comment by seikur0** [comment]
There are 2 phases, in the first phase every spawn point, that has already spawned is being scanned, this is done backwards, so the most recent spawns get shown first. For this phase there are pseude-percentages. Do you mean these? Then in the second phase it goes back to the spawntime at the start of phase 1 and starts scanning in forward direction, that's when the delay is shown. That delay will stop being shown for delays below ~10 s.

**Comment by c00ni** [comment]
Yes indeed it is quite adequate. My accounts caught up too quick for me to really take notice.
I'm now using 12 accounts for -r 26 instead of 73 and even that's probably a few more than I need.
