### ISSUE TITLE
collector.py not working?

### ISSUE THREAD

**Issue by hanscts** [seikur0/PGO-mapscan-opt#105]
I think collector.py is not working because the json file name format was changed to coordinates.

**Comment by seikur0** [comment]
You may need to install another requirement, 'pip install pypiwin32'. It has nothing do with the format change, it only upload the spawn files.

**Comment by seikur0** [comment]
I also edited the file, since it still wouldn't work for me, now it should be fine. (Not my uploader tool :P)

**Comment by hanscts** [comment]
I tried the updated script. It still says...

> Connected to server, start sending!
> 
> You seem to have no uploadable files.
> Wait a bit for the map to accumulate more pokemon.
> 
> Transferred 0 pokemon sightings!
> Transfer done, waiting for data to be sent by the os!
> Thanks for helping out!

And I can't seem to install pyypiwin32. I'm running this on Linux. Does that matter?

**Comment by seikur0** [comment]
pypiwin32 would only be needed for windows.

Well it's working, you just don't have uploadable files. It only uploads the archived spawn files from the res folder. In the standard setting they get archived at 10 MB. An example would be this one: "spawns0.20160814_2120.txt". So if you want to manually archive one, you can rename it.

**Comment by hanscts** [comment]
Ok. now I understand. My spawn0.txt is just below 10MB. And renaming manually did the trick. Thanks!
