### ISSUE TITLE
encrypt.so renaming does not work

### ISSUE THREAD

**Issue by Bukowskaii** [seikur0/PGO-mapscan-opt#108]
I have renaming every single file at

https://github.com/PokemonGoMap/PokemonGo-Map/tree/develop/pogom/libencrypt

to 'encrypt.so' and none of them work. What do I need to do to get this working? I am on Windows 10 64 bit with python 2.7 32 bit installed.

**Comment by seikur0** [comment]
encrypt32bit.dll should be working, are you sure that you put it into the right place? The res folder.

**Comment by Bukowskaii** [comment]
yes, i put it in the right place. without renaming the code threw an error that the file doesnt exist. With renaming it said it wasn't a valid windows executable. I tried changing the line of code to "encrypt32bit.dll" even and it still said it wasn't a valid windows executable.

**Comment by seikur0** [comment]
Either encrypt64bit.dll or encrypt32bit.dll, one of them must be working. If not open an issue in the pogoapi github.

**Comment by Bukowskaii** [comment]
I found another scanner that bundles these in packages and it works fine. I think it's an issue on your end.

**Comment by seikur0** [comment]
Then just use the working file from that bundle. If it says, that it's not a valid windows executable you used the wrong file, simple as that.
