### ISSUE TITLE
http://localhost:8000 can't be reached

### ISSUE THREAD

**Issue by mikeh108** [seikur0/PGO-mapscan-opt#109]
Hi,
I completed the 'pip install -r requirements.txt' step, and I downloaded encrypt32bit.dll and renamed it to encrypt.so and placed it in the res folder, so I guess that step is done too?  Now when I double click main0.py in the PGO-mapscan-opt-master folder I tells me which pokemon have spawned where and when till when they're visible, the only things I changed in usersettings.json is filling in the API key and filling in data for 4 PTC accounts using id 0 in all and the same lat lng and alt in all 4. When I paste http://localhost:8000 it tells me This site can't be reached. Before I ran the main0.py the site viewed a normal pokemon go map (without pokemon/pokestops/gyms)
Thanks in advance.
Edit: it also says Oops! Something went wrong 
Google maps didn't load correctly on this page. See JavaScript-console for technical details.
I also tried changing it to http://localhost:7000 and using port : 7000 in the usersettings.json

**Comment by seikur0** [comment]
Check the console then, F12. Where does it say "Oops! Something went wrong"? Certainly not my error message :D Maybe the api key is wrong?

**Comment by mikeh108** [comment]
Thanks for replying so quickly, it said it on google when I loaded the site. I tried another API too. It works now though since I woke up as far a I know, didn't change anything. In the main0 cmd I see alot more (3/4 times as much) pokemon than on the map though. Do you know how to fix this? (Would you like me to make a new issue for this and close this one?)

**Comment by seikur0** [comment]
Okay. Edit the exclude_ids setting in the usersettings file. Ids in there won't be sent to and shown on the map. (And no.)

**Comment by mikeh108** [comment]
My bad those are the excluded ID's from my usersettings.

**Comment by mikeh108** [comment]
Haha what a coincidence. Is there any way to make the map view its scanned locations and change the map from a google map to the pokemon go map?

**Comment by seikur0** [comment]
Not an easy way, you can create one by coding :P

**Comment by mikeh108** [comment]
Alright thanks for all the help, really loving the scanner so much faster than others.
