### ISSUE TITLE
Is unknown 12 really transaction id?

### ISSUE THREAD

**Issue by zeevallin** [seikur0/PGO-mapscan-opt#11]
@seikur0: Looking at the line in this file, you've left a comment saying it's a transaction id. https://github.com/seikur0/PGO-mapscan-opt/blob/91822ffa9887054fac15152b9804f300c8a71563/main0.py#L245

Care to elaborate? Asking for https://github.com/AeonLucid/POGOProtos/issues/94 :)

**Comment by seikur0** [comment]
I got it from this thread: https://www.reddit.com/r/pokemongodev/comments/4tn3lm/the_heartbeats/ I don't know more about it, maybe that redditor does.

**Comment by zeevallin** [comment]
Ah thanks :)
