### ISSUE TITLE
Softbann? No Spawns after a while

### ISSUE THREAD

**Issue by Coalado** [seikur0/PGO-mapscan-opt#110]
Is there any kind of softban detection? After a while, the scanner continues to run, but does not find anything. 

[+] 10981 of 10981 cells detected as empty during last run.
[+] Non-empty heartbeats reached a maximum of 0 retries, allowed: 1.
[+] Average number of retries was 0.0, total number 0.
[+] Scan Time: 675 s

**Comment by seikur0** [comment]
No softban detection, since that doesn't just happen randomly. If it happens like in this case you probably have too many accounts running for your ip.

**Comment by Coalado** [comment]
I reduced them to ~50 accs for a 30 radius. This seems to work fine
