### ISSUE TITLE
Pokestops

### ISSUE THREAD

**Issue by Coalado** [seikur0/PGO-mapscan-opt#111]
It would be great if the scanner could find pokestops(lured/normal), their time to expire and the active pokemon.
Any chance?

**Comment by seikur0** [comment]
Pokestops are already being written into the learning file. But scanning them live would be hard with intelligent spawn point scanning. There are many of them and they'd need to be rescanned regularly to determine, if they're lured and when lured every 3 minutes to get the currently active pokemon.

**Comment by Coalado** [comment]
That's true. I did not consider this
