### ISSUE TITLE
Write to stdout

### ISSUE THREAD

**Issue by Coalado** [seikur0/PGO-mapscan-opt#112]
It would be great if the scanner could write every information of interest to stdout. (formated)
This way I could simply parse the stream and write everything to a database.

My current approach would have to parse and merge the spawns*.txt file and the stdout stream to get most information.

Or did I miss anything I should know about?

**Comment by seikur0** [comment]
Which informations are you interested in?^^ The spawns*.txt files should have everything?

**Comment by Coalado** [comment]
Spawn incl. the Spawn types to predict if and when the spawn will reappear. 
Is it even possible to tell the spawn type in advance?

**Comment by seikur0** [comment]
What do you mean by in advance? These data gets written to a json file after 3 hours, that the point of the learning phase.

**Comment by Coalado** [comment]
I think got it. I will evaluate the spawns.txt and the json file
