### ISSUE TITLE
some bug

### ISSUE THREAD

**Issue by arivero** [seikur0/PGO-mapscan-opt#113]
Json saved this

  {
   "pausetime": [
    6.590933334082365
   ],
   "spawntime": 5.903933335095644,
   "pauses": 1,
   "lat": 41.65508198086151,
   "lng": -0.8784254361813663,
   "phasetime": 120,
   "type": -1,
   "id": 917265897999
  },

it was a range 4, interval 750 scan.

**Comment by seikur0** [comment]
Either it's a 2 hour interval spawn or your scan went pretty wrong (many empty cells in between/skipping due to a high interval). If you want to make sure, rescan just that one point with range 0 and an interval of 60 and one worker.
