### ISSUE TITLE
r.history list index out of range

### ISSUE THREAD

**Issue by blubkatze** [seikur0/PGO-mapscan-opt#116]
I always get 'Ptc login error in step 4: list index out of range' when trying to login with a ptc account.
r.history seems to be an empty list. print r.history yields [].

**Comment by seikur0** [comment]
Uncomment the line:
lprint('[{}] Connection error, http code: {}, content: {}'.format(account['num'], r.status_code, r.content))
and comment the one above in main0.py. Then look at the content for some error messages.
Either it's the wrong username/password or the account needs email verification I guess.

**Comment by blubkatze** [comment]
Thanks, weren't activated
