### ISSUE TITLE
[-] Non-empty cell returned as empty.

### ISSUE THREAD

**Issue by Coalado** [seikur0/PGO-mapscan-opt#118]
I get this pretty often in my logs. Is this somthing that should actually never happen?

**Comment by seikur0** [comment]
After the map is live it should never happen.

**Comment by Coalado** [comment]
Ich werde versuchen weniger Accounts zu nutzen

**Comment by seikur0** [comment]
Entweder das oder ein kleinerer Bereich oder du hast eine schlechte Lerndatei.
