### ISSUE TITLE
EncounterID Format

### ISSUE THREAD

**Issue by Coalado** [seikur0/PGO-mapscan-opt#119]
I want to compare the results of this scanners to others. All other scanners have the encounter ID in a base64 format. MapScan  uses a long number. How can I convert it to matching base64 encounter IDs?

**Comment by seikur0** [comment]
import base64 and use base64.b64encode(str(encounterID))

Btw that long number uses much less resources in memory than the base64 string, nevermind the encoding and comparing for uniqueness.

**Comment by Coalado** [comment]
Thanks
