### ISSUE TITLE
Google Login doesn't seem to be working?

### ISSUE THREAD

**Issue by ygongdev** [seikur0/PGO-mapscan-opt#12]
I keep getting the error and retrying when trying to do a google login. Does it actually work?

**Comment by permalost** [comment]
When you entered your username/password did you also change line 95 from ptc to google?

Edit: Looking at code the google login logic appears missing and I found this: https://www.reddit.com/r/pokemongodev/comments/4ui7um/pokemon_go_mapscan_optimized_code/d5tlqcc

**Comment by ygongdev** [comment]
yup I changed that line. The google login seems to be missing quite a few things when I comapred it with the original one from teejago.

**Comment by seikur0** [comment]
The new version support google login now.
