### ISSUE TITLE
IndexError: list index out of range in main0.py on line 1204

### ISSUE THREAD

**Issue by nyxdis** [seikur0/PGO-mapscan-opt#127]
I'm getting this at some point during the normal scan phase. I don't quite see yet why it would happen. The offending line is the following:
`spawn = scandata['spawns'][list_spawns.index(spawnIDint)]`
`list_spawns.index(spawnIDint)` is 2171, `spawnIDint` is 4927202816721 which is the following spawn:

```
  {
   "pausetime": -1,
   "spawntime": 12.671533335000277,
   "pauses": -1,
   "lat": 54.79546818490205,
   "lng": 9.430356426322902,
   "phasetime": -1,
   "type": -1,
   "id": 4927202816721
  },
```

At some point earlier the index 2172 was scanned which worked fine, so I don't see why 2171 wouldn't work anymore.

**Comment by nyxdis** [comment]
Considering that this is a spawn of type SPAWN_UNDEF, I'm wondering if commit d2005b3 is related. Especially the move of line 800 inside the if.

**Comment by seikur0** [comment]
Should be finally fixed now :)
