### ISSUE TITLE
split requirements.txt for *nix and Windows

### ISSUE THREAD

**Issue by tcmaps** [seikur0/PGO-mapscan-opt#128]
as getting VC-for-Python to work is one of the painfullst pita's you can have,  
i recommend adding a windows-requirements.txt without:  
- xxhash  
- twisted  

and instead link the Windows users to get compiled wheels from here:
http://www.lfd.uci.edu/~gohlke/pythonlibs/#twisted
http://www.lfd.uci.edu/~gohlke/pythonlibs/#xxhash

**Comment by seikur0** [comment]
What so bad about installing VC for python? It took something like 20 seconds for me.

**Comment by tcmaps** [comment]
for some it works, for others not. installing is not the problem, but setting up the paths correctly. depending on what also changed your paths before, it may freak out. for me, it never worked out, no matter what i tried. lots of issues posted regarding vc (on pogomap too) seem to reflect that.

**Comment by seikur0** [comment]
I'll link this issue in the readme, thanks :)
