### ISSUE TITLE
Proxy Support

### ISSUE THREAD

**Issue by Coalado** [seikur0/PGO-mapscan-opt#129]
Is it possible to run several instances each through a different proxy server?

**Comment by seikur0** [comment]
Not yet.

**Comment by Coalado** [comment]
This would be a great feature. 
To date, the only  way to run multiple instances are virtual machines.

**Comment by seikur0** [comment]
Added.

**Comment by Coalado** [comment]
Thanks a lot. Is Basic auth supported? like proxy : "https://user:pass@domain.com" ?
