### ISSUE TITLE
exception while running

### ISSUE THREAD

**Issue by pokeolaf** [seikur0/PGO-mapscan-opt#13]
Running this with pyhton2.7 on windows i get the following exception:

[+] login for ptc account: <redacted>
Traceback (most recent call last):
  File "main0.py", line 547, in <module>
    main()
  File "main0.py", line 434, in main
    do_login()
  File "main0.py", line 225, in do_login
    login_ptc(li_user,li_password)
  File "main0.py", line 192, in login_ptc
    ticket = re.sub('.*ticket=', '', r.history[0].headers['Location'])
IndexError: list index out of range

**Comment by ygongdev** [comment]
is that error coming from ticket = re.sub('.*ticket=', '', r.history[0].headers['Location'])?
I know I had an error similar, but that was because I didn't have anything in the users array lol.

**Comment by ProfessorPokes** [comment]
I have created, updated, and submitted a user_config file that should fix most of these issues associated with usernames (I can't make any promises tho, I'm new here). I just need to update the config file for multiple usernames and passwords.

**Comment by seikur0** [comment]
I just updated the project and settings should be much more accessible now, all of them are in a separate settings file. It looks indeed like you didn't enter a valid username/password, but I'm kind of confused why that error didn't get caught properly? I have that whole block inside a try statement.

**Comment by pokeolaf** [comment]
Testing with the old version ive found that r.history[0] is the problem.
The new version works
