### ISSUE TITLE
Pushbullet Channels error

### ISSUE THREAD

**Issue by ptchamp2016** [seikur0/PGO-mapscan-opt#130]
Hi, with the last big update, you accidentally broke the Pushbullet Channels feature

```
[-] Pushbullet error, key CENSORED is invalid, 'pushbullet'
[-] This pushbullet will be disabled.
```

At line 221, you have 

`if channel.channel_tag in allsettings['pushbullet']['channel_tags']:
`

and it should be 

`if channel.channel_tag in allsettings['notifications']['pushbullet']['channel_tags']:
`

**Comment by seikur0** [comment]
That's very true, thanks :)
