### ISSUE TITLE
pokesite.py and SSL

### ISSUE THREAD

**Issue by darkforcesjedi** [seikur0/PGO-mapscan-opt#133]
I have HSTS enabled for my domain (strict transport security), which tells clients never to connect without using SSL (and this setting is saved by the client browser). This wasn't an issue in the past as I just hosted the website using Apache, and created a symbolic link to the data file.

The latest version of pokesite.py uses some hard-coded functions to process the index.html and also a virtual "/_getdata" to serve up new pokemon spawns by querying the spawn database. This makes it a lot less straightforward to host the pokesite from an alternate web server.

I created a _getdata.php file for my server which implements "/_getdata" and modified index.html to hard-code the settings so it works (for now).

Surely there must be a way to set it up so that it can be hosted on a separate web server.

This is my _getdata file:

``` php
<?php
$profile=htmlspecialchars($_GET["profile"]);
$datatill=htmlspecialchars($_GET["data_till"]);
$timenow=time();

$db = new SQLite3('data.db');

$query='SELECT spawnid, latitude, longitude, spawntype, pokeid, expiretime FROM spawns WHERE (expiretime > :expiretime) AND (fromtime >= :fromtime)';
if ($profile<>-1) {
  $query=$query . ' AND (profile == :profile)';
}

$stmt=$db->prepare($query);
$stmt->bindValue(':expiretime', $timenow, SQLITE3_INTEGER);
$stmt->bindValue(':fromtime', $datatill, SQLITE3_INTEGER);
if ($profile<>-1) {
  $stmt->bindValue(':profile', $profile, SQLITE3_INTEGER);
}


$results = $stmt->execute();

echo '[' . $timenow . ',[';
$rownumber=0;
while ($row = $results->fetchArray()) {
    $rownumber=$rownumber+1;
    if ($rownumber>1) echo ',';
    echo '[' . $row[0] . ',' . $row[1] . ',' . $row[2] . ',' . $row[3] . ',' . $row[4] . ',' . $row[5] . ']';
}
echo ']]'
?>
```

**Comment by seikur0** [comment]
I'm not sure, how I can help you.

These hard coded statements are used by jinja, which is used by flask. But if you don't need the flexibility from that or your security settings don't allow it, then it's certainly fine to replace these {{ }} settings as you did and use something else to host it.

**Comment by darkforcesjedi** [comment]
It is your application, so you are welcome to ignore my suggestion if you don't think it is practical.

Previously the index.html file read its settings by dynamically requesting a JSON file. Independent settings for each profile could be stored in a single JSON file and the client could apply the appropriate settings for the selected profile using javascript. The file is only loaded once and using compression wouldn't require much bandwidth. Alternately each profile could have a separate settings file.

Then pokesite.py could serve everything except "/getdata" passively. /getdata would still function as the database interface. Then I could put a "getdata/index.php" or "getdata" file on my web server that mirrors the functionality. pokesite.py would ignore this file, but Apache would not.

**Comment by seikur0** [comment]
Then how would you tell the html file, which profile to use? If you're gonna have to change the html file anyway, you could probably just do with a small program that mimics the jinja functionality and just replaces the {{ }} settings in the file by settings of your choice. That way, you'd only have to execute it once, if I update something in the html?

**Comment by darkforcesjedi** [comment]
Using an anchor like http://example.com:port/#id1 . Javascript window.location.hash would return '#id1'. Javascript could parse this string to determine what profile to apply.

Right now there is not much to implement, but as pokesite.py diverges more from a simple web server it will be more difficult to host from a standard web server, as everything pokesite does that is not a passive file transfer will have to be reimplemented in order for it to work.

**Comment by seikur0** [comment]
Can you make a pull request for that with the php as well and put it into a folder named webres_standalone together with a .py file, that creates the required settings files from the main settings file, which would need to be put into that folder or optionally downloaded directly? I guess it's pretty useful for people, who want to host it separately.

**Comment by darkforcesjedi** [comment]
I have never used python before and barely touched php. (I use .NET normally.) I will see if I can figure something out but I will need a little time. For efficiency sake, it would probably make more sense if main0.py put the settings into the database when it loads, then pokesite.py or the php file could pull the settings from the database to send to the client.

**Comment by seikur0** [comment]
That is true, I can make it put the settings into the database.

**Comment by seikur0** [comment]
I'll close this for now, if you want to do it and have it finished, just do a pull request :)

**Comment by seikur0** [comment]
Hey, I just found this: https://github.com/Frozen-Flask/Frozen-Flask Could this be helpful to you?
