### ISSUE TITLE
hardcoded _getdata URL may break

### ISSUE THREAD

**Issue by nyxdis** [seikur0/PGO-mapscan-opt#136]
I'm running nginx on my server which forwards requests to /pokemap to localhost:9000 (which is pokesite.py). Now obviously _getdata is located under /pokemap/_getdata. index.html tries to request /_getdata though. I've fixed this locally by changing the request from /_getdata to just _getdata (relative path), would it be a problem to change this in your repo?

**Comment by seikur0** [comment]
No, changed it :)

**Comment by darkforcesjedi** [comment]
I was going to do a pull request for this but I felt silly creating a pull request for a 1 character change.

**Comment by seikur0** [comment]
Haha
