### ISSUE TITLE
Basic Auth for Proxy

### ISSUE THREAD

**Issue by Coalado** [seikur0/PGO-mapscan-opt#137]
Thanks for the proxy support.  Is Basic auth supported? like proxy : "https://user:pass@domain.com" ?

**Comment by seikur0** [comment]
Yes.

**Comment by Coalado** [comment]
I get this for every login: [22] Ptc login error in step 0: ('Connection aborted.', BadStatusLine("''",))

**Comment by seikur0** [comment]
Make sure the proxies themselves have http:// urls. From what I read the python socket doesn't support https tunneling through proxies, so it gets sent as http to the proxy itself and then as https from there on, meaning all proxy urls start with http and not https.

**Comment by Coalado** [comment]
This does not work.

https://:  
Ptc login error in step 0: ('Connection aborted.', BadStatusLine("''",))

http://: 
[23] Ptc login error in step 0: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
[23] Error happened before network request.
[23] Retrying...

 Which answer would I get if the proxy ip is blocked?

**Comment by seikur0** [comment]
It would tell you, that your ip is blocked. But in this case it just seems, your proxy can't do ssl?

**Comment by Coalado** [comment]
Ich kann dir meinen Proxy gerne zum testen schicken. Email IRC oder so?

**Comment by seikur0** [comment]
Ich weiß nicht, was ich da testen soll :/
