### ISSUE TITLE
Add raw_data or map-data to the webserver

### ISSUE THREAD

**Issue by Trustmania** [seikur0/PGO-mapscan-opt#139]
Hi,

the AndroidApp pokkimap support **PokemonGo-Map** and **pogom** as private server. So it would be nice to add there as well your solution.

The **PokemonGo-Map** has http://11.11.11.11:1111/raw_dat
The **pogom** has http://11.11.11.11:1111/map-data

Thank you very much for your nice work!!!

Best regards from Berlin (Germany),
Sascha

**Comment by seikur0** [comment]
Just do http://11.11.11.11:1111/_getdata for my map and it'll give you all the data it has.

**Comment by Trustmania** [comment]
Wow, this was fast! THX! 

Seams, that you did a good job and pokiimap has some issue ^^
(Getting Message: **java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at line 1 column 2 path $**)

Again: Your stuff is really good working...! Nice Job!

**Comment by seikur0** [comment]
^^
