### ISSUE TITLE
logging data for later analysis

### ISSUE THREAD

**Issue by marvin-bitterlich** [seikur0/PGO-mapscan-opt#14]
Hello there,

we are currently creating a big collection of pokémon spawns/nests and want to ask popular pokemon maps to share their data with us.

for reference: 
https://www.reddit.com/r/TheSilphRoad/comments/4uqlet/pokelyzer_setup_instructions_a_tool_for_finding/
https://github.com/Kostronor/pokelector

What we would need are:
- A log file created that adds a new line for each pokémon found.If possible removing hearthbeat updates. 
- maybe an option to push all found pokémon over a socket (if the user wants that)

what we need is a data object having these properties:

```
pokemon_id = int(data['pokemon_id']) # the pokemon number
last_modified_time = int(data['last_modified_timestamp_ms']) # when you received the pokemon from pogo-servers
time_until_hidden_ms = int(data['time_till_hidden_ms']) # the time until the mon is hidden
encounter_id = str(data['encounter_id']) # the encounter id from pogo
spawnpoint_id = str(data['spawnpoint_id']) # the spawnpoint id from pogo
longitude = float(data['longitude']) # longitute of the spawn
latitude = float(data['latitude']) # latitude of the spawn
```

Sending a json object would be best but other formats are fine too. If you can give me a hint where to look for a pokemon received event, I could submit a pull request.

**Comment by pokeolaf** [comment]
This script currently writes its found pokemon to a file csv stile (with space as value delimiter and new line as data set delimiter).

[Edit] the whitespace used as value delimiter is a single tab.

**Comment by marvin-bitterlich** [comment]
That should be parsable just fine, thanks!

Could we convince you to give your users the option to upload found pokémons automatically without the detour over the csv file?

**Comment by ferazambuja** [comment]
Each worker saves to a separate spawn.json.
Also, I've been testing and seems that this map can detect more Pokemon than the Pokemap variants. It has to do with the negative TimeTillHidden bug.

**Comment by seikur0** [comment]
No I don't want to add the option for automatic upload, I want to keep it independent, sry.
However you can ask the people from my reddit thread, the tool logs encounters automatically and I'd say many people there would be willing to share.

**Comment by ferazambuja** [comment]
Maybe something in the middle of the road. A tool to upload the db?

**Comment by marvin-bitterlich** [comment]
@seikur0 Would you agree to me submitting a pull request for an upload tool that is completely separate from the map, but useable for people?

**Comment by seikur0** [comment]
Yes, that would be okay, Btw here is a link to my data: http://seikur0.pythonanywhere.com/static/res/spawns0.20160728_1351.json Sry for the large size, I implemented the auto backup function just today :)

**Comment by marvin-bitterlich** [comment]
@seikur0 thanks a lot! Will get right to it :)

PS: I'm unauthorized to view the file :)

**Comment by seikur0** [comment]
Sorry, forgot to include the username/ password, it's user/nopassword
