### ISSUE TITLE
It can't find every spawn point in my town

### ISSUE THREAD

**Issue by plebcity** [seikur0/PGO-mapscan-opt#141]
I've been scanning my town for about 2 hours with 15 bots using spawnscan and it found every possible spawn point in my town. I'm missing loads of spawns using your scanner. You should scan the same spot atleast 4/5x in 1 hour to know if its a spawn point. You should set the bots to do a run in about 12 minutes  and then restart it. After the first hour you should have all spawn points in the first area and you can move on to the next one.

What would be nice if you can define an area instead of a range. Take a look at this: https://github.com/TBTerra/spawnScan

**Comment by seikur0** [comment]
You say, I should do things, when in fact these are things, that you personally should and can do. It takes 3 hours, because 1 hour isn't enough to distinguish between the known types and a new one. (I'll change that in the future, because at this point I think I've found all of them.)

**Comment by plebcity** [comment]
Why should I need to calculate myself when that can easily be build in to some kind of calculator to let you know its gonna take 2 hours for your entire area per run so 6 hours in total? Now I need to trial and error to know what range i need for my area and how many workers i'm gonna need.

**Comment by seikur0** [comment]
Because it can't be calculated, I could only give you a range, which would be very huge. So just do one run, if that takes 16 minutes and you want it to take 10 minutes, you need 16/10 as many workers.
