### ISSUE TITLE
Questions about Spawn Scanning

### ISSUE THREAD

**Issue by Coalado** [seikur0/PGO-mapscan-opt#142]
no 1.
It may happen, that a scan takes longer than 15 minutes.  In this case, the scanner would not find all spawnpoints and types properly. Is there some kind of auto-detection of such situations. 
The scanner could - for example -  automaticly increase the timeframe to ensure that it has all spawnpoints. 

 no 2.
If the scanner misses some points during the initial 3 hours, he might find them during the optimized scan later. will the spawnpoints file be touched in this case?

 no 3. 
The area I'd like to scan is too big to  do the initial 3 hours scan in a 10 minutes interval. I have to do this initial scanning in smaller 30 steps parts. Can I merge the resulting json files to do the optimized scan in one single instance?

**Comment by plebcity** [comment]
I have the same problem described in this issue: https://github.com/seikur0/PGO-mapscan-opt/issues/141

**Comment by ptchamp2016** [comment]
As I understand it, either you create more accounts so the total scan time is under 13 minutes or you do smaller scans of the areas that you want.

If you split the scans, then, when you have all the areas that you want, you can put all the learning files in a folder together with spawnfix.py and run

`python spawnfix.py`

That will generate a mapdata.json that you'll need to rename to the correct learning file format (lat_lng_radius_70.0.json).

After that, you put that file inside res folder, edit usersettings.json to make all accounts have the same ID, lat, lng and the scan radius, so that it matches with the file name.

**Comment by Coalado** [comment]
This answers question no. 3

**Comment by ptchamp2016** [comment]
Well, for number 1, I guess the only way is for you to see how long the scan took. It says waiting X seconds after each run. If X is 0, then it took more time than what you expected and either you increase scantime or add more workers or split the area. I believe there is no way for the tool to automate that.

For 2, I believe that it won't edit the learning file while doing iscan.

**Comment by Coalado** [comment]
for 1:
I wrote a tiny tool that creates a lat_lng_radius_70.0.json file for several locations -  on after another- and restarts if  a scan takes too long. So i kind of worked around this problem.

**Comment by seikur0** [comment]
for 1: Just watch the time, it tells you the needed time after each run and that time stays about the same, at least for the first 2 hours (then empty cells get removed and it gets faster). It's not so hard to ensure the first run taking under 10 minutes or if you want to take a risk 12 min.

for 2: during iscan you likely wouldn't be getting the full information, meaning one scan in every quarter. Some points at the border, that weren't in your original area actually only get scanned once every hour.

for 3: ptchamp2016 answered that already

I'm not that happy with the algorithm, these 3 hours were good, when I wasn't sure about the different spawn point types, but now I'm pretty sure I have them all and they all have a one hour rhytm, so I definitely want to rework that algorithm.

**Comment by darkforcesjedi** [comment]
These kinds of problems could be addressed by the code if it did learning and intelligent scanning in parallel. For example:

During the first run of learning phase scan as many regions as possible in < 15 minutes and end that run. Rescan those same regions for the remainder of the 3 hour learning period. Once learning is complete, perform intelligent scanning on those regions. Use idle time of intelligent scanning mode to perform learning phase on additional regions.

Alternately, it could attribute some threads for learning and some for intelligent scanning. Then reassign them all to intelligent scanning once learning is complete.

I created a tool to tile a region in radius 7 hex grids and I have a second instance running in parallel that runs 6 threads (about 5 minute runtime per iteration) to complete the learning phase for each subregion. As those region scans complete I integrate them into the spawn point file in the main instance and restart it periodically to incorporate the new subregions.

**Comment by seikur0** [comment]
The thing with learning is it takes a lot of workers, a lot more than for iscan, so I'd rather keep it separated and not mix it for now. But I'll rework the learning phase, so it only takes 1 hour or optionally 2 hours, if you want to be on the safe side, for sure.

**Comment by k0enf0rNL** [comment]
@seikur0 I have another question: Why are cells being excluded after the first run?
