### ISSUE TITLE
Some spawns doesn't show up some times.

### ISSUE THREAD

**Issue by ptchamp2016** [seikur0/PGO-mapscan-opt#143]
Hey again!

My "problem" is that sometimes I know there will be a spawn somewhere but the tool doesn't pick it up. It's a random behavior, without any pattern that I could find.

This happens with iscan and with no error (non-empty cell bla bla). The spawn should be there but isn't.

I don't know the % of this situation, as I only know some spawns timers.

Just wanted to ask what could be causing this? Not enough workers (I have 85 for 100km^2) and some spawns aren't scanned in time?

Thanks!

**Comment by seikur0** [comment]
Check your learning file for that specific spawn, if it's in there it will be scanned on time, if not not.

**Comment by ptchamp2016** [comment]
Well, as I said, I know it's in the file and I know when its supposed to spawn. But it's random...

I even searched the spawn0.txt file for the specific spawn ID and for a full 16 hours I only had 2 records...

It's not a deal breaker for me, as it seems that it works most of the time, just wanted to know if you had any insight on this.

**Comment by seikur0** [comment]
Could be that your system clock is out of sync. If the pokemon get scanned with 899 s left, you should probably resynchronize it, since then it may scan the point too late but still have another pokemon nearby so it doesn't give an error. Can you post these 2 records, so I can see?

**Comment by ptchamp2016** [comment]
Well, I can't find that pattern again.

Anyway, I updated to the new algorithm and doing another learning scan, so for now, I'll close this.

Thanks anyway!
