### ISSUE TITLE
Stuck on running main0.py

### ISSUE THREAD

**Issue by skeith** [seikur0/PGO-mapscan-opt#144]
How do I fix this error

```
root@ykrn:/home/pgmap# python main0.py
Traceback (most recent call last):
  File "main0.py", line 84, in <module>
    requests.packages.urllib3.disable_warnings(requests.packages.urllib3.exceptions.InsecureRequestWarning)
AttributeError: 'module' object has no attribute 'packages'
root@ykrn:/home/pgmap#
```

**Comment by darkforcesjedi** [comment]
You probably didn't install the dependencies.

**Comment by skeith** [comment]
I have run `pip install -r requirements.txt`
As I have 3 python version, it throws errors on every module so I have to pip2.7 install manually for all the modules

Now stuck on that error. Can't figure out which module causing that

**Comment by plebcity** [comment]
> requests.packages.urllib3.disable_warnings

the requests module isn't properly installed

**Comment by seikur0** [comment]
If you can't fix it, consider installing python 2.7.

**Comment by skeith** [comment]
I have python 2.7, 3.4.3 and 3.5 installed

let me try installing requests module

**Comment by skeith** [comment]
It was because my requests module is outdated. Fixed

**Comment by seikur0** [comment]
Okay good :)
