### ISSUE TITLE
Created spawnpoints, now stuck after trying to start to start iscan.

### ISSUE THREAD

**Issue by ballstorm** [seikur0/PGO-mapscan-opt#146]
Ran through last night before I went to bed, watched the scanner run the initial points without any issue and then I wake up not to intelligent scanning running, but this instead:

Traceback (most recent call last):
  File "C:\Program Files\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "main0.py", line 815, in run
    if curT <= all_sort[pointnum-1][0]:
IndexError: list index out of range

**Comment by ballstorm** [comment]
in cmd it the message also has the header:

Exception in thread Thread-9

**Comment by seikur0** [comment]
Could it be, that you're using an older version? Either way at that point the learninf file is already written and it would be working, if you restart it. I'm currently reworking the spawnpoint recognition, I'll take a look at the transition as well then.

**Comment by ballstorm** [comment]
Uninstalled all other versions of python and cleaned things up a bit. Trying it out with a fresh clone and install of python and threw some more accounts at it, wasn't using many on the first trial run (not sure why tbh...). Will let you know.

**Comment by ballstorm** [comment]
Same issues from a clean install... I'm tempted to see if I can get things running on another system now... even when I restart the server with python main0.py (after the learning file has been written) I get the same error.

**Comment by fvarellalopes** [comment]
I am facing the same issue

[+] Starting intelligent scan mode.

[+] Spawn point count: 291
[+] Type: 1x15, Count: 0, Percentage: 0.0%
[+] Type: 1x30, Count: 0, Percentage: 0.0%
[+] Type: 1x45, Count: 0, Percentage: 0.0%
[+] Type: 1x60, Count: 0, Percentage: 0.0%
[+] Type: 2x15, Count: 0, Percentage: 0.0%
[+] Type: 1x60h2, Count: 0, Percentage: 0.0%
[+] Type: 1x60h3, Count: 0, Percentage: 0.0%
[+] Type: 1x60h23, Count: 0, Percentage: 0.0%
[+] Type: UNDEF/DEF, Count: 291, Percentage: 100.0%

Exception in thread Thread-5:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "main0.py", line 815, in run
    if curT <= all_sort[pointnum-1][0]:
IndexError: list index out of range

**Comment by seikur0** [comment]
Well, if you have only UNDEF/DEF points, don't expect it to work. At least you, fvarellalopes, need to repeat the learning phase. How many workers did you use during that, what was your interval seting and what was your actual interval?

**Comment by ballstorm** [comment]
Just switched to the dev branch instead of the master and its working fine for me now. I also reduced the scan range a bit though as well.

**Comment by ballstorm** [comment]
@fvarellalopes I'd look into what seikur0 has to say, make sure you're running at least a handful of workers (accounts) and have the range and interval set correctly for optimal initial scans. Might even want to reduce range down to 15 or less (depending on how many workers you have). I reduced my scan interval down to 300 for the initial scan as well.

**Comment by seikur0** [comment]
In principal you're very right, just a comment, the scan interval is fine at 600 as long as you stay below it.

**Comment by ballstorm** [comment]
^ aweseome thanks for the tip :) probably best for "longevity" purposes to keep the scan interval right below that threshold I would assume

**Comment by fvarellalopes** [comment]
I was using only one worker.
It is working fine now with 15 workers and range 15. :D

**Comment by seikur0** [comment]
Okay :) Closed.
