### ISSUE TITLE
Some Hanging on "Login refresh"

### ISSUE THREAD

**Issue by Trustmania** [seikur0/PGO-mapscan-opt#147]
Hi,

so after 1 day using, i'm happy with your work. Nice application. But i figured out, that after 1-2h if the tooling is doing the "Login refresh" it is hanging and will be killed after some time.

Is this known? Is there a workaround or even a fix for this issue?

The last lines of the log:

> [+](16) Taubsi visible for 637 seconds (1108m SE from you)
> [+](92) Nebulak visible for 901 seconds (1079m E from you)
> [+] Login refresh.
> [+] Login refresh.
> [+] Login refresh.
> [+] Login refresh.
> [+] Login refresh.
> [+] Login refresh.
> [+] Login refresh.
> [+] Login refresh.
> [+] Login refresh.
> [+] Login refresh.
> [+] Login refresh.
> [+] Login refresh.
> [+] Finished: 6.0 %
> [+] Login refresh.
> [+] Login refresh.
> [+] Login refresh.
> [+] Login refresh.
> [+] Login refresh.
> [+] Login refresh.
> [+

Btw: Do you have som proposals how much accounts would work as best and how big  the scan area should be?

Best regards,
Sascha

**Comment by seikur0** [comment]
Login refreshs are a normal thing to happen and if you have many accounts running, you'll see many of these. What do you mean hanging?^^

For iscan something like 10-20 Accounts for a range 30 area, during the learninf phase about 70 maybe?

**Comment by Trustmania** [comment]
I mean, that after the last **[+** nothing comes again and on the console comes **killed**

```
~/PGO-mapscan-opt$ nohup python main0.py >> pgo_mapscan5.log
nohup: ignoring input and redirecting stderr to stdout



Killed
```

Do you have some debug level for the logging?  

I have ~ 300 accounts is this maybe to much?

**Comment by seikur0** [comment]
It probably is too much, softbans happen with 150 or something accounts over one ip.

Well something on your server must have killed it. It's your server, don't expect me to know, what/who killed it. If it crashed, there would be some error message, but killed means, it was forcefully terminated by something external.

**Comment by Trustmania** [comment]
Ok, thank you, i will reduce it to < 150...

Maybe the logfile produced the kill. Who knows ... i will try to debug this with some debug output.

Can you set this ticket into the state "on hold" or do you have only open and cloesd?

**Comment by seikur0** [comment]
I'll close it and if you think it's something on my side, you can reopen it.

**Comment by Trustmania** [comment]
Good morning,

so it seams, that the issue was connected with to much accounts. With < 150, it is working very well since yesterday!

Best regards,
Sascha

**Comment by seikur0** [comment]
If I had to guess, I'd say your system thought, there were too many connections going out from that program and killed it. Maybe some anti-malware measure, I don't know.
