### ISSUE TITLE
main0.py starts, but won't start scanning

### ISSUE THREAD

**Issue by dwenzier** [seikur0/PGO-mapscan-opt#148]
So I pulled the latest version of your scanner.
Installed it like in the readme.
Put all the accounts and info in the usersettings.json.
Fired up main0.py and it starts without errors.
I get the following output:

[main0.py console](http://i.imgur.com/706W2eg.png)

After this it does nothing, no error, no scanning.
If i start up the webserver, I see an empty map.
What am I doing wrong? It doesn't give me any errors to look at...
I left it like this for about 8 hours, nothing happened.

**Comment by seikur0** [comment]
That is very weird, normally it should start scanning after the logins and also indicate that^^ Did you use 11 accounts(meaning they were all logged in correctly)? Does it happen every time?

**Comment by seikur0** [comment]
Are you using python 2.7? Seems like a queue issue and python 3 doesn't have that module I think.

**Comment by BlackeB** [comment]
http://pastebin.com/cNBaE5VE
my settings

**Comment by BlackeB** [comment]
I'd be willing to run a debug version for you if you would like to

**Comment by seikur0** [comment]
Try it with just one account just to see, if it works.

**Comment by BlackeB** [comment]
Over some time , I have slowly increased the amount of accounts, I got it up to 50, but once I pass 50, it no longer works :/

**Comment by seikur0** [comment]
Huh, weird. And if you set "login_simu" to false in the settings?

Or maybe it's a single account, that's giving you trouble, don't ask me how :/ So if you don't use the 51th account or something?

**Comment by BlackeB** [comment]
it does not work again if set to false

**Comment by dwenzier** [comment]
I had login_simu set to false. That's what kept it from starting to scan.
I have python 2.7 and it wouldn't start every time I tried it.

Works flawless since I set it to true.
So something is not working with "login_simu=false".

**Comment by seikur0** [comment]
Okay.. And for you BlackeB? I'm not sure, what to make of your last post :D

**Comment by BlackeB** [comment]
Sorry, when I had set it to false, the program got stuck again, after using it again today, sometimes it doesn't work with 50 accounts, but a quick restart and it work flawlessly again

**Comment by seikur0** [comment]
Sometimes one of them needs a little bit more time(, because it's special?!) So it may be good to wait something like half a minute before restarting. But that seems to be a different case here. Also when you restart, you should always wait something like 2 minutes in between, because too many logins in a row seem to trigger an ip softban.

**Comment by BlackeB** [comment]
Yes I understand the way that works and did allow time for that, can the ip even get softvanned if the accounts login though? I would assume it would just block login and now all us to login our accounts before stopping us

**Comment by seikur0** [comment]
When the ip gets softbanned everything is working fine, expect that the server responses don't contain map objects=pokemon.

**Comment by BlackeB** [comment]
Ah, I understand, but if you take a look at the first guy's console output, the scan operation doesnt seem to even start, I may be mistaken, but wouldn't it display the amount of threads and such after login is complete? It seems to stop working a step before the mapper actually launches

**Comment by BlackeB** [comment]
I don't code in python, so don't hesitate a second to correct me if I'm wrong, just trying to throw out ideas

**Comment by JohnHKoh** [comment]
I have the same problem. Either the map stops scanning after the catch up phrase, or it switches to silent mode and stops scanning.

**Comment by BlackeB** [comment]
That doesn't seem to be the same issue, check your setting file and make sure scannum is set to your likings, our issue is the scan never starts

**Comment by seikur0** [comment]
It doesn't stop scanning, it's just silent Johnny ;)

(Not saying that softbans are the cause here, I just wrote about it, since you brought it up.) Yeah, I'm not sure, what's causing that issue, do you have anything special about your system?

**Comment by BlackeB** [comment]
No, just a standard windows 10 laptop

**Comment by seikur0** [comment]
Okay, I made a branch for this, try it out and post, what it has to say to us..

**Comment by BlackeB** [comment]
I will once I get home, should be late tonight

**Comment by seikur0** [comment]
That's fine, there don't seem to be an awful lot of people with that problem (2) :P

**Comment by BlackeB** [comment]
Haha very true, I'm just trying to help you out bug fix, I got mine working most of the time so only one really haha

**Comment by baottousai** [comment]
i think i'm having the same problem

**Comment by fvarellalopes** [comment]
I am also facing this issue.
It just stops on API endpoints

**Comment by seikur0** [comment]
There is a bugfix branch for this, try it and write the output in here.

**Comment by fvarellalopes** [comment]
Using the bugfix branch, the log printed a lot of authentication errors.
After replacing all accounts in usersettings.json with new ones, it worked. 
I tested this usersettings.json with new accounts in the master branch and it is working too.

**Comment by seikur0** [comment]
It would be helpful for me to know, what exactly was printed.

**Comment by fvarellalopes** [comment]
-removed- the issue was a missing email verification.

**Comment by seikur0** [comment]
Okay, but that's a different issue than the one in this thread, the bugfix version does show these errors the same as the normal one. If you give me the account data for one of the code 200 accounts, I can probably improve the error message to be specific. (PM it to me on reddit, if you want.)

**Comment by fvarellalopes** [comment]
-removed-

**Comment by seikur0** [comment]
Thanks, that was helpful, it now gives you a detailed message. If you check it, you'll find that all these accounts weren't banned but rather they're missing their email verification. At least for [1] that's the case. I'll remove your file from the post, so nobody is tempted ;) And I'll shorten the above post as well.

**Comment by seikur0** [comment]
Doesn't seem to be a problem anymore, closed.
