### ISSUE TITLE
Map tiles do not load on MobileSafari (iOS) and Safari on OSX

### ISSUE THREAD

**Issue by c00ni** [seikur0/PGO-mapscan-opt#149]
Works fine in Chrome on OSX.

The error console in Safari has 2 things, first
`Line 167 Unexpected token '>'`
Line 167 being `wholedata = wholedata.filter(entry => entry[5] > timenow);` in function cleanWholedata()

and also in https://maps.googleapis.com/maps/api/js
`InvalidValueError: initMap is not a function` on line 1874:5?

This is using the current commit (https://github.com/seikur0/PGO-mapscan-opt/commit/ca18c1b8b696b7a61eb9f11a442863c00df1d0c7).
This is the first commit I've tried to use since you changed to the new DB system and map. Old map still running fine.
I'm running the new one on a different port and instance of pokesite.

**Comment by seikur0** [comment]
Yeah apparently some browsers don't like the arrow functions, somebody did a pull request for this before and I must have accidentally reverted it :/ You know how I do that from time to time :D Now it should be working.

**Comment by c00ni** [comment]
Hurrah!
(Fixed indeed)
