### ISSUE TITLE
Choosing correct spawn point file

### ISSUE THREAD

**Issue by ftuttle5** [seikur0/PGO-mapscan-opt#150]
If I've made multiple spawn point files (e.g. 33.8xxx83_-84.4xxx153_20_70.0.JSON), how do I control which one main0.py uses?

**Comment by seikur0** [comment]
It uses the file for which the name corresponds to the used scan parameters.

**Comment by ftuttle5** [comment]
And what does the 70.0 at the end stand for?

**Comment by Coalado** [comment]
70m Cell radius

**Comment by seikur0** [comment]
Yeah, it's the scan radius we have, so not an option for you but rather an option in case N'Tic changes that radius again.
