### ISSUE TITLE
pausetime: [False, True, True, True]

### ISSUE THREAD

**Issue by rostah-r** [seikur0/PGO-mapscan-opt#151]
Hi all, I'm about 2 hours into my initial scan and everything was going fine. The first 10 or so Runs went perfect, but now most pokemon found display the following or something similar...

+] (21) Spearow visible for 555 seconds (314m NE from you)
id: 4966207003889, spawntime: 26.7910000011, pausetime: [False, True, True, True]

Any ideas what this means?

**Comment by seikur0** [comment]
That's the spawnpoint recognition at work (a debug message which I left in there at some point and forgot to take out). So it's perfectly normal. You have a fine 1x15 point right there ;)
