### ISSUE TITLE
acceptable number of undefined areas?

### ISSUE THREAD

**Issue by ftuttle5** [seikur0/PGO-mapscan-opt#155]
I've collected a range 31 spawn set with 80 accounts, and 2.6% of the spawns are undefined. Does this indicate I may want to remake my spawn points file?

Note: Scan time was only 7-9 minutes

**Comment by seikur0** [comment]
Did you collect them with the old or the new algorithm?

the acceptable number in general is 0 ;)

**Comment by ftuttle5** [comment]
I downloaded your algorithm 2 days ago

**Comment by seikur0** [comment]
Okay, then rescan it with the new algorithm, it has various improvements, that help in avoiding undefined points and it also only takes less than 1 hour.

**Comment by ftuttle5** [comment]
Great, thanks for the help as always seikur0
