### ISSUE TITLE
Getting multiple "n seconds behind" messages

### ISSUE THREAD

**Issue by ghost** [seikur0/PGO-mapscan-opt#157]
The complete message follows the pattern:

[+] Time: 15:15:05, ID: 0, Lat: x, Lng: x, Range: 30, Start: 07:54:02

631.67 s behind
538.32 s behind
1259.7 s behind
....

And many more like these last 3 messages (the whole pattern keeps repeating). Any clue what might have caused this? Do I stop the execution and try again? I'm asking since the execution has been going on for a long-ish time and if I could avoid losing the spawn points already scanned, that'd be great.

**Comment by seikur0** [comment]
You're in iscan mode already, so you don't lose spawn points or anything (by that I mean the learning file) These messages basically mean, that you don't have enough workers. If you do have enough workers, that time will decrease resulting in phase 2 of the iscan start to finish. If you don't they can't keep up with the new spawns and start lagging behind.

**Comment by ghost** [comment]
Thank you very much for replying. That is very likely the case, since I left the default scan range and added only 10 accounts. Maybe I've missed it, but did you recommend a min # of workers per scan range?
I'll ctrl+z the execution and add more accounts anyway, thanks again!

**Comment by seikur0** [comment]
I didn't recommend a min of workers, but rather a maximum for the scan interval and with just 10 workers for the standard range you must have been well above it and your learning file is pretty much worthless. For the standard range you'd need something like 70 for rural areas and 50 for urban areas during the learninf phase and then 10 (rural) to 20 (urban) workers during iscan. Get the newest release, if you haven't done so yet, for that it only takes below 1 hour to do the learning phase.

**Comment by ghost** [comment]
Thank you for the thorough explanation! I'll just add more accounts and start again, then :)
