### ISSUE TITLE
Rudimentary Tor support

### ISSUE THREAD

**Issue by Dracon23** [seikur0/PGO-mapscan-opt#158]
I use Tor to proxy Scanner requests. About two and a half hours into initial scanning, it keeps saying your IP is banned...

A reconfigurable timer that retries every x seconds (e.g. 30 sevs) would be really nice for these cases, AS I can force Tor to cycle circuits after x seconds oft inactivity.

**Comment by seikur0** [comment]
With Tor, do you set a sock5 proxy? So basically you want a timer, that retries every 30 seconds, if the ip is banned? Or does the proxy have to change in some way then?

**Comment by Dracon23** [comment]
Socks5,yes...

Basically, what I am looking for is a way to match retrying with tor's circuit cycling rhythm. Currently, Ehen an IP ie banned, the Programm just stops doing anything and sits there.

**Comment by seikur0** [comment]
That means the proxy address stays the same, right?

**Comment by Dracon23** [comment]
Yes, TOR operates through a local socks5 proxy, only the exit IP changes. You can check whether the IP is torified via polling https://check.torproject.org/api/ip - returning json looking like {'isTOR':true, 'ip':<insert tor IP here>}... The main issue at hand though is that even when I hit the MaxCircuitDirtiness time (which I currently set at 60 seconds of inactivity), I still have to start over (mostly just before that 3-hour sweet spot)

**Comment by seikur0** [comment]
There is no 3-hour sweet spot anymore. It only takes 1 hour max now ;) I'll still add a timer of 30 secs to that ip banned message, in case the proxy is set and starts with socks5

**Comment by Dracon23** [comment]
That'll work with me, but keep in mind that other people might use different MaxCircuitDirtiness-Settings. I'd make that retry configurable, if it's not too much work.

**Comment by seikur0** [comment]
I'll do that, thanks for the hint.

**Comment by seikur0** [comment]
I implemented this and set it to 30 seconds for now. I'll make it a setting at some point. (Keeping this open to remind me of it.)

**Comment by Dracon23** [comment]
I've just raked in the newest, looks good so far, thanks for the work.

**Comment by seikur0** [comment]
Added as setting, closed.
