### ISSUE TITLE
Pushbullet API Limit/Throttle?

### ISSUE THREAD

**Issue by FrozenSocket** [seikur0/PGO-mapscan-opt#159]
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "main0.py", line 1304, in run
    pushacc.push_link(notification_text, 'https://maps.google.com/?ll={},{}&q={},{}&z=14'.format(wild.latitude, wild.longitude,wild.latitude, wild.longitude), body=time_text)
  File "C:\Python27\lib\site-packages\pushbullet\pushbullet.py", line 259, in push_link
    return self._push(data)
  File "C:\Python27\lib\site-packages\pushbullet\pushbullet.py", line 267, in _push
    raise PushError(r.text)
PushError: {"error":{"code":"pushbullet_pro_required","type":"invalid_request","message":"Pushbullet Pro is required to make this call.","cat":"\ud83d\ude40"},"error_code":"pushbullet_pro_required"}

Additional Info: https://docs.pushbullet.com/#limits

**Comment by seikur0** [comment]
So you went over the limit of 500 requests, I'd say. They added these limits shortly after Pokemon GO came out and they plan to stop their free service completely. You may want to use Telegram instead.

**Comment by FrozenSocket** [comment]
Yes :/ I'll look into a telegram bot later today.

This appeared to hang the scanning threads, catching and periodically pushing the error to screen every so often would be helpful. Personally I would rather the program flagged the limit and continued to progress bypassing future api calls.

**Comment by seikur0** [comment]
Okay I did exactly what you said last in the new release (hope it's working as intended), closed.
