### ISSUE TITLE
Error when running spawnfix.py to merge two initial scans

### ISSUE THREAD

**Issue by FrozenSocket** [seikur0/PGO-mapscan-opt#160]
python spawnfix.py

[+] Spawn point count: 0
Traceback (most recent call last):
  File "spawnfix.py", line 152, in <module>
    main()
  File "spawnfix.py", line 130, in main
    spawnstats(alldata)
  File "spawnfix.py", line 37, in spawnstats
    print('[+] Type: {}, Count: {}, Percentage: {}%'.format(typestrs[t], typecount[t], round(100.0 \* typecount[t] / tallcount, 2)))
ZeroDivisionError: float division by zero

**Comment by seikur0** [comment]
Did you put the two learning files into the same folder? :)

**Comment by FrozenSocket** [comment]
I did, however clearly not the right folder :/. From whatever thread I read about using the spawnfix.py file I thought they had to both be in the res folder but I can see they should be in the project root folder.

Again maybe catching the error and slapping us in the face with our incompetence would help :)

**Comment by seikur0** [comment]
Probably xD Well I can just slap you in the face with that here meanwhile :D I added an error message now.

**Comment by yyarp** [comment]
hi, i got the same error few minutes ago, tried putting those files in one folder, but it didn't work. any other way to make it work?
