### ISSUE TITLE
Error in main0.py when launching 'add_location_name'

### ISSUE THREAD

**Issue by phattbeats** [seikur0/PGO-mapscan-opt#165]
Hello,
Not sure what I am doing wrong. Set up according to readme, added 85 accounts using your script, checked with JSONlint, no errors in settings file. I don't see anywhere to add a location name except for the command arguments.

I did try to add pushbullet notification settings, and I also added more Pokemon ID's to the notification section. don't know if that is incorrect?

D:\Pokemon Go Tools\intelligent scan map>python main0.py
Traceback (most recent call last):
  File "main0.py", line 1507, in <module>
    main()
  File "main0.py", line 1377, in main
    accounts = do_settings()
  File "main0.py", line 231, in do_settings
    if allsettings['notifications']['add_location_name']:
KeyError: 'add_location_name'

Thanks

**Comment by seikur0** [comment]
You sir, have an outdated settings file, update it.

**Comment by UmbaSimpy** [comment]
i got the newest setting and i get this error too.
Turning to False notifications fixes it
I'm currently trying to use telegram ones

"notifications":
  {
    "enabled": false,
    "push_ids": [1,2,3,4,5,6,7,8,9,131,132,142,143,144,145,146,147,148,149,150,151],
    "pushbullet":
    {
        "enabled": false,
        "api_key": ["PUT_YOUR_PUSHBULLET_API_KEY_HERE"],
        "use_channels": false,
        "channel_tags": [""]
    },
    "telegram":
    {
        "enabled": true,
        "bot_token": "287038698:AAHwKjX7dSy0hizpH8vguDwWz3EkjWT1vI4",
        "chat_ids":["-167917213"]
    }

**Comment by seikur0** [comment]
Getting an up to date settings file fixes it as well as stated before..
