### ISSUE TITLE
Map stops scanning

### ISSUE THREAD

**Issue by JohnHKoh** [seikur0/PGO-mapscan-opt#166]
Not sure what's causing this, but before iscan started it used to work perfectly, but now after iscan has been enabled, once the catch up phase completes, the scan never starts. Sometimes it picks up 2 or 3 Pokemon, but after that nothing gets updated. The catch up phase also doesn't show me any Pokemon.

Not sure if this matters as well, but 54% of my scanned spawn points are UNDEF/DEF.

Thanks.

EDIT: It started working again after a few minutes, but all the Pokemon picked up says they despawn in 59 minutes.

**Comment by seikur0** [comment]
If more than 0% of your scanned spawn points are UNDEF you're doing something wrong, I already said plenty about this in plenty of other issues and it's in the readme and the newest version gives notifications. I don't know what I should do more.
