### ISSUE TITLE
all pokemon disappear at constant time

### ISSUE THREAD

**Issue by AKuHAK** [seikur0/PGO-mapscan-opt#167]
After [commit ](https://github.com/seikur0/PGO-mapscan-opt/commit/0fba75bbda9d04e91f8b66cd84de79740825930d)all pokemon disappear at constant time. For example all pokemon that appear from 14:00 till 15:00 will disappear at 15:00 which of course cannot be true :)

**Comment by seikur0** [comment]
@cmende, what did you do^^

No seriously though, AKuHAK read the readme and it will become clear to you ;)

**Comment by AKuHAK** [comment]
I was reading readme. This is last commit when ALL pokemon starts disappearing at constant time. All pushbullet notifications will show me that every pokemon will disappear in 15:00

**Comment by AKuHAK** [comment]
I just run latest version and get pushbullet message that poliwag will disappear at 22:00:00 than I get message that Magikarp will disappear at 22:00:00 than I get message that rattata will disappear at 22;00:00.
Than I open map at 8000 port and see in the map that TTH is completely the same for all found pokemon. I mean really for ALL (map is full with pokemon which have 25 minutes till disappear).

Than I reverted into [this version](https://github.com/seikur0/PGO-mapscan-opt/commit/0fba75bbda9d04e91f8b66cd84de79740825930d) and it shows me correct information (magikarp will disappear after 3 minutes and then appears after 15 minutes, spearow will disappear after 1 minutes and so on)

**Comment by seikur0** [comment]
Then tell me, did you use spawnfix.py to migrate your learning file(s) to the new format as stated in the readme?

**Comment by AKuHAK** [comment]
Sorry didn't mention this in readme - my bad. Now everything is working fine :) Thanks for help.
