### ISSUE TITLE
Telegram-Reporting fails

### ISSUE THREAD

**Issue by Dracon23** [seikur0/PGO-mapscan-opt#170]
**Config:**

  "notifications":
  {
        "enabled": true,
        "push_ids": [1,2,3,4,5,6,7,8,9,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,43,44,45,48,49,50,51,52,53,56,57,58,59,63,64,65,66,67,68,69,70,71,72,73$
        "add_location_name": true,
        "pushbullet":
        {
                "enabled": false,
                "api_key": ["PUT_YOUR_PUSHBULLET_API_KEY_HERE"],
                "use_channels": false,
                "channel_tags": []
        },
        "telegram":
        {
                "enabled": true,
                "bot_token": "BetachWishTheTelegramTokenWasHere",
                "chat_ids":["@ShadowCatchInfo"]
        }
##   },

**Error**

Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in **bootstrap_inner
    self.run()
  File "main0.py", line 1389, in run
    telebot.sendMessage(chat_id=telegram, text='<b>' + notification_text + '</b>\n' + time_text, parse_mode='HTML', disable_web_page_preview='False', disable_notification='False')
  File "/home/lofwyr/.virtualenvs/pgom/local/lib/python2.7/site-packages/telepot/__init**.py", line 409, in sendMessage
    return self._api_request('sendMessage', _rectify(p))
  File "/home/lofwyr/.virtualenvs/pgom/local/lib/python2.7/site-packages/telepot/__init__.py", line 398, in _api_request
    return api.request((self._token, method, params, files), **kwargs)
  File "/home/lofwyr/.virtualenvs/pgom/local/lib/python2.7/site-packages/telepot/api.py", line 131, in request
    return _parse(r)
  File "/home/lofwyr/.virtualenvs/pgom/local/lib/python2.7/site-packages/telepot/api.py", line 126, in _parse
    raise exception.TelegramError(description, error_code, data)
TelegramError: (u'Bad Request: channel not found', 400, {u'error_code': 400, u'ok': False, u'description': u'Bad Request: channel not found'})

I've tried various things, bot is in a public channel, is an admin, I'm stumped as to what I did wrong...

**Comment by jRam84** [comment]
Im having issues starting the scanner with Telegram enabled after the latest pull also. 

File "main0.py", Line 1554, in <module>
  main()
File "main0.py", Line 1424, in main
 accounts = do_settings()
 File "main0.py", Line 278, in do_settings
  if allsettings['notifications']['add_location_name']
Key Error: 'add_location_name'

After I set Telegram notifications to False in the usersettigs.json the scanner works.

**Comment by seikur0** [comment]
@jRam84: Get the newest setting file.

**Comment by jRam84** [comment]
That fixed it. I was being lazy and just copy pasted the old usersettings.json

Thank you.

**Comment by seikur0** [comment]
@Dracon23: Okay, while the channel name is ShadowCatchInfo, the actual tag name is just @ShadowCatch in your case, so it's no wonder, that the channel isn't being found.

**Comment by Dracon23** [comment]
Tch, Telegram, way too complex for things like this... 

Lessee if that fixed it...
