### ISSUE TITLE
website not responding after few hours

### ISSUE THREAD

**Issue by dikkedeur** [seikur0/PGO-mapscan-opt#171]
I have been running this for a day roughly now.
but the website stops responding after some time, so you get a blank page.
tried everything, on the console there is no error to be found.
the only solution is close the pokesite.py instance and start it up again..

seems that after an amount of time there is a timeout if you dont use the site and that makes it non responsive.

**Comment by seikur0** [comment]
I'm not sure, what could be causing this, I'll try to keep an eye on it.

**Comment by dikkedeur** [comment]
i think it happens on roughly 2 hours of running...

**Comment by seikur0** [comment]
2 hours without touching the website at all? Or can you use it in these 2 hours?

**Comment by dikkedeur** [comment]
without touching the website aka visiting it.. 
so you run it, go to website, it works, come back 2 hours later... it will not respond at all, no errors in console.
like it refuses connections

**Comment by seikur0** [comment]
Okay, I'll try it tomorrow.

**Comment by seikur0** [comment]
I might have fixed this just now, please test it and tell me, if it's still freezing.

**Comment by dikkedeur** [comment]
okay i have just updated... lets see how it goes..
i have already a new thing since the change.. dont know but i just encounter it multiple times.

im messing around with the icons setting, looking what looks best for my taste.
Now i close the pokesite.py instance, make a change in the config for the icons.
and then i start a new instance.
it seems that if you are too quick that it wont start, you dont get the message that it is listening to port etc. etc.. its just blank in the console.
so i close it again, sometimes i must do that multiple times.
it can be that the port it is listening to is still then in use by the old instance and is not freed..
do you know if that is intentional? how long is that? or is that a bug.

to fix this i must sometimes close and reopen the pokesyte.py instance multiple times, and suddenly it "catches" it and run.
i didnt encounter that before.. so it might be due the code change....
now i must wait if it keeps on running.. ^^

**Comment by seikur0** [comment]
I don't have such a thing, for me it "catches" immediately every time. If the port is already taken, it would give an error. I'll try changing the icon settings a few times, maybe I'll encounter it :D 

By the way, how do you like the icons?

**Comment by dikkedeur** [comment]
well i like the shuffle one, it looks nice, but since im used to the old fashion look i keep it now for standard, im now filtering out the most common pokemons that i encounter like voltorb and such, its truly clustering my map ^^ along with a few others..

its definetly a threading thing on the map.. i now closed it, waited longer then normal like 1 min for typing above text, and now it starts inmediatly.
so if you are too quick since the new threading in the map code it might be that a thread still hangs or is not killed that it wont start up.
just something to know..

so not a truly bug perse.. but if more people encounter it.. then this is it.. dont be to quick..

**Comment by seikur0** [comment]
Yeah I use the standard ones as well, I really like them. But different people have different tastes I guess :) Okay, good to know, Which system are you on? For me it doesn't do that.

**Comment by dikkedeur** [comment]
i use ubuntu server 16.04 LTS dedicated server.. 

i must say im truly truly impressed by how this map works.. on pogom i had 40 accounts and it took roughly 7 min to scan my area..
with this its after the learning time 2 minutes, if not almost instant lol..
amazing work!!!

**Comment by dikkedeur** [comment]
![schermafbeelding 2016-09-11 om 09 58 50](https://cloud.githubusercontent.com/assets/11842306/18415996/66f22818-7806-11e6-9f5f-33b689100f1a.png)

wow? what is this?? did i miss something? ^^

**Comment by seikur0** [comment]
Seems like a 2x15 spawn point :P https://www.reddit.com/r/pokemongodev/comments/4yzqc2/spawn_point_types_clearing_confusion/

**Comment by dikkedeur** [comment]
aha didnt knew that, well we learn everyday ^^

**Comment by seikur0** [comment]
True :) Now you can spook your friends by seemingly predicting spawns :D

**Comment by dikkedeur** [comment]
scary shit ^^ :p moehahahaha

**Comment by seikur0** [comment]
Step 2: Learn how to make pokeballs hover around you.

**Comment by dikkedeur** [comment]
seems that its now fixed..  ^^

**Comment by seikur0** [comment]
Sweet :)
