### ISSUE TITLE
Not using Spawn Data Base file

### ISSUE THREAD

**Issue by ftuttle5** [seikur0/PGO-mapscan-opt#172]
My "33.8xx83_-84.4xx153_31_70.0.json" file has been created, but when I restart main0.py it is not being used. Instead, the 1 hour spawn find always begins again. My parameters are the same, I am not changing the settings file. Also, spawnfix.py will not recognize the json spawns file either.

**Comment by seikur0** [comment]
It'll tell you the expected name in the beginning (unless you start it in dumb mode that is.) In the most recent version, spawnfix will tell you, that it's looking for the learning files only in the same folder, so you'll have to copy it and after that copy it back.

**Comment by ftuttle5** [comment]
How do I get out of dumb mode? I haven't changed the mode.
I know that the file name should be correct because it has the same coordinates and range as the settings file.

**Comment by seikur0** [comment]
Your're not in dumb mode, if you don't start dumb mode. It does tell you the name of the file in the beginning, if it's missing, so double check that.

**Comment by ftuttle5** [comment]
fixed.
