### ISSUE TITLE
BUG - Website throwing ISE - HTTP 500

### ISSUE THREAD

**Issue by Dracon23** [seikur0/PGO-mapscan-opt#174]
I've passed the learning phase now, still fighting with the website, keeps throwing me a 500 - Internal Server Error when accessing the site.

_**Traceback**_: [dpaste here](https://dpaste.de/ZQBH)
_**Intended Behaviour**_: Should display the mapped data as intended by creator...
_**Actual Behaviour**_: Traceback in Console as seen above, and a 500 Internal Server error on the browser.

**Comment by seikur0** [comment]
Either you're using an outdated version of the index.html or you need to clean your cache.

**Comment by Dracon23** [comment]
i cleaned my Caches and raked in a fresh setup via git pull, still occuring.

**Comment by seikur0** [comment]
which url do you use to access the site?

**Comment by Dracon23** [comment]
http://atlaslabs.tk:25700, where atlaslabs points to the server IP I run this on. Server itself binds to 0.0.0.0:25700

-EDIT- pokesite.py running right now, i cleaned out staticres and raked in another pull, it still errors out...

**Comment by seikur0** [comment]
Okay, should be fixed now.

**Comment by Dracon23** [comment]
Confirmed working now, thanks again for investing into this ;)

**Comment by seikur0** [comment]
You're welcome ;)
