### ISSUE TITLE
"add_location_name" Can't launch main0.py

### ISSUE THREAD

**Issue by UmbaSimpy** [seikur0/PGO-mapscan-opt#177]
As the title says, if I turn on my notifications for Telegram the Main0.py won't launch
I have the newest usersetting file and i can't get it to work
Any fix?
Thanks
Here is the part i'm talking about:

"notifications":
{
"enabled": false,
"push_ids": [1,2,3,4,5,6,7,8,9,131,132,142,143,144,145,146,147,148,149,150,151],
"pushbullet":
{
"enabled": false,
"

**Comment by Dracon23** [comment]
Your config is not the latest, there was a change, add "add_location_name": true or false (depending on whether you want the locations shown)

**Comment by UmbaSimpy** [comment]
I will try and report back,
thx

**Comment by FrozenSocket** [comment]
Also edit your bot_token out, thats private info ^^

**Comment by UmbaSimpy** [comment]
Thx
It worked
I just had to make sure to put it under thre Notification part
Edited it out
Thanks again
