### ISSUE TITLE
Telegram Crash after a while

### ISSUE THREAD

**Issue by UmbaSimpy** [seikur0/PGO-mapscan-opt#179]
As the title says, it just stopped working
I have no idea how to fix it, anybody else having this error?
All the files are from the newest version

Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in **bootstrap_inner
    self.run()
  File "C:\Users\Michele\Desktop\aiuto2\PGO-mapscan-opt-master\main0.py", line 1
393, in run
    telebot.sendMessage(chat_id=telegram, text='<b>' + notification_text + '</b>
\n' + time_text, parse_mode='HTML', disable_web_page_preview='False', disable_no
tification='False')
  File "C:\Python27\lib\site-packages\telepot__init**.py", line 409, in sendMes
sage
    return self._api_request('sendMessage', _rectify(p))
  File "C:\Python27\lib\site-packages\telepot__init__.py", line 398, in _api_re
quest
    return api.request((self._token, method, params, files), **kwargs)
  File "C:\Python27\lib\site-packages\telepot\api.py", line 131, in request
    return _parse(r)
  File "C:\Python27\lib\site-packages\telepot\api.py", line 112, in _parse
    raise exception.BadHTTPResponse(response.status, text, response)
BadHTTPResponse: Status 502 - First 500 characters are shown below:
<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.10.0</center>
</body>
</html>

**Comment by seikur0** [comment]
I'll add error catching to it, when I have the time. It can happen, when the telegram servers are temporarily down/having trouble.

**Comment by UmbaSimpy** [comment]
Luckily it just happened once
The whole night went flawlessly
Thanks for your input
And great job with the scanner
The best by far
Keep up the good work

**Comment by seikur0** [comment]
I'll keep this open, so I don't forget it. It's not a big deal to implement some error catching on this and my tool shouldn't crash, when they have problems.

Thanks :)

**Comment by seikur0** [comment]
Okay, now it won't crash due to Telegram Network Errors anymore.

**Comment by UmbaSimpy** [comment]
Can i just replace the main0.py file with the newest one?

**Comment by seikur0** [comment]
Depends on your previous version, I haven't changed any settings since yesterday, so you should be fine.
