### ISSUE TITLE
Response error, status code: 52, retrying in 1 seconds

### ISSUE THREAD

**Issue by ferazambuja** [seikur0/PGO-mapscan-opt#18]
Just got the last version to work. Everything worked; however, this message showed constantly in my terminal window.
[-] Response error, status code: 52, retrying in 1 seconds
[-] Response error, status code: 52, retrying in 1 seconds

If I change the backup size to 0 returns an error.

**Comment by seikur0** [comment]
Yeah, I semi-fixed it, they seem to be returning only every second hearbeat right now. I lowered the time from 1 to 0.26 seconds, lower and it skips more heartbeats, so the scanning is faster again. For now live with these error messages. backup size 0 should be fixed.

You can comment line 443 out for now, if you want to.

**Comment by ProfessorPokes** [comment]
I have to be missing something. Even with the changes you made, it's just more errors with no scanning.

**Comment by seikur0** [comment]
Comment out line 443, then you won't see the errors anymore. The thing is only every second requests gets returned with an error, so it's still scanning albeit significantly slower. Can't do much about this atm, they changed their server protocol, maybe the anti-cheat campaign has started^^ Either it is a server stressed out bug and it will fix itself or someone needs to figure out the new network protocol.

**Comment by ProfessorPokes** [comment]
Yeah, sorry. So I need to take a nap. I hadn't changed unique_coords to true... it was scanning the ocean, of course it'll come up empty.

**Comment by seikur0** [comment]
I scanned that good old 0,0 point before, not that interesting haha Yeah I'll need to nap too, good night.
