### ISSUE TITLE
[REQUEST] Telegram Bot with IV of found Pokemon

### ISSUE THREAD

**Issue by UmbaSimpy** [seikur0/PGO-mapscan-opt#181]
As the title says, I have seen some implementations with Telegram that make it possible to see the IV and moves
I think that would be a great addition :) 

Here are some thread about it:
https://www.reddit.com/r/pokemongodev/comments/522i6j/telegram_bot_with_iv_of_found_pokemons/

**Comment by seikur0** [comment]
That's a request, that I'll deny, I'm on the contra IV scan side, so I won't implement it.

**Comment by UmbaSimpy** [comment]
Ah I see
Thanks for answering
Do you mind sharing why?

**Comment by seikur0** [comment]
Did the nazi mods remove that discussion thread? Damm them.... (I can say that, I'm german haha) Well basically I think it crosses the line between a feature, that is absolutely needed to play Pokemon GO, the possibility to detect pokemons aka a scanner, and a feature, you don't need and which would just destroy gameplay fun and the sense of achievement for people using it, That's not up for discussion for me.

**Comment by UmbaSimpy** [comment]
Just to make it clear, I was not trying to convince you!
Btw i think it makes sense, and after hearing your opinion I agree with you
It's not essential and It will ruin the fun of going there and holding  your breath to see the IV and moves of the Pokemon
