### ISSUE TITLE
Different proxies per account

### ISSUE THREAD

**Issue by darkforcesjedi** [seikur0/PGO-mapscan-opt#183]
I created 5 proxies, each with a different public IP and distributed my accounts like this, but all of them end up using the same proxy. I only have 1 spawn point file with all my data merged into it and all accounts scan the same area.

```
{
  "id": 0,
  "type": "ptc",
  "username": "account1",
  "password": "password1",
  "proxy": "http://proxy1",
  "coordinates":
      {
          "lat": XXX,
          "lng": YYY
      }
},
{
  "id": 0,
  "type": "ptc",
  "username": "account2",
  "password": "password2",
  "proxy": "http://proxy2",
},
{
  "id": 0,
  "type": "ptc",
  "username": "account3",
  "password": "password3",
  "proxy": "http://proxy3",
},
```

etc.

**Comment by darkforcesjedi** [comment]
Nevermind this is an easy fix I will do a pull request.

**Comment by seikur0** [comment]
It is currently designed so that i'll use the proxy setting from the group leader as you wouldn't have enough proxies for each account normally.

**Comment by darkforcesjedi** [comment]
See my pull request. You may not have a proxy for every account but it is entirely possible to have more proxies than groups/IDs.

My pull request looks like:
If specified on an account, use that proxy
Else no proxy

Or you could expand on my pull and use a preferential choice for proxy:
If specified on an account, use that proxy
Else if specified on main account in group use that proxy
Else no proxy

**Comment by seikur0** [comment]
Yeah I did exactly that, see my comment on your pull request :)

**Comment by darkforcesjedi** [comment]
Very good, but the message logging is inconsistent. It doesn't show if proxies are used from the individual accounts. I only see one message when using multiple proxies:

[+] Using proxy: http://127.0.0.1:3000

**Comment by seikur0** [comment]
That's true, I decided to do that, do you want them to show the proxies at start? Is that useful information? I thought it would just be spamming, so I'm only showing it once right now.

**Comment by darkforcesjedi** [comment]
It's feedback so you can see that it used all your proxies. If you use many proxies it will show 1. Or maybe show a warning message if some accounts but not all accounts have proxies.

Right now it says I am using proxy 127.0.0.1:3000 but it doesn't say anything about :3001 through :3004. When it first ran I didn't know if it was working right.

**Comment by seikur0** [comment]
I doubt you can use that feedback if you're using 30 accounts with 30 different proxies :P I tweaked it, now it'll show the group proxy from the first profile if used and for profiles with a proxy setting for themselves it'll show the proxy as well.

**Comment by seikur0** [comment]
I hope that you didn't want individual proxies implemented to use it with 4 accounts.^^

**Comment by darkforcesjedi** [comment]
I have 62 accounts at the moment but I need to add more. My area has about 23,000 spawn points. I think I need about 80 accounts to cover it effectively. Right now it will catch up occasionally but is usually a few minutes behind. I will also need to figure out how to subdivide my area because after a while my accounts are getting soft banned and I think it is because my area is spread out so much. (The farthest distance between cells is about 50km.)

**Comment by seikur0** [comment]
I see. Yeah you're right, that's what you have to do.
