### ISSUE TITLE
'NoneType' object has no attribute 'groupdict'

### ISSUE THREAD

**Issue by FrozenSocket** [seikur0/PGO-mapscan-opt#184]
[+] Login refresh.
[17] Ptc login error in step 7: 'NoneType' object has no attribute 'groupdict'
[17] Connection error, http code: 400
[17] Retrying...
[+] Login refresh.
[+] Login refresh.
[+] Login refresh.
[+] Login refresh.
[17] Ptc login error in step 7: 'NoneType' object has no attribute 'groupdict'
[17] Connection error, http code: 400
[17] Retrying...
[+] Login refresh.

**Comment by FrozenSocket** [comment]
I've had the NoneType error 9 times today, dont know if one of my accounts are banned or if it's just iffy connection. Just got in so haven't had time to investigate, but wanted to post it up first for feedback.

**Comment by seikur0** [comment]
Iffy connection, as long as it's not the same account number continuously, you don't have to worry. Banned Accounts would be detected and you'd get a message.

**Comment by FrozenSocket** [comment]
Changed routing and all sorted, thanks for feedback.
