### ISSUE TITLE
Spawnfix issue

### ISSUE THREAD

**Issue by darkforcesjedi** [seikur0/PGO-mapscan-opt#186]
Most of my spawn data files were created by the same version of main0.py (a few versions ago). I just updated to the latest and I have found that the new main0 doesn't handle my data file correctly. So I ran the new version of spawnfix on my previous files in order to combine them. The new version of spawnfix can't seem to handle these spawn points:

```
  {
   "pausetime": [
    false,
    false,
    true,
    true
   ],
   "spawntime": 18.6047333329916,
   "pauses": 2,
   "lat": 34.20928178981728,
   "lng": -77.80210425276843,
   "phasetime": 60,
   "type": 1,
   "id": 9460188741015
  },
  {
   "pausetime": [
    50.74165000021458,
    58.77724999934435
   ],
   "spawntime": 47.53619999811053,
   "pauses": 2,
   "lat": 33.924846352196546,
   "lng": -78.07620249033684,
   "phasetime": 90,
   "type": -1,
   "id": 9414744639427
  },
  {
   "pausetime": [
    54.142099998891354,
    0.5714333318173885
   ],
   "spawntime": 52.694466665387154,
   "pauses": 2,
   "lat": 33.932519710879234,
   "lng": -78.0914444118595,
   "phasetime": 90,
   "type": -1,
   "id": 9460210681265
  },
  {
   "pausetime": [
    false,
    false,
    true,
    true
   ],
   "spawntime": 14.785000000149012,
   "pauses": 2,
   "lat": 33.93117370595454,
   "lng": -78.06889272618469,
   "phasetime": 60,
   "type": 1,
   "id": 9460210210535
  },
  {
   "pausetime": [
    false,
    false,
    true,
    true
   ],
   "spawntime": 17.823933336883783,
   "pauses": 2,
   "lat": 33.92186865078818,
   "lng": -78.07210195256287,
   "phasetime": 60,
   "type": 1,
   "id": 9414744642711
  },
  {
   "pausetime": [
    35.75739999860525
   ],
   "spawntime": 33.341000001877546,
   "pauses": 1,
   "lat": 34.099136260944405,
   "lng": -77.92437818581719,
   "phasetime": 30,
   "type": -1,
   "id": 9460193833779
  },
  {
   "pausetime": [
    false,
    false,
    true,
    true
   ],
   "spawntime": 38.54993333294988,
   "pauses": 2,
   "lat": 34.11381799448597,
   "lng": -77.92294991695121,
   "phasetime": 60,
   "type": 1,
   "id": 9460193814929
  },
  {
   "pausetime": [
    false,
    false,
    true,
    true
   ],
   "spawntime": 41.76086666435003,
   "pauses": 2,
   "lat": 34.11557790553383,
   "lng": -77.94499672306677,
   "phasetime": 60,
   "type": 1,
   "id": 9460233180725
  },
  {
   "pausetime": [
    false,
    false,
    true,
    true
   ],
   "spawntime": 43.57899999991059,
   "pauses": 2,
   "lat": 34.09913918447953,
   "lng": -77.92268211444795,
   "phasetime": 60,
   "type": 1,
   "id": 9460193834309
  }
```

The output from spawnfix contains hundreds of thousands of lines containing false false true true false false true true. 4 out of 51 of my spawn files encounter this issue.

**Comment by seikur0** [comment]
Well, what should the poor spawnfix.py file do with those points.

"pausetime": [
    false,
    false,
    true,
    true
   ]

Would mean, it's a 1x30 point, but it also has "pauses": 2, which would indicate a 2x15 point. That conflicting info is why it wasn't fully classified ("type": 1) in the first place and spawnfix can't change anything about that. Type 1 and type -1 points in a file are a very good indication, that it needs to be rescanned.

**Comment by darkforcesjedi** [comment]
I don't know how to interpret the infomation in these files. I will rescan with the new version of main0, but I would suggest spawnfix identify problems and either cull the points or notify that the area needs to be rescanned.

**Comment by seikur0** [comment]
I can put in a message for these points. The newest algorithm won't create 1 points anymore and I thought it is well know by now, that undefined -1 points are bad and shouldn't be in your file.
