### ISSUE TITLE
Grouping accounts [question]

### ISSUE THREAD

**Issue by darkforcesjedi** [seikur0/PGO-mapscan-opt#190]
I am working on subdividing my map into smaller regions and confine certain accounts to certain regions. I just want to make sure I understand how to do this correctly.
- Create a lat_lng_range_70.0.json file for each region
- In the usersettings all accounts for a given region use a matching "id" and the lat and lng match the given filename (only the first account in each group needs a lat and lng specified, as the other ones will inherit it)
- The range in each file name should be the same and all should match the value in usersettings.

Is this correct?

**Comment by seikur0** [comment]
Yes, that's absolutely correct.

**Comment by darkforcesjedi** [comment]
This doesn't seem to be working for me. It only loads the location file and accounts associated with id 0

Here is my usersettings:
http://pastebin.com/LVh2dSnt

**Comment by seikur0** [comment]
You still have to start a new instance for each id.

**Comment by darkforcesjedi** [comment]
And I can launch them all from the same working directory and they all use the same database?

Sorry for all the questions.

**Comment by seikur0** [comment]
Yes they can.

**Comment by ianfreitas1** [comment]
I have like 3 different locations, so if I merge all spawns with spawnfix, will the accounts stay attached to some region or travel all over?

**Comment by seikur0** [comment]
They'll travel, if you put them into the same id group, which is the point of spawnfix. If you don't want that, run different instances.

**Comment by ianfreitas1** [comment]
What do you advise?

**Comment by darkforcesjedi** [comment]
If the farthest points in your region are within 10km or so, I would suggest combining the files and using 1 instance.

**Comment by seikur0** [comment]
For regions close to each other, merge that stuff, for regions far away from each other, you'll run into softban problems then. If you can, always merge, because you're a) improving the worker efficiency and b) decrease the chance of softbans due to too many workers, since each instance is kind of preventing too many network requests at once by smartly delaying them. (secret sauce right there :P) If you use multiple instances, that's not working perfectly anymore.

**Comment by ianfreitas1** [comment]
Awesome, thanks guys!!

**Comment by darkforcesjedi** [comment]
@seikur0 multiple instances are not a problem if you use separate proxies per region.

**Comment by seikur0** [comment]
True. Where do you have your proxies from? I'm sitting here and only have one IP at my disposal T_T

**Comment by darkforcesjedi** [comment]
A paid service. I don't want to post it publicly , because if everyone uses it then the IPs will get blocked by Niantic. Most of the IPs in their pool are already blocked. My home IP is blocked too and I don't know why because I never used any PoGo codes from my home IP.

**Comment by seikur0** [comment]
That's okay, I thought maybe you inherited a IP provider company or something haha

**Comment by darkforcesjedi** [comment]
You could use multiple Tor circuits, but Tor is very slow.

**Comment by seikur0** [comment]
Hm no, I'm good. I'll just make do with one IP for now.
