### ISSUE TITLE
Show optional the time on the map as a label

### ISSUE THREAD

**Issue by Trustmania** [seikur0/PGO-mapscan-opt#191]
I'm on it ...

![image](https://cloud.githubusercontent.com/assets/5430522/18507312/25025fd8-7a70-11e6-8552-5c80b33ccb84.png)

![image](https://cloud.githubusercontent.com/assets/5430522/18507324/2ef7fe08-7a70-11e6-9bb2-2986490c0062.png)

Gefällt soweit? Anmerkungen?

**Comment by seikur0** [comment]
Jo, gefällt mir :)

**Comment by Trustmania** [comment]
Bastel noch den Button...
Hast du ne mail oder so, dass wir mal schreiben können ?

**Comment by seikur0** [comment]
Kannst du mich bei reddit anschreiben? Dann kann ich dir meine Email Adresse als pm schicken.

**Comment by FrozenSocket** [comment]
Slightly off topic but... I personally think the " o'clock " prefix (English version) on the time remaining is overkill. It's extremely clear the information provided is a time and it just feels like screen clutter making the tooltip wider. Who says " o'clock " any more anyway... :)

What time is it... it's 4pm or 10am, you wouldn't say it's 10am o'clock.

**Comment by Trustmania** [comment]
Hehe, this was probably my bad englisch translation ;-)

@seikur0 should we remove the o'clock?

**Comment by seikur0** [comment]
Yeah I thought the same thing about it and with Uhr as well. Though Uhr is less awkward :D,It just seems like clutter. And when you do it, please switch the first and the second line. And make the line with the time into "-until 14:30:53-" or "-bis 14:30:53-", so it's another orientation point for the eyes.

**Comment by Trustmania** [comment]
will be done with the next PR ...

**Comment by seikur0** [comment]
Done and closed.

**Comment by FrozenSocket** [comment]
Is it possible to raise the label about 10+px, maybe just me but looks quite far away from the related icon?
![image](https://cloud.githubusercontent.com/assets/22102429/18517945/1251d532-7a96-11e6-9f3b-d4b56e5f7021.png)

Really great addition, thank you.

**Comment by Trustmania** [comment]
For me it is fitting:

![image](https://cloud.githubusercontent.com/assets/5430522/18518202/59c73f84-7a9f-11e6-8166-226d7bb063e7.png)

![image](https://cloud.githubusercontent.com/assets/5430522/18518222/6f087d0e-7a9f-11e6-86cf-6d8a10f91a6d.png)

![image](https://cloud.githubusercontent.com/assets/5430522/18518250/94962bca-7a9f-11e6-9dda-bf8d0565a4a2.png)

What do you have as a scalefactor? I have 0.7

**Comment by FrozenSocket** [comment]
I'm also 0.7 using latest Chrome, same in Edge

**Comment by FrozenSocket** [comment]
![image](https://cloud.githubusercontent.com/assets/22102429/18519147/b77ffc24-7a9a-11e6-8a90-e9ea369c76ce.png)

Changing yOffset to 15 sorts it for me, nice and snug :)

Don't know why the difference in our renders but maybe something that could go in the config?

**Comment by Trustmania** [comment]
Yes, why not
