### ISSUE TITLE
[Request] Show affected account which errors in console

### ISSUE THREAD

**Issue by FrozenSocket** [seikur0/PGO-mapscan-opt#192]
[-] auth/token error, refreshing login...

Which account/login has the error and is been refreshed? 
# 

[52] Ptc login error in step 7: 'NoneType' object has no attribute 'groupdict'
[52] Connection error, http code: 400
[52] Retrying...

Which account has the error and is been retried?
# 

You see where I'm going with this :)

**Comment by seikur0** [comment]
Since auth/token errors can always be resolved I don't think it's that useful to put out the number. But yeah, I can do that^^

**Comment by claimer21** [comment]
I'm getting this error a lot with no indication as to what account is affected.  This would be extremely helpful.

**Comment by seikur0** [comment]
Implemented in the update and closed.
