### ISSUE TITLE
[Question] Acceptable thresholds of UNDEF?

### ISSUE THREAD

**Issue by FrozenSocket** [seikur0/PGO-mapscan-opt#193]
[-] Learning file contains 3 undefined spawn points. It is advised to recreate it. This can happen, if you either run into softban issues during the scan (very high range/very high amount of workers/other reasons) or if you're not using enough workers for your range.
...
...
[+] Type: UNDEF/DEF, Count: 3, Percentage: 0.09%
# 

Do I really need to recreate my learning file to remove 3 UNDEF (0.09%)?

The first time I created a learning file it had 2 UNDEF
The second time I created the learning file it had 1 UNDEF

I merged these learning files with spawnfix.py so now I have 3 UNDEF.

Would appreciate your advice clarifying the above. Thanks.

**Comment by seikur0** [comment]
You don't need to, if you're fine with 3 points not being scanned, but as stated in the message I'd advise it ;)

**Comment by FrozenSocket** [comment]
What I wondered is when you run spawnfix.py does it de-dup the spawn points or am I scanning all my spawn points twice every spawn refresh?
The file size doubled running spawnfix.py on the two files which didn't make sense to me if I'm honest - I expected it to stay about the same as its a record of spawn points and these have not increased, regardless of the number of times I create a learning file.

**Comment by seikur0** [comment]
It does de-dup them. And it also prefers non -1/1 while doing that. At least that's what it was supposed to do, but I just checked it and I failed :D In one of the last updates, I destroyed that functionality, just now I fixed it again.

**Comment by FrozenSocket** [comment]
Better crack on with another learning file then :)

**Comment by seikur0** [comment]
Before that try merging your files again and see, if the merged one still has UNDEF points, if they're not UNDEF in all your files, they won't be in the merged one.

**Comment by FrozenSocket** [comment]
Another learning scan and another 2 UNDEF, could it be the scan doesn't understand one type of spawn type? [+] Type: UNDEF/DEF, Count: 2, Percentage: 0.09%

[+] Spawn point count: 2141
[+] Type: 1x15, Count: 1920, Percentage: 89.68%
[+] Type: 1x30, Count: 129, Percentage: 6.03%
[+] Type: 1x45, Count: 13, Percentage: 0.61%
[+] Type: 1x60, Count: 1, Percentage: 0.05%
[+] Type: 2x15, Count: 76, Percentage: 3.55%
[+] Type: 1x60h2, Count: 0, Percentage: 0.0%
[+] Type: 1x60h3, Count: 0, Percentage: 0.0%
[+] Type: 1x60h23, Count: 0, Percentage: 0.0%
[+] Type: UNDEF/DEF, Count: 2, Percentage: 0.09%

All the learning scans finished well under 500 seconds each.
I just cant explain the continued UNDEFs...

# 

The old learning file (2 merged together) looked like this...

[+] Spawn point count: 3335
[+] Type: 1x15, Count: 3020, Percentage: 90.55%
[+] Type: 1x30, Count: 179, Percentage: 5.37%
[+] Type: 1x45, Count: 15, Percentage: 0.45%
[+] Type: 1x60, Count: 1, Percentage: 0.03%
[+] Type: 2x15, Count: 117, Percentage: 3.51%
[+] Type: 1x60h2, Count: 0, Percentage: 0.0%
[+] Type: 1x60h3, Count: 0, Percentage: 0.0%
[+] Type: 1x60h23, Count: 0, Percentage: 0.0%
[+] Type: UNDEF/DEF, Count: 3, Percentage: 0.09%

# 

You can see the spawn point counts don't match (not even close), surely this isn't right for the same settings on all learning scans?

**Comment by seikur0** [comment]
Was that with the broken merge? Were they all scanned with the new algorithm (which is generally better)? Could be softban issues at work here, if you want, I'll try scanning these 2 points myself. Are they always the same?

**Comment by FrozenSocket** [comment]
These are all post move to 1hour learning time, <S>I assume that's why Type: 1x60h2 and Type: 1x60h3 etc are zero because the learning process isn't long enough to detect them?
Could that be what is registering as undefined maybe?</s>

No, I haven't run spawnfix.py since you corrected it.

**Comment by FrozenSocket** [comment]
After running spawnfix.py on the merged learning file...
The 'old' learning file now looks like this (which is much closer to the new learning scan but still 3 UNDEF):

[+] Spawn point count: 2160
[+] Type: 1x15, Count: 1938, Percentage: 89.72%
[+] Type: 1x30, Count: 128, Percentage: 5.93%
[+] Type: 1x45, Count: 13, Percentage: 0.6%
[+] Type: 1x60, Count: 1, Percentage: 0.05%
[+] Type: 2x15, Count: 77, Percentage: 3.56%
[+] Type: 1x60h2, Count: 0, Percentage: 0.0%
[+] Type: 1x60h3, Count: 0, Percentage: 0.0%
[+] Type: 1x60h23, Count: 0, Percentage: 0.0%
[+] Type: UNDEF, Count: 3, Percentage: 0.14%

Still a few spawns of differing types not matching up...
<S>Where do I change the learning time requirement and i'll put it back to 3 hours see what happens?</s>
That's just not how it works is it lol, you can see the type at scan - oh well.

**Comment by seikur0** [comment]
You don't need more than 1 hour. Well my offer stands, if you want, you can give me the locations of the 3 points and I'll try my luck.

**Comment by FrozenSocket** [comment]
Merging the fixed old and the new now gives.... DRUM ROLL !!!

[+] Spawn point count: 2194
[+] Type: 1x15, Count: 1972, Percentage: 89.88%
[+] Type: 1x30, Count: 131, Percentage: 5.97%
[+] Type: 1x45, Count: 13, Percentage: 0.59%
[+] Type: 1x60, Count: 1, Percentage: 0.05%
[+] Type: 2x15, Count: 77, Percentage: 3.51%
[+] Type: 1x60h2, Count: 0, Percentage: 0.0%
[+] Type: 1x60h3, Count: 0, Percentage: 0.0%
[+] Type: 1x60h23, Count: 0, Percentage: 0.0%
[+] Type: UNDEF, Count: 0, Percentage: 0.0%

So maybe the slight diff in spawn numbers is a connection/softban issue etc as you've said.

**Comment by seikur0** [comment]
Uhm congrats :D
