### ISSUE TITLE
Specify Learning File by Filename Rather Than Coordinates

### ISSUE THREAD

**Issue by darkforcesjedi** [seikur0/PGO-mapscan-opt#197]
It would be great to be able to specify a learning file by name instead of coordinates to make them easier to distinguish. If the file doesn't exist it could just fail and exit. If both a file and coordinates are present, it would load the file if it exists, and if not, perform the learning phase and then write the results to the given file name.

Something like this as an alternative to specifying coordinates:

```
    {
      "id": 0,
      "type": "ptc",
      "username": "xxxxxxx",
      "password": "xxxxxxx",
      "proxy": "http://xxxxxxx:3000",
      "coordinates":
          {
              "data_file":"downtown.json"
          }
    }
```

It looks like a minor change to me, but as you've seen already I don't know any python and I might break something if I do it myself.

**Comment by seikur0** [comment]
Seems good, I'll do something like that.

**Comment by seikur0** [comment]
That's in the new update. Closed.
