### ISSUE TITLE
Sunos5

### ISSUE THREAD

**Issue by furier** [seikur0/PGO-mapscan-opt#198]
Hi

I am running SmartOS which is a hypervisor OS were I am running several zones (virtual containers like docker). I created one yesterday and did everything like described but then when I tried to start it up it complained about the OS not being supported for the libencrypt library. I was wondering if you have any idea what library I might incorporate to make this work. Ill do the code changes my self and maybe make a pull request later. Just wondering if you can point me in the right direction. :)

Regards

**Comment by seikur0** [comment]
I added a hint on how to do that in the readme, basically you compile that file yourself:

```
brew install wget

wget http://pgoapi.com/pgoencrypt.tar.gz && tar -xf pgoencrypt.tar.gz && cd pgoencrypt/src/ && make && mv libencrypt.so ../../encrypt.so
```

I'm not sure if you can do it exactly like that on your OS, but this hopefully gives you an idea about what to do.

**Comment by furier** [comment]
haha that worked like a charm! just needed to add an else if statement to you `main0.py` file telling the code to use the newly compiled file when the OS is `sunos5`. Thanks! :D

**Comment by seikur0** [comment]
If you want, you can make a pull request for this, so you don't have to do it again after each update :)

**Comment by furier** [comment]
Iv made a pull request! :) #207
