### ISSUE TITLE
Key Error: "id" please assist a newbie

### ISSUE THREAD

**Issue by Vikingjojo** [seikur0/PGO-mapscan-opt#199]
Hi I believe I have set my settings file up correctly. However upon running the program I receive the error.

Traceback (most recent call last):
  File "C:/POKEMAP/PGO-mapscan-opt-master/main0.py", line 1584, in <module>
    main()
  File "C:/POKEMAP/PGO-mapscan-opt-master/main0.py", line 1454, in main
    accounts = do_settings()
  File "C:/POKEMAP/PGO-mapscan-opt-master/main0.py", line 321, in do_settings
    if allsettings['profiles'][i]['id'] == wID:
KeyError: 'id'

I have tried worker id's of 0 and 1 with no sucess. Any help would be very appreciated

**Comment by FrozenSocket** [comment]
Update/pull from the repo and make a new settings file I think would be the best start - There's a few new variables been added recently to the example settings file you could be missing.

As for the profile id numbers leave them all 0 as in the example until you have it working and want more control.

EDIT: Check your settings file for commas too, it's easy to have one to many or one missing when your c&ping many profiles.

**Comment by seikur0** [comment]
It's not commas, otherwise the error would be different. You just don't have the id entry for at least one of your workers

**Comment by Vikingjojo** [comment]
Thanks for the quick replys and assistance guys.
Yeah it turns out in my sleep deprivation I made the mistake of having a letter O in one of the id's not a Zero...
I also had random errors because I was attempting to run the program on a drive without adequate permissions. 

After coming back to it fresh yesterday I was able to get it  running and set up telegram notifications . Overall it was not too painful considering I have never installed python before or even ran any scripts in over a decade lol

Thanks for the great work Seikur0 the algorithm is amazing compared to the original "dumb" desktop map I had running. 

95% or so of the spawns are the 15min/h type with unfortunately only 4 30min spawns and I think a few 15m twice an hour.

Slightly off topic but very interesting.
 I have it scanning the local semi parkland / suburban area that has a river through the middle but also contains what I believe to be a meadow biome because of Clefairy spawns and lack of jiggilypuffs and Koffings.
It has always had good spawns (great ingress xm compared to most other parts of Townsville - North Australia) and regular dratini and occasional dragonair spawns along the river footpath, but  I really seemed to believe that the quality of spawns increased after we had a local apparently Niantic  sponsored event in our Town that coincided with the mass increase in regional pokemon spawns.

What are your thoughts about the idea of change of spawn quality around that time?

**Comment by seikur0** [comment]
You're welcome.

Visiting Niantic representative be like: "Where are my bitches? Rare pokemon for everyone! Gordon, call the central, I can't find shit here, tell them to quadruple pokemon spawns."

I don't know, hard to tell without data. How big of an event are we talking about? Spawn point activity is thought to be caused by google service usage, maybe it went over a certain range and triggered a spawn point increase or something.

**Comment by Vikingjojo** [comment]
The event was tiny, maybe 500 players more than the usual amounts. It's a small city but it's had a relatively  strong Ingress following. Yeah, pretty much. Kangaskhans that originally spawned like once an hour along the seafront esplanade suddenly starting popping up every 100m.  Afterwards they slowed down to at least one always up every km^2. 

Oh I didn't mean to imply the event had a effect on spawns other than temporarily, however Kangaskhans and especially pincers were now appearing regularly back at my local stomping ground so at least one obvious change was made. However now I semi regularly encounter evolved Eevees when originally I saw only one vaporeon in the first month of hours a day playing and scanning.
Dragonites now also spawn at least once a day, when I previously should have spotted at least one once in the first month as at the time a pokemon go map was being hosted at the local University and I was using my own desktop map in addition.
