### ISSUE TITLE
"ValueError" executing main0.py

### ISSUE THREAD

**Issue by yacx21** [seikur0/PGO-mapscan-opt#2]
Hi, first thank you for this improved algorythm really a good idea (others are slow and forced us to scan rather small areas).

So, when executing : 
python main0.py -id 0 -r 20 -t 600

It returns the following message : 

Traceback (most recent call last):
  File "main0.py", line 541, in <module>
    main()
  File "main0.py", line 431, in main
    pokemons = json.load(open('res/'+LANGUAGE+'.json'))
  File "C:\Python27\lib\json__init__.py", line 291, in load
    **kw)
  File "C:\Python27\lib\json__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\lib\json\decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting , delimiter: line 4 column 1 (char 18)

Since I've not any knowledge in python, I don't really understand this message, I've tried to go to the "C:\Python27\lib\json\decoder.py" file or in main0.py at line 4, but it doesn't seems to have any missing "," there.

Any idea where this could comes from?

I've used other map without trouble btw.

**Comment by yacx21** [comment]
My bad, seems like I dowloaded it right before you update json english file with the missing comas. Works perfectly npw, ty for the great job!

**Comment by garyandtaz321** [comment]
Same issue, seems when you change the langauge back to german only outputs these errors
line 541, in <module> main()
also f.close UnboundLocalError local varible f referenced before assignment
