### ISSUE TITLE
ptc login error in step 4: list index out of range

### ISSUE THREAD

**Issue by UmbaSimpy** [seikur0/PGO-mapscan-opt#202]
I have no idea but i'm getting this error everytime i try to launch main0,py
I have all the newest file and still get this.
Even my old folder that was working flawlessly stopped working for the same reason, even if i did not change a single thing
I think that some of my accounts are banned maybe but i don't know which one, and don't see any log file for it
How do i fix it?

**Comment by UmbaSimpy** [comment]
i tracked down one account that was giving this error and removed it
Now it seem it's working
Is it intended to behave like this if one account goes down?

**Comment by claimer21** [comment]
How did you track down that account that was giving the error? I'm using 100+ accounts and finding it really hard to track down the errors.

**Comment by UmbaSimpy** [comment]
I mostly got lucky
Started trying them in different groups
I have around 80 account
Just split them in different times
Eventually you will find it

**Comment by seikur0** [comment]
It does show you the zero based account number in the error bracket, if I'm not mistaken. And it's no ban, but rather a wrong name/password or missing email verification.

**Comment by atticusm** [comment]
I can confirm. Came here looking into the error and figured it was due to banned accounts. I used the following repo to find them and remove them. 

https://github.com/a-moss/PoGoAccountCheck

**Comment by seikur0** [comment]
This error can mean many things, wrong username/wrong password/email verification missing and yeah also account deleted(as in not existent). That tool you posted assumes it as account deleted. Instead it may be worth checking out, if you spelled the name/pw wrong or don't have the email verified yet.
