### ISSUE TITLE
Support for alternate web servers

### ISSUE THREAD

**Issue by darkforcesjedi** [seikur0/PGO-mapscan-opt#205]
I brought this up before. Take a look at my fork under webmod branch. I did a few things that might help address this, but I didn't make any of the necessary changes to the python code to support it. If you send me your contact info I can send you a link to my server running the mod. I don't want to do a pull request because it is incomplete and I can't implement the changes on the python side.

https://github.com/darkforcesjedi/PGO-mapscan-opt/tree/webmod
1. Created a settings file manually
2. Changed index.html to load the settings through javascript
3. Changed the index.html and static js code to swap profiles through the web interface instead of virtual web sites dynmically generated by pokesite.py
4. Added styles to the different lines of the marker labels to make them easily customizable.
5. Added a _getdata.php file to duplicate the "_getdata" function of pokesite.
6. I also uploaded my icon set since someone asked me for them at one point.

Todo (requires modification to the python code and I don't know any python):
1. Dynamically generate websettings.json
2. pokesite needs to be modified to serve websettings.json. Need to rename _getdata to _getdata.php. Serve index.html as a static file.
3. The pokemon filter should be written to the database in a separate table so it can be implemented by _getdata.php. Loading this setting from the JSON file every time the site loads is unnecessarily expensive on the server side.

**Comment by darkforcesjedi** [comment]
I also tested on desktop and mobile versions of Firefox and Chrome browsers and didn't have trouble with either.

**Comment by seikur0** [comment]
I'm currently working on something, but when I'm finished with that, I'll take a look at this too.

**Comment by darkforcesjedi** [comment]
Thanks.

I wish I were more experienced so I could contribute more. I love your project.

**Comment by seikur0** [comment]
I wish so too haha, but nevertheless I'm happy that you love and support my project :)

**Comment by seikur0** [comment]
I guess I can close that now :D
