### ISSUE TITLE
What is the range's metric unit

### ISSUE THREAD

**Issue by furier** [seikur0/PGO-mapscan-opt#209]
the default range is 30 in the configurations, I got 5 PTC accs and it takes for ever to even finish the initial scan. is it a diameter of 30km or 3000m or what? I dont want a high amount of accounts to minimize the risk of getting my IP banned...

**Comment by FrozenSocket** [comment]
30 circles of hexes
Range 1 is 1 hex ie the centre (a hex is about 70m wide)
Range 2 is 7 hexes ie the centre 1 + 6 hexes surrounding it totalling 7
Range 3 is 19 hexes 1 centre + 6 first circle +12 second circle

You can see it grows quickly, I'd suggest you drop the range to 5 and see if that completes within the 600sec threshold - If it does then increase the range with what you think you can get away with and try again (or get more accounts).

**Comment by furier** [comment]
Thank you @FrozenSocket, that was really helpfull! :)
