### ISSUE TITLE
mehrere ID´s auf einmal laden

### ISSUE THREAD

**Issue by mancmanGER** [seikur0/PGO-mapscan-opt#21]
Hallo seikur0,

wie kann ich in der Map mehrer ID´ßs auf einmal anzeigen lassen.

Wenn ich mit python main0.py starte wird mir immer nur die ID0 Koordinaten mit Leben befüllt.

Habe:
 "unique_coordinates": true,
  "centralscan": false,
"load_ids": [0,1],

Ich bekomme nur Inhalt für ID1 wenn ich python main0.py -ID 1 starte.

Oder geht es nicht die Map mit 2 Koordinaten zu befüllen?

**Comment by seikur0** [comment]
Du musst schon auch python "main0.py -id 0" gleichzeitig am Laufen haben, ein Programm sammelt immer nur Daten für eine id.

**Comment by mancmanGER** [comment]
ah ok, da war der Denkfehler.

Danke

**Comment by shadowsyllvet** [comment]
I was wondering about this myself.
Assuming I got the gist of this correct from google translate.
But we need to run a separate instance of the program for each ID?

**Comment by mancmanGER** [comment]
So you need to have for each ID a separate account.
start each with his own main0.py -id ? and restart the 'python -m SimpleHTTPServer 8000' 

This is how it worked for me and of course reload the webpage by hitting F5
