### ISSUE TITLE
Request|Facebook Messenger integration

### ISSUE THREAD

**Issue by Dracon23** [seikur0/PGO-mapscan-opt#214]
Since there is telegram and pushbullet integration, is there a way of using facebook messenger for notification?

Or, if no, is there some form of API documentation so I could hack something together myself?

**Comment by seikur0** [comment]
I'll integrate web hooks for the next version.

**Comment by Coalado** [comment]
I'm looking forword to this feature. I can stop to use my own  txt-reader-push-to-web tool then.

**Comment by Dracon23** [comment]
I'm currently using a somewhat hacked together integration of telegram,tasker and autonotification to transport infos cross-network, happy to stop that then

**Comment by furier** [comment]
As pushbullet doesn't work on iOS for notifications, facebook messenger or similar would be awesome! :P

**Comment by Coalado** [comment]
Pushbullet should work on iOS as well. Works fine in my own implementation.
However, as far as I know, there is no API that allows to send FB messages.  You would have to Crawl through the website - which is certainly against the Facebook TOC

**Comment by furier** [comment]
@Coalado what version of iOS are you running the latest 9.3.5 doesn't give me any notifications and all notification settings have been turned on, also the app has been reinstalled and phone rebooted multiple times, no difference... However if I open the app I can see all messages, that is no problem I just dont get any notification about it, so it kind of defeats the purpose when you have to sit and watch the application in order to stay updated on spawns...

**Comment by seikur0** [comment]
> You would have to Crawl through the website - which is certainly against the Facebook TOC

And we'd certainly never do anything against the TOC of companies, would we :P Btw, when they're sending the emails about new messages, you can replay to it via email to write in that chat. Depending on how long these links are valid, you can probably integrate Facebook notifications by sending emails.

@furier Why do you want to use Pushbullet instead of Telegram? :)

**Comment by furier** [comment]
Because I don't want to go through the hassle of setting up a bot blabla...
Seems like so much trouble. 😆
ons. 21. sep. 2016 kl. 09.46 skrev seikur0 notifications@github.com:

**Comment by seikur0** [comment]
It's soooo easy, like 10 clicks or something [guide](https://github.com/kvangent/PokeAlarm/wiki/Telegram#how-to-get-a-telegram-api-key)

**Comment by furier** [comment]
Thanks! I'll give it a try!

Btw on the matter of the issue at hand, I have no idea why you would need
to crawl facebook... What you would need to do is use an API to send a chat
message to a person, the messanger app would take care of the rest. However
I don't know if facebook exposes such an API... And you would certainly
either need to log on as a user or be given an API key for a bot to send
the message.
ons. 21. sep. 2016 kl. 10.09 skrev seikur0 notifications@github.com:

**Comment by seikur0** [comment]
You can answer to chats via email, so that could be used for it. But in the future I'll focus on Telegram only and let the other things be handled by the PokeAlarm guys :P

**Comment by furier** [comment]
Isnt Telegram part of PokeAlarm?

ons. 21. sep. 2016 kl. 10.24 skrev seikur0 notifications@github.com:

**Comment by seikur0** [comment]
It is, but with PokeAlarm you have another thing to set up and learn. And while they are willing to include the additional info like "15m later back for 15m.", they won't make it standard so you have to set it up and change some specific settings to enable that, which is kind of roundabout if you ask me. See [this](https://github.com/kvangent/PokeAlarm/pull/214) Also in my tests yesterday I noticed, that it can't handle too many requests at once (I wanted notifications for all pokemon :P ), I'm not sure if it's a Telegram throttling issue or an issue on their side. So in general I want to have an independent and easy to use notification thing inside my tool and Telegram is good for that.

**Comment by furier** [comment]
Sure thing.

Anyways I thought PokeAlarm was just a middle ware for communicating with the different platforms or is a service? 

What would be an obvious approach for PokeAlarm would be to expose different variables which you could just use in your own custom message. 

Say `TimeLeftInMinutes = 10`, `Location = ...` and `PokemonName = Snorlax`

Then you could compose your own message with `"{{PokemonName}} spawned @ {{Location}} and disappears in {{TimeLeftInMinutes}} minutes"`. Which would translate into `"Snorlax spawned @ ... and disappears in 10 minutes"`.

Dont you agree? :D

**Comment by seikur0** [comment]
They are doing exactly that, but you'll have too look into it a little bit do learn how to do that. ![teaser](https://cloud.githubusercontent.com/assets/20639004/18703790/c6892b6c-7fe7-11e6-93b1-d1ed5754c741.png) Each square (lvl 10 s2 cell) can be split into 2 areas and each area can be scanned with around 80 workers in one hour. So you can scan Berlin and some significant parts around it in 50 hours while only starting it once and letting it run. Will be released today :)

**Comment by furier** [comment]
Im failing to see how the map relates to the issue #214, or are we just having a nice conversation right now? :P Anyways that sounds awesome, but what is the purpose of it? just to discover all spawn points which you then afterwards can to iscans on with just a small amount of workers?

**Comment by seikur0** [comment]
I may have confused it with #182 The purpose is to gather large amounts of data for spawn point scanning. Wouldn't a world wide database of spawn points be very awesome? _._

**Comment by furier** [comment]
Yes that would be awesome @seikur0, however I think it would be needed to be updated regularly because it seems some spawn points are deleted and new ones are added every now and then. I think this is true as iv seen some maps miss some spawn points and it seem they are using iscans as well.

**Comment by seikur0** [comment]
I haven't seen any proof of that until now, but having a large spawn points database can also be useful to confirm or deny that.

**Comment by Coalado** [comment]
BTW. I just noticed that there ARE Facebook Bots. https://developers.facebook.com/blog/post/2016/04/12/bots-for-messenger/
However, I don't need them. Telegram is just fine.  
Webhooks would be cool anyway

**Comment by seikur0** [comment]
If you want Facebook support, contact the PokeAlarm guys, I won't be supporting any notifications other than Telegram and the ones by PokeAlarm from now on.
