### ISSUE TITLE
Bug - "SOCKS5 Proxy detected..." over and over

### ISSUE THREAD

**Issue by Dracon23** [seikur0/PGO-mapscan-opt#216]
[Paste](https://dpaste.de/vNOb)

I've been noticing since I raked in the latest dev, that I get a lot less spawns... Checked the log, see the [Paste] above.

I don't think that the IP was banned as I actually managed to get spawns, so the socks proxy sleeping is getting false positives.

**Comment by seikur0** [comment]
It's not getting false positives, if you see that, you got a banned IP. It's letting some few requests through. I noticed that when they started doing it, it's not a 100% ban, but more of a 95% ban.

**Comment by Dracon23** [comment]
It's rather strange though, as there shouldn't be anything going through as the failed requests share the proxy IP with the successful ones... But that's Niantic for you...

**Comment by seikur0** [comment]
It's been like this right from the beginning, when they started the ip blocking. Some requests just go through xD Yeah Niantic. (Do they have their own hashtag yet? I feel like Hashtag Niantic should become an expression for fails like that.)
