### ISSUE TITLE
Click in the map

### ISSUE THREAD

**Issue by set92** [seikur0/PGO-mapscan-opt#22]
I didnt know if this goes here or in pull requests, but I thought that it will be better to click in the google map to change the location, instead of changing it manually in the config file.

**Comment by seikur0** [comment]
You mean start with a zoomed out map and let it zoom in on click? I don't agree on that, especially in mobile devices, this would be very stressful and it's advantageous to start it zoomed in. You can change it for yourself though.

**Comment by set92** [comment]
No, to change the location clicking in the map, like https://pokevision.com/ where you can click anywhere and track pokemons in a new position.

**Comment by seikur0** [comment]
I'm deliberately not including that, my tool is meant and conceived to run stationary.
