### ISSUE TITLE
Pulling of IVs and Moves of Pokemon

### ISSUE THREAD

**Issue by toshioson** [seikur0/PGO-mapscan-opt#221]
Marvelous job of making this map and being able to identify the correct type of spawnpoint and report the right remaining time of pokemon with > 15 mins, thanks!!

Any plan that this map can perform an encounter and pull the IV and moves of particular pokemon and also being able to send the details via telegram? Thanks.

By the way, one noob question. What is the best way to upgrade my running copy of this map to the latest committs, is that I should run "git pull" inside the folder of the map? Will this overwrite any customized changes I have locally? Thanks.

**Comment by kaiyan910** [comment]
#121

**Comment by seikur0** [comment]
It'll never have IVs and moves, that's just not my style of doing things. And git pull is a very good way of updating it, additionally for bigger updates you should look at the new settings file format or other changes, the last one had a lot of them.

**Comment by toshioson** [comment]
@kaiyan910 I see, it has been asked before, thanks.

@seikur0 Thanks and understand your standpoint on IVs and moves. For the latest update with new settings and file format, so I'd better clone a complete new version and implement the changes/setting, right?

**Comment by seikur0** [comment]
Yes that's true, it takes a bit of time to get used to the new folder structure, but now the res folder isn't in such a chaotic state anymore :)
