### ISSUE TITLE
Map point in the middle of nowhere

### ISSUE THREAD

**Issue by aldder** [seikur0/PGO-mapscan-opt#223]
Hello, i wanna report this issue:

before last update i started the scanner and opening localhost automatically set as starting point the coordinates of the first account in usersettings.json

after the update i moved the json to learn_files directory and set learn_file option in settings, and now opening localhost, the map place me in the ocean xD (everything else works perfectly btw)

what did i wrong?? Thank you and sorry for my bad english.

**Comment by seikur0** [comment]
It's using the coordinates of the first profile for id 0 in usersettings.json So it seems that you still have it at the standard value of 0,0 which is in the middle of the ocean.

**Comment by aldder** [comment]
You're right!! Thank you :)
