### ISSUE TITLE
Errors in new version using webhooks

### ISSUE THREAD

**Issue by claimer21** [seikur0/PGO-mapscan-opt#227]
Hi, after running the main0.py server for a few hours with webhooks/pokealarm, I alway seem to get a different error after some time.  Here is the error I got this time.  

I had to post it on imgur.
http://imgur.com/a/K8vZH

**Comment by seikur0** [comment]
That's some debug stuff, that I "forgot" inside, well I left it there and din't think it'd be this room filling. Don't worry about it, it's nothing bad, just a normal ptc hickup. I should probably remove this.

**Comment by claimer21** [comment]
Alright, I'll try not to worry about it but the only problem is when this happens I have to restart my scanner or the alerts don't come through PokeAlarm.  And it happens frequently enough that I have to be near my computer every hour or two to restart it.  Looking forward to your fix!

**Comment by seikur0** [comment]
At least that error doesn't have anything to do with PokeAlarm and wouldn't affect it in any way. If there is still another thing, feel free to reopen this.
