### ISSUE TITLE
Can't access outside of LAN even with port forwarding

### ISSUE THREAD

**Issue by NHLGames** [seikur0/PGO-mapscan-opt#228]
This is the strangest thing.

I forwarded port 8000 on my router, and I can even access the map using http://external-ip:8000/.  But other people can't connect to it.

Is there some kind of host verification going on with Flask?  I saw in the code it should be running on 0.0.0.0, so I don't think it's an interface issue.

I'm running in a linux virtual machine with its own IP on the network.

(Btw, I've never had this issue with any other scanner, including PokemonGo-Map and pogom)

**Comment by NHLGames** [comment]
UPDATE: As a workaround, I used a repeater (http://www.gcd.org/sengoku/stone/) to rebroadcast the server to another IP on my network.  It seems it's not respecting the 0.0.0.0 setting?

**Comment by seikur0** [comment]
Normally the 0.0.0.0 is working and as public IP it's even not accessible from inside the network. What about the external IP, is it the correct one, or is there something special about it? If you can access it via the external IP from inside your network, check the connection with netstat for the actual IP.

**Comment by seikur0** [comment]
Does it still happen with the new server now? Try it please.

**Comment by NHLGames** [comment]
I think it was honestly an issue with my VM - since I'm using a VPN I think all ports become inaccessible.  Not sure why it was working for a while at the start.  Sorry about that!

**Comment by seikur0** [comment]
Okay then.
