### ISSUE TITLE
Scan interval doesn't work

### ISSUE THREAD

**Issue by nyxdis** [seikur0/PGO-mapscan-opt#229]
With a scan interval of 600 I get this:
[+] Scan Time: 436 s
[+] Sleeping for 0 seconds...

As far as I can see, this seems to be caused by the fact that the scan time is saved as milliseconds and the interval as seconds, so 436000 > 600 => no sleep.
This should be fixed by a division by 1000 on line 1472 (haven't tested):
                curT = max(scaninterval - curT, 0)
to
                curT = max(scaninterval - curT/1000, 0)
(or multiply scaninterval by 1000)

**Comment by seikur0** [comment]
That is very true, thanks.
