### ISSUE TITLE
Weird PTC related login issue

### ISSUE THREAD

**Issue by pauloyourdreams** [seikur0/PGO-mapscan-opt#230]
Near the beginning of the scan (usually around the catchup phase), I get this error message:

`cannot watch more than 1024 sockets`

It spits this line for a good minute or two, and then it stops. The scan goes normally as it should, for a long while.

At some point during the scan, it spits a pretty similar message again, but this time, it just **continuously**
gives this error:

`[241] Ptc login error in step 0: cannot watch more than 1024 sockets`
`Error happened before network request.`
`Retrying. . .`

I have no clue as what is the cause for this issue. It happens a quarter of the time I run scans, and restarting the scan some times fixes it.

**My current setup:**
100 workers being used out of the 300 I have inputted into the usersettings.json file.
7000m range.
300s scan interval.
Using this command line, `python main0.py` to prevent it from going into silent mode.

**Comment by seikur0** [comment]
Which os are you on? Are you using webhooks?

**Comment by pauloyourdreams** [comment]
I'm using Windows 10 Home. And yes, I was using this with web hooks, for the first time. I turned it off, just to see if the same bug occurs, and it does. (Just not as frequently as having it with web hooks.)

**Comment by seikur0** [comment]
That should be fixed now, if it's still an issue, reopen it :)
