### ISSUE TITLE
Missing Settings error?

### ISSUE THREAD

**Issue by FrozenSocket** [seikur0/PGO-mapscan-opt#231]
Traceback (most recent call last):
  File "main0.py", line 1813, in <module>
    main()
  File "main0.py", line 1747, in main
    accounts = do_settings()
  File "main0.py", line 314, in do_settings
    time_socks5_retry = allsettings['time_socks5_retry']
KeyError: 'time_socks5_retry'

**Comment by FrozenSocket** [comment]
updating my settings file to match new setting in the example file resolved this problem.

  "time_socks5_retry": 30,

Default param values you know you want to add them ^^!

**Comment by seikur0** [comment]
I prefer the compiler notifying you in a slightly cryptic but friendly manner, that your settings file is outdated :D
