### ISSUE TITLE
File missing?

### ISSUE THREAD

**Issue by FrozenSocket** [seikur0/PGO-mapscan-opt#232]
[+] Can't load location database file: [Errno 2] No such file or directory: 'D:\PGO-mapscan-opt/res/learning/learn_files/seikur0_circle__-lat/lon removed-__25__70.0.json'.
Traceback (most recent call last):
  File "main0.py", line 1813, in <module>
    main()
  File "main0.py", line 1775, in main
    set_locations()
  File "main0.py", line 982, in set_locations
    all_loc = get_plan_locations(scanplan)
  File "main0.py", line 911, in get_plan_locations
    LAT_C, LNG_C = locations[0]
IndexError: list index out of range

**Comment by seikur0** [comment]
Okay, so the thing is your circle with radius 25 m just doesn't contain any of the grid points, which have a distance of ~120 m between each other. It's not bad, that the file is missing. If you were trying to load an older learning file, put that into the learn_files folder and put its name into the settings of the corresponding profile, see the readme.

**Comment by FrozenSocket** [comment]
This doesn't feel like a step forward in easy of use. :(

added the extra setting to point to the learning file and moved it to the new folder to get another file not found error because I included the file extension in the config. Removed this and it appears to be running again.

**Comment by seikur0** [comment]
It is a step forward, but as with every step you have to motivate yourself first to take it and then check if the ground is stable. But once you've done that, you get to enjoy the new scenery :)
