### ISSUE TITLE
seikur0_spir plan not working. Number of locations incorrect

### ISSUE THREAD

**Issue by Pedromanuelsilva** [seikur0/PGO-mapscan-opt#234]
when subdividing my scan area into seikur0_spir plans it doesn't calculate the number of locations correctly.

when running:
`python main0.py -hx -r 6 -lat [LAT1] -lng [LNG1]`

it outputs `Distributing 127 locations to 4 threads.`

if i try to run a seikur0_spir plan it outputs `Distributing 18 locations to 4 threads.` 

According to darkforcesjedi formula from #182 , 

> The number of tiles in a grid with "L" layers is N=3L(L+1)+1.

that gives 127 for a 6 layers hexagon

My plan:

```
{
 "type": "seikur0_spir",
 "location": [LAT1,LNG1],
 "range": 6,
 "subplans": 7,
 "subplan_index": 1
}
```

**Comment by seikur0** [comment]
Damm you're right, it should be 19. That was an integer division issue, leading to it being rounded down. Now fixed :/ @c00ni see :P

**Comment by Pedromanuelsilva** [comment]
Issue still there.

it should be 127 or 128 locations for a range 6 hexagon,  not 18 or 19 locations

maybe a range issue? could it be assuming a wrong range like 6 meters instead of 6 layers?

**Comment by seikur0** [comment]
Hm no 19 is the correct number, since you use 7 subplans. 127/7 = 18,14, so the first 6 subplans scan 19 and the last one 13.

**Comment by Pedromanuelsilva** [comment]
oh my mistake. i thought i had to subdivide it myself and the range was the scan range for the subplan part

**Comment by seikur0** [comment]
Thank you so much for that mistake! It gave me the chance to spot and correct mine.

**Comment by c00ni** [comment]
Damn you integers!
