### ISSUE TITLE
email notifications

### ISSUE THREAD

**Issue by darkforcesjedi** [seikur0/PGO-mapscan-opt#235]
What are your thoughts on email notifications. I have a daemon running on my server that polls the database and sends emails using sendmail on Linux. It has worked pretty well for me.

![tmp_23787-screenshot_2016-09-22-19-23-05-1541077844](https://cloud.githubusercontent.com/assets/20672693/18769292/0b602034-80fa-11e6-9de2-8e090e49736d.jpg)

**Comment by seikur0** [comment]
Sry, I'd like to focus on Telegram notifications, I'll even remove pushbullet in one of the next versions, because PokeAlarm has that too. But you can probably make a request for email notifications at the PokeAlarm github :)

**Comment by darkforcesjedi** [comment]
I was working on a subsystem with per-user customizable notifications, but it turns out email notifications are bad. After a while the mail providers mark them as spam because they are too frequent.

**Comment by seikur0** [comment]
:D
