### ISSUE TITLE
"Database is locked" bug?

### ISSUE THREAD

**Issue by pauloyourdreams** [seikur0/PGO-mapscan-opt#236]
In the beginning of running `python main0.py -v`, during the login process, I get this bug that pretty much halts the start of the scan:

`[96] New API endpoint: https://pgorelease.nianticlabs.com/plfe/536/rpc`
`[191] New API endpoint: https://pgorelease.nianticlabs.com/plfe/296/rpc`
`Exception in thread Thread-181:`
`Traceback (most recent call last):`
`File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner`
`self.run()`
`File "main0.py", line 1512, in run`
`do_login(self.account)`
`File "main0.py", line 569, in do_login`
`set_api_endpoint(location, account)`
`File "main0.py", line 804, in set_api_endpoint`
`cur.execute("INSERT OR REPLACE INTO accounts VALUES(?,?,?,?,?,?,?)", [account['user'],`
`account['access_token'], account['access_expire_timestamp'], account['api_url'], account['auth_ticket']`
`['expire_timestamp_ms'], account['auth_ticket']['start'], account['auth_ticket']['end']])`
`OperationalError: database is locked`

`[240] New API endpoint: https://pgorelease.nianticlabs.com/plfe/327/rpc`
`[242] New API endpoint: https://pgorelease.nianticlabs.com/plfe/175/rpc`
`[241] New API endpoint: https://pgorelease.nianticlabs.com/plfe/450/rpc`

I didn't even know it was possible to get the database locked until now.

**Comment by darkforcesjedi** [comment]
Are you using any other tools to access the database? Are you running multiple instances of main0? I have a separate alert system I set up that reads off the database and it was getting that error. I just had to add "pragma busy_timeout=xxxx" to my query to wait for database access. I haven't tried the latest version but the threads may be colliding trying for simultaneous database access.

**Comment by pauloyourdreams** [comment]
I'm only using one instance of `python main0.py -v` with the webhook for PokeAlarm enabled.
And I don't know how to add that line in, cause I'm not **that** knowledgeable with programming language.

**Comment by seikur0** [comment]
Are you using the newest version? Because I changed the pragma to "PRAGMA journal_mode = WAL" (look for that in the main0.py). If it still does that I'd be suprised :)

**Comment by darkforcesjedi** [comment]
Yes I am using an old version because I don't want to take it offline unless I need to. Usually I get lots of complaints when it goes down.

**Comment by seikur0** [comment]
Complaints? Wtf, they can be happy, they get anything from you at all. Unless you charge money for it or something? :P I meant @pauloyourdreams though, since he has the problems with it.

**Comment by pauloyourdreams** [comment]
@seikur0 Yeah, I'm still getting the "database is locked" bug on the first run of the scan. Once I close that and restart for second scan, the second scan is fine and doesn't have that bug. (I'm still using the latest version of your map.)

**Comment by Coalado** [comment]
Same problem. latest Version:
`Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "main0.py", line 1514, in run
    do_login(self.account)
  File "main0.py", line 569, in do_login
    set_api_endpoint(location, account)
  File "main0.py", line 806, in set_api_endpoint
    cur.execute("INSERT OR REPLACE INTO accounts VALUES(?,?,?,?,?,?,?)", [account['user'], account['access_token'], account['access_expire_timestamp'], account['api_url'], account['auth_ticket']['expire_timestamp_ms'], account['auth_ticket']['start'], account['auth_ticket']['end']])
OperationalError: database is locked`

**Comment by seikur0** [comment]
Okay, try it now.

**Comment by Coalado** [comment]
It started to scan. I will give feedback if the error comes back.
thanks for the fix. I will send you the resulting learning files
