### ISSUE TITLE
Hex pattern for scan generated incorrectly

### ISSUE THREAD

**Issue by lyssy2000** [seikur0/PGO-mapscan-opt#240]
If using hex pattern for scan (-hx parameter used), scan points are overlapping - their count is correct (e.g. 37 for range=3), but area covered is about 1/3 of expected with such range.

Digging through code showed that point calculation in function "neighbor_circle" in maplib.py is incorrect, at least for shift=false - it generates only 3 out of 6 possible point coordinates, leaving half of circle unused. Don't know if this is expected behaviour, maybe used in some other scan pattern, but it does not work correctly for hex pattern. It seems that for shift=true all 6 points are generated correctly. 

Changing xvals and yvals tables for not-shifted version from original:

yvals = [-2, -1, 1,-2, -1, 1]
xvals = [0, 1, 1, 0, 1, 1] 

to:

yvals = [-2, -1, 1, 2, 1, -1]
xvals = [0, 1, 1, 0, -1, -1]

seems to correct the issue.

**Comment by Pedromanuelsilva** [comment]
I can  confirm the issue. Doing a hex scan  returns "duplicate" pokémon on some scanpoints while missing others ( compared to a pokémon go map ).

**Comment by seikur0** [comment]
That's true and now fixed, thanks. I recently changed that, had a function do the 3 last values before, because they're just repetitions of the first 3 ones and then put it back but not correctly.
