### ISSUE TITLE
Spawns?.txt logs

### ISSUE THREAD

**Issue by darkforcesjedi** [seikur0/PGO-mapscan-opt#245]
I updated to the latest version yesterday and these log files are no longer being written. Is there a way to re-enable that?

**Comment by seikur0** [comment]
I'm pretty sure they're still being written, look in your res/logs folder. Btw you should update again today, yesterday some map stuff was broken.

**Comment by darkforcesjedi** [comment]
Ok they moved. I was looking at the code and saw it there. 😲
