### ISSUE TITLE
Telebot: UnicodeDecodeError on "ignored pokemon" message

### ISSUE THREAD

**Issue by nyxdis** [seikur0/PGO-mapscan-opt#249]
I currently get this when trying to get the list of ignored pokemons:

```
Traceback (most recent call last):
  File "telebot.py", line 610, in <module>
    bot.sendMessage(chat_id, message.format(arg=argdic), parse_mode="html")
  File "/home/christoph/virtualenvs/pgo-mapscan/local/lib/python2.7/site-packages/telepot/__init__.py", line 409, in sendMessage
    return self._api_request('sendMessage', _rectify(p))
  File "/home/christoph/virtualenvs/pgo-mapscan/local/lib/python2.7/site-packages/telepot/__init__.py", line 398, in _api_request
    return api.request((self._token, method, params, files), **kwargs)
  File "/home/christoph/virtualenvs/pgo-mapscan/local/lib/python2.7/site-packages/telepot/api.py", line 130, in request
    r = fn(*args, **kwargs)  # `fn` must be thread-safe
  File "/home/christoph/virtualenvs/pgo-mapscan/local/lib/python2.7/site-packages/urllib3/request.py", line 148, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/home/christoph/virtualenvs/pgo-mapscan/local/lib/python2.7/site-packages/urllib3/poolmanager.py", line 244, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/home/christoph/virtualenvs/pgo-mapscan/local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 594, in urlopen
    chunked=chunked)
  File "/home/christoph/virtualenvs/pgo-mapscan/local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 361, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python2.7/httplib.py", line 1039, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1073, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1035, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 877, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 165: ordinal not in range(128)
```

Other commands work fine.

**Comment by nyxdis** [comment]
After updating the dependencies, I no longer get the exception with stack trace, but only this:
[20:03:57] [t] Text received: @xxx (xxx): '? Ignored pokemon'
[20:03:57] [!] An unkown error happened while sending message

Edit: the exception still happens, looks like it's not directly related to "ignored pokemon" though.

**Comment by nyxdis** [comment]
Looks like the error is caused by a location that includes ß (0xc3 0x9f), which obviously cannot be converted to ASCII.
Not sure why "ignored pokemon" isn't working currently.

**Comment by seikur0** [comment]
The ascii part is fixed now, do you have ignored pokemon in the settings as [1,2,3,4] and so on? "1,2,3,4" would be wrong.

**Comment by nyxdis** [comment]
Fixed, indeed.
My telebot.json contains this:
        "ignored_by_default" : [1,2,4,5,7,8,10,11,13,14,16,17,18,19,20,21,22,23,24,25,27,29,30,32,33,35,37,39,41,42,43,44,46,48,50,52,54,56,58,60,61,63,64,66,67,69,70,72,73,74,75,77,79,81,83,84,86,88,90,92,93,96,98,99,100,102,104,109,111,115,116,118,119,120,122,128,129,133,138,140,147],

**Comment by seikur0** [comment]
Okay, that's good. So is that ignored pokemon error still happening?

**Comment by nyxdis** [comment]
Yup, sorry wasn't clear. Only the ß bug is fixed, ignored pokemon still doesn't work.
What's strange is that it worked earlier today, it just stopped working.

**Comment by seikur0** [comment]
I'm not sure, since it's really confusing for me, how @nodex0 put in the different encodings. Like utf-8, ascii and byte encodings seem totally mixed and it's even amazing that it's working at all imho.

**Comment by nyxdis** [comment]
Yeah, it's definitely the encoding. I've changed the "except" to show the exception message:

> [20:48:52] [!] An unkown error happened while sending message 'ascii' codec can't decode byte 0xe2 in position 159: ordinal not in range(128)

This is the offending line:

> [20:48:52] Here you have a list of your pokemon notifications. The pokemon marked with  will be notified and the pokemon with  will be ignored. Press to toggle.

**Comment by nodex0** [comment]
Does your pokemon name list include any non-ascii character, @cmende ? It may be that the pokemon list is not converted to byte string when loaded and JSON.load uses unicode objects. If thats the problem pokemon names just have to be encoded.

The bot tries to use byte strings for most if not all things, except the comparing of the message command, that is done in ascii. I tried using unicode objects before but it was an encoding HELL @seikur0

**Comment by nyxdis** [comment]
As far as I can tell, the problem character (0xe2) is written here:

> ```
>     formatted_pokemon_buttons.insert(0, ["♻️ " + messages["restore_default_ignored"], "☑️ " + messages["mark_all"], "◼️ " + messages["unmark_all"]])
> ```

That first emoji before "restore_default_ignored" seems to start with 0xe2. I have no idea when or why it stopped working though.

**Comment by seikur0** [comment]
Why would you use ascii though, ascii can't encode all these emojis, take for instance the line `messages_ascii[m] = messages[m].decode("utf-8").encode('ascii', 'replace')` that alone destroys all your emoticons in all your messages.

See the question mark in that message: `[20:03:57] [t] Text received: @xxx (xxx): '? Ignored pokemon'` That's an unicode character as well, that can't be depicted in ascii.

**Comment by nodex0** [comment]
Because that is only used for comparing, and the messages are supposed to be identifiable by themselves, the emoji is attached later as eye candy, it doesn't matter that there's a ???. For everything else I think byte strings are used @seikur0  :c

**Comment by seikur0** [comment]
I'm not meaning to attack you or something like that, I just think it's confusing. There shouldn't be any reason against just using utf-8 all the way.

**Comment by nodex0** [comment]
In theory there shouldn't be, but in practice it caused loads and loads of errors trying to use unicode with python 2.7 ( https://github.com/nickoala/telepot/issues/164 for example ). I decided to use ascii to compare and try to use bytestrings elsewhere, you're free to change it to something simpler xP

**Comment by seikur0** [comment]
The only thing you have to do is use a str type bot token (I found that out the hard way just now), I changed a lot of it now, so it only uses unicode in most places. The file log doesn't work, I was too lazy for that.

**Comment by nyxdis** [comment]
This seems to have shifted the problem. Ignored pokemon works fine now, but it looks like notifications with non-ASCII chars are broken again. I now get this exception:

> UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 20: ordinal not in range(128)

on line 614.

Edit: Your last commit also broke the geolocator on main0.py, all messages are sent without address now.
