### ISSUE TITLE
Issues with "encoding fixes"

### ISSUE THREAD

**Issue by NHLGames** [seikur0/PGO-mapscan-opt#252]
With the latest encoding fixes commit, my telebot crashes almost immediately after sending a few messages:

```
Traceback (most recent call last):
  File "telebot.py", line 614, in <module>
    bot.sendMessage(chat_id, message.format(arg=argdic), parse_mode="html")
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe0' in position 2: ordinal not in range(128)
```

I reverted to the old PR version for now.

**Comment by nyxdis** [comment]
I've fixed this by porting telebot.py to python3. Is there any reason why main0 and telebot still use python2?

**Comment by seikur0** [comment]
Please tell me, python 3 has better utf-8 support. God, in the last days I realized that python 2.7 hates unicode in every imaginable way.

**Comment by ftuttle5** [comment]
How do I port it to python 3? Can someone give me the steps for getting the Telegram notifications working again?

**Comment by nyxdis** [comment]
Oh, python3 actually loves unicode: https://docs.python.org/3.0/whatsnew/3.0.html#text-vs-data-instead-of-unicode-vs-8-bit
The 2to3 tool did most of the work for telebot.py. Haven't tried main0.py or any of the other files yet though. But just porting to 3 immediately fixed the UnicodeEncodeError in telebot.py.

**Comment by seikur0** [comment]
"This value-specific behavior has caused numerous sad faces over the years."

I can tell by my face while implementing these many details needed to make it work with unicode.

**Comment by seikur0** [comment]
Should be fixed now.
