### ISSUE TITLE
(question) starting all over again

### ISSUE THREAD

**Issue by dikkedeur** [seikur0/PGO-mapscan-opt#253]
I want to wipe all content and start all over again.. since rumours goes that the recent update has also made more spawns.
now the question is how to do that.
i have learning files in the /res/learning folder..
do i need to delete them???

what about the username.json config.. there is a setting learning file where you put in: 52.942224672_4.75690841675_27_70.0 for example. ( thats my learning file )
what do i need to put there in? how to start a new learning??

**Comment by seikur0** [comment]
You remove the files from the learning folder, maybe put them to a subfolder, then you can compare it, if you're interested. The name doesn't really matter, it checks, if that exists in the learning folder and if not starts a new learning phase with the parameters. If you start it in plan mode it doesn't matter anyway.

**Comment by dikkedeur** [comment]
well moved them to a backup folder, problem is in the username.json file it still says 52.942224672_4.75690841675_27_70.0
so now i get offcourse  the error that it cant find it.

[+] Can't load location database file: [Errno 2] No such file or directory: '/home/scan/PGO-mapscan-opt/res/learning/learn_files/52.942224672_4.75690841675_27_70.0.json'.
[+] Can't load location database file: [Errno 2] No such file or directory: '/home/scan/PGO-mapscan-opt/res/learning/learn_files/seikur0_circle__52.942224672_4.75690841675__27__70.0.json'.
Traceback (most recent call last):
  File "main0.py", line 1822, in <module>
    main()
  File "main0.py", line 1784, in main
    set_locations()
  File "main0.py", line 990, in set_locations
    all_loc = get_plan_locations(scanplan)
  File "main0.py", line 919, in get_plan_locations
    LAT_C, LNG_C = locations[0]
IndexError: list index out of range

in my username.json i have set the radius and everything since i only scan my own town.
so i just want to make a new database and such.

it doesnt start a new learning phase.

**Comment by seikur0** [comment]
It's okay that it can't find them, the problem here is, that you try to scan a circle with a radius of 27 meters, and that doesn't contain any grid points in this case.

**Comment by dikkedeur** [comment]
well it also says i have no plans.. so may that be the problem??
it looks for me now more difficult then without the learning files .
How to start now a new fresh scan that does first learning then goes into iscan?

**Comment by seikur0** [comment]
You don't need plans, unless you start it with -p, conversely if you don't have plans, don't start it with -p! Just start it with python main0.py and put your range setting to the distance you want, rather than the value of 27, which would be good for hex layers, but not as a real meter radius. I mean, if you like the hex shape, you can still use it with -hx, then 27 would be good.

**Comment by dikkedeur** [comment]
python main0.py gives error, since in the username.json is still learning_file: the learningfile name.
so i removed that.
started it up.
same result.

[+] Can't load location database file: [Errno 2] No such file or directory: '/home/scan/PGO-mapscan-opt/res/learning/learn_files/seikur0_circle__52.942224672_4.75690841675__27__70.0.json'.
Traceback (most recent call last):
  File "main0.py", line 1822, in <module>
    main()
  File "main0.py", line 1784, in main
    set_locations()
  File "main0.py", line 990, in set_locations
    all_loc = get_plan_locations(scanplan)
  File "main0.py", line 919, in get_plan_locations
    LAT_C, LNG_C = locations[0]
IndexError: list index out of range

 "_comment": "Standard scan range, represented as layers around the center hexagon.",
  "range": 27,

changing it to 37, doesnt make any difference.
"learn_file": ""

**Comment by seikur0** [comment]
Yeah, listen to me please. The error has nothing to do with the learning file names, if they're not there, it just starts a learning phase. The problem is, that 27 and 37 meters as well are really small distances, two grid points have a distance of ~120 meters between each other. So just set that value of 27 to something like 3000m =3km.

**Comment by dikkedeur** [comment]
ahh, nice thanks, it works now, i wonder why i had it all the time on 27?? it did work, anyway, thanks

**Comment by seikur0** [comment]
You had 27, because that was your old hex range and you didn't update it :P You're welcome.
