### ISSUE TITLE
Too many webhooks

### ISSUE THREAD

**Issue by Coalado** [seikur0/PGO-mapscan-opt#254]
I'd like to use the webhooks to push pokemons to a central DB.
If you do an extra request for each pokemon, this results in way to many requests.
could you add a parameter "webhookInterval":10000 to wait 10 seconds and send all findings as an array?

**Comment by seikur0** [comment]
That's the bad part, now with PokeAlarm using it, everybody is like webhooks, webhooks!, WEBHOOK!, when they're totally the wrong thing to use even with PokeAlarm. An efficient thing to use would be a normal server-client connection instead, that you can then serve with just one thread. Are you sure, that you want webhooks?

**Comment by Coalado** [comment]
A socket solution would probably be a better approach, But I'm afraid I would be the only one using it. 
As long as you keep the logfile, I'm actually happy. 
Currently, I disable the log file backup function, open a stream to the logfile, and push changes directly to my MongoDB. 

I did some tests with the webhook feature, and noticed exactly what you said: inefficient. Especially for a large area with many pokemons.

**Comment by seikur0** [comment]
I plan on changing the Telegram Bot to a socket connection as well and then I'll persuade kvangent to integrate it, or I'll put it into a fork and start using that instead. But if you're fine with the log, should I close this right now?

**Comment by Coalado** [comment]
Can be closed
