### ISSUE TITLE
Telebot.py crash

### ISSUE THREAD

**Issue by PureMethod** [seikur0/PGO-mapscan-opt#257]
`[17:36:10] [+] Telegram bot for PGO-mapscan-opt started!
Traceback (most recent call last):
  File "telebot.py", line 614, in <module>
    bot.sendMessage(chat_id, message.format(arg=argdic), parse_mode="html")
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 29:
 ordinal not in range(128).`

I'm not sure but it might have something to do with the finnish languange having letters like äöå?

edit: sorry about not checking all open issues, might be the same as #252?

**Comment by NHLGames** [comment]
Yup same as #252 .

For now I reverted to the original version in the PR here: https://github.com/nodex0/PGO-mapscan-opt/blob/a56ce8e66321e98d61e1f6c0a1e7957fe9fa3e8f/telebot.py (called it telebot2.py so I can still pull from main branch properly)

**Comment by seikur0** [comment]
Yes, closed, since it's a duplicate.
