### ISSUE TITLE
Raw plans

### ISSUE THREAD

**Issue by darkforcesjedi** [seikur0/PGO-mapscan-opt#258]
Raw plans do not have a 'location' property but main0.py references that on line 860 and 894. Fix below:

860:
  id = 'raw__{}_{}__{}__{}'.format(plan['locations'][0],plan['locations'][1],plan['id'],Rsight)

894:
  location = plan['locations'][0]

Edit: It looks like you have fixed one of the lines but not the other in the latest version.

**Comment by darkforcesjedi** [comment]
Also the wiki for Plan mode contains some errors which make it hard to understand (I had to read the code to determine how to initiate scanning from a new plan).

I have edited the wiki for plan mode to describe how I think it works. My description may not be entirely accurate.

**Comment by seikur0** [comment]
True and fixed. And thanks for the additions to the wiki page.
