### ISSUE TITLE
Timer on pokemon

### ISSUE THREAD

**Issue by mirzaciri** [seikur0/PGO-mapscan-opt#26]
Looks like the time is static, it's not counting down at all. I need to refresh the site for it to work.

**Comment by seikur0** [comment]
It's counting down every 10 seconds.

**Comment by mirzaciri** [comment]
Any way to change this? And how can i added 2 accounts with 2 separate location, just the first location is scanned. i set "unique_coordinates": true, 

EDIT:
With AHAAAAAAA/PokemonGo-Map i could have 10 instances run with the same account, is it possible with this to?

**Comment by seikur0** [comment]
You can change this in the html, line 160, set 10000 to whatever time in ms you want.  Using just onoe account was possible before yesterday. But they just changed their network protocol so a single account can only do so many requests per second now.

To scan two places, you open two command windows and start the tool with different ids. And then you also change the load_ids setting in the setting file to the ids you want shown.

**Comment by shadowsyllvet** [comment]
nodejs http-server has a method to specify how long a page is cached or to disable caching completely.  I am using a 10 second cache and I notice that I get less instances of having no pokemon on the map after a refresh.
I am unsure what the python equivalent is.

While on the subject of using multiple ID's, would it be possible to name the cmd windows after which ID they are using? Once the programs have been running for awhile, you can only scroll up so far to see. I can always put it in the .bat file I use to launch them I guess.

**Comment by seikur0** [comment]
I'm not sure about this, but would that mean increased network traffic, since clients need to download whatever was cached before again? Cmd window names, okay I'll look into it for the next update. But if it's not working for unix systems as well I probably won't add it.

**Comment by mirzaciri** [comment]
@shadowsyllvet when i run an instance, the username i use is displayed on top of the CMD window.

**Comment by shadowsyllvet** [comment]
@realbunny whenever I run a cmd prompt it defaults the title to the folder that the prompt is run from. It may be because I am running cmd as an admin. I'd have to change some registry settings to test that tho.

**Comment by mirzaciri** [comment]
@shadowsyllvet Do you run it from a batch script? Or manually? Try running without admin

**Comment by shadowsyllvet** [comment]
.bat usually, I occasionally start it myself but ether way has the same result. modified my registry to rum cmd as admin

**Comment by mirzaciri** [comment]
@shadowsyllvet I just tried it with .bat, with admin and without. I'm getting the same results. What OS version are you running?

**Comment by shadowsyllvet** [comment]
Windows 8.1, what are you using to start the program. I'm only using:

python main0.py -id 1

**Comment by mirzaciri** [comment]
W10,
But i think there's your problem, you don't have your username or password in the argument. You have that on your config file maybe?

Try this
python main0.py -lt ptc -u username -p password -id 1

**Comment by shadowsyllvet** [comment]
Just tried that getting the same result. I already have a workaround:

title User 1
python main0.py -id 1
