### ISSUE TITLE
[Question] New learning files

### ISSUE THREAD

**Issue by FrozenSocket** [seikur0/PGO-mapscan-opt#260]
I drop of the face of the earth for a few days, come back and spawn points have changed (?) and I can't work out how to create these new learning plans/files or whatever. Feeling lost :/

**Comment by seikur0** [comment]
Fear not, for we have a pretty good [wiki](https://github.com/seikur0/PGO-mapscan-opt/wiki) now.

**Comment by FrozenSocket** [comment]
a WIKI... what crazyness is this...

**Comment by FrozenSocket** [comment]
OK, My word so many options...
<s>So using the spawnview.py tool I selected 1 section which was sort of in the right place, saved it in 2 parts but I have 4 files created</s> (appears I clicked 2 sections hence 4 files), is there anyway to know which is the top part etc If I dont want to scan the bottom half of a sector.

For example if I split my s2 save in 4 parts is part 1 always top left, part 2 top right, part 3 bottom left & part 4 bottom right for example.

Is there a benefit to using the s2 zones over the circle/hex options? They would appear unworkable big in respect of scanning many km you don't care about?

**Comment by seikur0** [comment]
The parts are sorted by latitude, all points in part 1 will always be at a lower or equal latitude than the points in part 2. I thought with s2 cells, we had a chance to map the whole world, but now that they changed the spawn points just like that, I guess it's obsolete. I guess, I should change that plan tool to something better.

**Comment by FrozenSocket** [comment]
Looks like I'm having trouble with the spir plan, it appears to only be scanning about a 1/3 (most of the right side) of the area that the location/range previously covered.
It's not found anything on the left side of the area as yet and 3 scans have passed. (Will update)

EDIT: Looking at it, it might be scanning the s2 section instead of the hex spiral... hmmm.

**Comment by FrozenSocket** [comment]
Look at this example... Everything is to the east of the start point :/

[+] Finished: 12.0 %
[+](16) Pidgey visible for 519 seconds (969m NE from you)
[+](21) Spearow visible for 411 seconds (1133m NE from you)
[+](16) Pidgey visible for 769 seconds (1060m NE from you)
[+](13) Weedle visible for 806 seconds (1177m SE from you)
[+](10) Caterpie visible for 853 seconds (1175m SE from you)
[+](16) Pidgey visible for 584 seconds (1165m SE from you)
[+](122) Mr. Mime visible for 842 seconds (1141m SE from you)
[+](16) Pidgey visible for 505 seconds (1178m SE from you)
[+](16) Pidgey visible for 729 seconds (1097m SE from you)
[+] Finished: 14.0 %
[+](16) Pidgey visible for 668 seconds (1087m NE from you)
[+](19) Rattata visible for 801 seconds (1125m NE from you)
[+](16) Pidgey visible for 557 seconds (1165m NE from you)
[+](21) Spearow visible for 536 seconds (1267m NE from you)
[+](16) Pidgey visible for 694 seconds (1172m SE from you)
[+](96) Drowzee visible for 668 seconds (1149m SE from you)
[+](21) Spearow visible for 828 seconds (1106m SE from you)
[+] Finished: 16.0 %
[+](41) Zubat visible for 630 seconds (1213m SE from you)
[+](41) Zubat visible for 883 seconds (1172m SE from you)
[+](10) Caterpie visible for 833 seconds (1160m SE from you)
[+](133) Eevee visible for 799 seconds (1262m SE from you)
[+](13) Weedle visible for 901 seconds (1280m SE from you)
[+](13) Weedle visible for 637 seconds (1214m SE from you)
[+](16) Pidgey visible for 810 seconds (1179m E from you)
[+](19) Rattata visible for 745 seconds (1150m NE from you)
[+](16) Pidgey visible for 648 seconds (1241m NE from you)
[+](16) Pidgey visible for 519 seconds (1154m NE from you)
[+](16) Pidgey visible for 533 seconds (1174m NE from you)
[+] Finished: 18.0 %
[+](13) Weedle visible for 464 seconds (1264m SE from you)
[+](41) Zubat visible for 444 seconds (1272m SE from you)
[+](41) Zubat visible for 901 seconds (1313m SE from you)
[+] Finished: 20.0 %
[+](96) Drowzee visible for 901 seconds (1276m SE from you)
[+](16) Pidgey visible for 850 seconds (1489m SE from you)
[+](16) Pidgey visible for 672 seconds (1280m NE from you)
[+](19) Rattata visible for 698 seconds (1233m NE from you)
[+](92) Gastly visible for 881 seconds (1252m NE from you)
[+] Finished: 22.0 %
[+](41) Zubat visible for 689 seconds (1308m NE from you)
[+](41) Zubat visible for 809 seconds (1275m NE from you)
[+](7) Squirtle visible for 895 seconds (1232m SE from you)
[+](16) Pidgey visible for 555 seconds (1594m SE from you)
[+] Finished: 24.0 %
[+](19) Rattata visible for 889 seconds (1419m SE from you)
[+](41) Zubat visible for 893 seconds (1233m SE from you)
[+](96) Drowzee visible for 604 seconds (1363m NE from you)
[+](116) Horsea visible for 797 seconds (1429m NE from you)
[+](16) Pidgey visible for 882 seconds (1441m NE from you)
[+](52) Meowth visible for 743 seconds (1457m NE from you)
[+] Finished: 26.0 %

**Comment by seikur0** [comment]
I don't think that's in relation to the center, is it? Look on the map, if it's really that way.

**Comment by FrozenSocket** [comment]
Yeah, the map is only showing spawns on 80% of the left (east) side; nothing on the right at all.
I've deleted the files created by the s2 plan but still the same problem :/

**Comment by FrozenSocket** [comment]
any ideas @seikur0 what could be causing this?

EDIT: I'm running the plan again from a random location I'll post up screenshots of the plan and results so you can better see the problem.

**Comment by FrozenSocket** [comment]
![image](https://cloud.githubusercontent.com/assets/22102429/18993317/77bf4e32-871a-11e6-899d-ff3691331751.png)

python main0.py -p -id 0

executed plan: townrange25.plan
{
 "type": "seikur0_spir",
 "location": [47.497178, 19.070534],
 "range": 25
}

**Comment by seikur0** [comment]
I'll try it out.

**Comment by seikur0** [comment]
![hex](https://cloud.githubusercontent.com/assets/20639004/18999583/a838b2b4-873e-11e6-9fc7-2a0fc7862a1a.png)

Well I can't see anything wrong with it. Make sure you have the newest files and everything.

I used this plan:

```
 {
     "type": "seikur0_spir",
     "location": [
         53.148302, 8.182658
     ],
     "range": 25
 }
```

**Comment by seikur0** [comment]
{
 "type": "seikur0_spir",
 "location": [
  53.148302, 8.182658
 ],
 "range": 25
}
{
 "type": "seikur0_spir",
 "location": [
  53.148302, 8.182658
 ],
 "range": 25
}

**Comment by FrozenSocket** [comment]
![image](https://cloud.githubusercontent.com/assets/22102429/19001347/ab27b34e-873e-11e6-8967-200847966611.png)

Same shape of spawn reguardless of the location, I always get the 1/3 pie on the right side :/
I'll delete all my files and re-pull from scratch see if that helps.

**Comment by FrozenSocket** [comment]
That sorted it, deleted PGO dir, re-cloned the repo, put same settings in and no problem. Very strange...

**Comment by seikur0** [comment]
I really like the paint scribbling though :D
