### ISSUE TITLE
This operation would block forever (Orly!)

### ISSUE THREAD

**Issue by FrozenSocket** [seikur0/PGO-mapscan-opt#261]
`[-] Pushbullet Error: ('This operation would block forever', <Hub at 0x73d0470 select pending=0 ref=0 resolver=<gevent.resolver_thread.Resolver at 0x145b42e8 pool=<ThreadPool at 0x145b4668 0/1/10>> threadpool=<ThreadPool at 0x145b4668 0/1/10>>)`

No idea what it means but thought I'd post it up here for you :)

**Comment by seikur0** [comment]
Forever is a long time :P It probably means, you have more notifications going on than the python pushbullet api can handle.
