### ISSUE TITLE
new pokemon dont' always show up on map.

### ISSUE THREAD

**Issue by vDrag0n** [seikur0/PGO-mapscan-opt#268]
To force a refresh i need to hide/active the specific pokemon for it to refresh on map.  currently running latest version. It might have to do with something in the mapscan.js

**Comment by seikur0** [comment]
Or you could just be patient and wait for the 10 second refresh interval to trigger.

**Comment by vDrag0n** [comment]
even after 10 secs. This is after minutes.

**Comment by seikur0** [comment]
It's working normally for me. Do you have anything in the browser console? F12.

**Comment by vDrag0n** [comment]
just a warning
`Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.`

Im using the standard icons with about 20k spawn points.

**Comment by seikur0** [comment]
Which browser are you using, did you do anything special, etc? Since it's working for me and probably for everybody else, I'm not sure, how to help you, if you don't give me more infos.

**Comment by vDrag0n** [comment]
I have made no modifications to the map code. I am running 2 maps on the same chrome browser.  The map with 20k spawn points has problems with refreshing, while the map with 13k spawn points refreshes fine.  Panning the map away from the spawn points and back will also force a refresh. 

on the 20k spawn map, I occasionally get a 404 for _getdata

**Comment by seikur0** [comment]
I see, so yeah, that changes things a lot. It saves received pokemon in the local storage, so they don't get downloaded twice ever. And that's shared between all tabs of the same page. How is your setup for these two maps, I mean are they running via the same url?, which id?

**Comment by vDrag0n** [comment]
20k one is running on an external ip (has about 3 get data issue over a 6 hr period). the 13k one is a local host (no get data issue). Im also running another external map with i think 16k points which has no issues refreshing automatically( 1 get data issue ).

**Comment by seikur0** [comment]
Okay, it's still the local storage issue. Try accessing the two maps by appending /id0 or /id1 or whatever id is running. Standard id is -1, which will show data for all ids. As long as the id is different, it'll work in the same browser with two maps. Example:  http://localhost:8000/id0

**Comment by vDrag0n** [comment]
i decided to try running on a seperate browser (firefox).  Same issues with the 20k spawns.  Im thinking there is a limit somewhere. thats causing the problems.

**Comment by seikur0** [comment]
If you don't mind, can you give me the address of the 20k one to test? That way, I can pull the data from you with my local files and try to look into it.

**Comment by vDrag0n** [comment]
Sent it to your reddit account.

**Comment by seikur0** [comment]
Resolved, was an old version.
