### ISSUE TITLE
Import spawn to PokemonGo Map

### ISSUE THREAD

**Issue by Eskof** [seikur0/PGO-mapscan-opt#271]
Hello, is that possible to import json scanned from it to PokemonGo Map?
Thanks

**Comment by seikur0** [comment]
Sure, but since PokemonGoMap doesn't support spawnpoint scanning properly, I don't think it's of much use?^^

**Comment by Eskof** [comment]
Well, its much better to scan with this one as TBTerra/spawnScan, but I cant figure how can I use this for -ss @ pokemongomap, the json doesnt seems to be in correct format

**Comment by seikur0** [comment]
Json is easy enough to import and modify, look into the spawnfix.py for an example, you have to code a converter tool yourself, if you want it :)

**Comment by Eskof** [comment]
Well. Thanks for quick answer, but guess I'll have to pass =(
Great job anyway!

**Comment by seikur0** [comment]
Maybe someone on the PokemonGoMap github or discord wants to do it. I wouldn't be the right person for it, because I'd feel bad for using the exact data so inefficiently and also I don't know the details of how that map uses the specific infos.
