### ISSUE TITLE
SSL3 certificate error trying to log into Google

### ISSUE THREAD

**Issue by bmenrigh** [seikur0/PGO-mapscan-opt#274]
Starting this morning I'm getting a certificate validation error when the code tries to log into google:

```
/home/brenrigh/.local/lib64/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
[0] Unexpected google login error: [Errno 1] _ssl.c:504: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
```

It gets stuck in a retry loop and doesn't make progress.  I tried switching to python 3.3 per the warning about upgrading python but it seems the code doesn't run under python 3.3.  I had to change "import Queue" to "from multiprocessing import Queue" but after that main0.py starts and then exits silently with a error code of 1.

**Comment by seikur0** [comment]
You can try updating gpsoauth, change it in the requirements.txt to just gpsoauth and do `pip install --upgrade gpsoauth` after that

**Comment by bmenrigh** [comment]
So the previous gpsoauth version I had was 0.3.0 and the upgrade took it to 0.4.0 however the behavior is the same.  I'm a bit surprised others aren't experiencing the same issue since nothing changed on my end between when it was working and when it failed.

I was trying to dig through the code to figure out where the actual SSL session happens to figure out if I could tweak it to do TLS or figure out what exactly it was doing that was resulting in a failure.  It seems like your code fully relies on the gpsoauth library for all that though so perhaps I should be looking there.

**Comment by bmenrigh** [comment]
So it seems like Google has disabled support for SSL3 for auth (which is the right security move).  I dug through gpsoauth and see that it's making use of `session = requests.session()` and then later `session.post(auth_url, data,[...]` so it semes like the requests library is at fault for choosing SSL3 for an HTTPS URL.

I'll look for a work-around and take it up with the other projects at fault.

For what it's worth, if you try SSL3 manually against the auth server it fails in basically the same way:

```
$ openssl s_client -ssl3 -connect android.clients.google.com:443
CONNECTED(00000003)
140730601207528:error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number:s3_pkt.c:337:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 5 bytes and written 7 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
SSL-Session:
    Protocol  : SSLv3
    Cipher    : 0000
    Session-ID:
    Session-ID-ctx:
    Master-Key:
    Key-Arg   : None
    Krb5 Principal: None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1475534203
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
---

```

**Comment by seikur0** [comment]
Apparently SSL3 is pretty much broken. Try patching the gpsoauth using [this](http://docs.python-requests.org/en/latest/user/advanced/#example-specific-ssl-version). It's probably best to make a pull request there then.

**Comment by seikur0** [comment]
The reason why nobody noticed is probably, that nobody uses a google account for authorization, it's hard to create 60 google accounts, but easy to create 60 ptc accounts.
