### ISSUE TITLE
Is scan range deprecated?

### ISSUE THREAD

**Issue by chelming** [seikur0/PGO-mapscan-opt#276]
https://github.com/seikur0/PGO-mapscan-opt/wiki/Settings-Guide#3-scan-range

Talks about using a scan range, i.e., 30, but usersettings.json.example has range as 3300.

Has there been a change that needs to be updated in the wiki and the how-to or am I just reading something incorrectly?

If the wiki/how-to need to be updated I can submit PR's for them.

**Comment by seikur0** [comment]
It is deprecated, it was 30 hex layers before and is now 3300 meters, you can update it :)

**Comment by seikur0** [comment]
Thanks.
