### ISSUE TITLE
SpawnScan seems to hang

### ISSUE THREAD

**Issue by grdn1014** [seikur0/PGO-mapscan-opt#278]
Hi all, sorry I may be beyond help:

I followed all the instructions very carefully and used the -tos parameter since they are all new accounts but it seems that it is not scanning or doing anything. (see attached image) it just gets to this point within a few minutes and does nothing further.

I am able to view the map through my browser but nothing ever shows.

I checked the log file and it just has the headers and is completely empty otherwise.

![wtfpgo](https://cloud.githubusercontent.com/assets/22619924/19081100/bfee4dc8-8a1e-11e6-9100-e6eb49dd1679.png)

**Comment by claimer21** [comment]
You have a couple logins there that apparently did not exist.  If too many logins fail it will hang like that.  Fix your accounts in your usersettings.json file

**Comment by grdn1014** [comment]
Omg. I saw that but I didn't think such a little issue would cause that but you just fixed it!!!! <3 <3 <3

**Comment by seikur0** [comment]
The scan accounts form a group, so if one isn't logged in, they wait. If you start it with 40 accounts you get 40 accounts or none.

**Comment by grdn1014** [comment]
Thank you so much it runs great!!!
