### ISSUE TITLE
Add account number for "Non-empty cell returned as empty"

### ISSUE THREAD

**Issue by chelming** [seikur0/PGO-mapscan-opt#280]
Would it be possible to add which account was returning "Non-empty cell returned as empty." 

Would this even be useful to see if just a specific account is being soft-banned or if it's a whole bunch?

**Comment by chelming** [comment]
I figured out how to add it. I can submit a PR if anyone would think it's useful info.

**Comment by seikur0** [comment]
I'm not sure, why that would be useful for you to know? The account probably wasn't banned, because of its properties, but because of the scan's properties?

**Comment by chelming** [comment]
I'll close this then, but if anyone else is interested you just have to change the entire line in `main0.py` that contains `Non-empty cell returned as empty` to `lprint('[{}] Non-empty cell returned as empty.'.format(self.account['num']))`

**Comment by chelming** [comment]
Ha, so this did end up being seemingly useful. For my one scan, I can see that account 5 is the only one getting non-empty cells returned as empty. Possibly recaptcha?

**Comment by seikur0** [comment]
That's not too hard to guess with reports popping up left and right of it even without the number :P

**Comment by chelming** [comment]
Since it's only happening on one account I can just swap it out.

**Comment by seikur0** [comment]
It's one account for now, wait some hours :/

**Comment by chelming** [comment]
Perhaps some sort of queue for accounts could be implemented? I.e., Here are 150 accounts. Use 10 at a time and if one returns a non-empty cell as empty, cycle it out.
