### ISSUE TITLE
[Question] Recommended number of accounts per Lvl 10 cell

### ISSUE THREAD

**Issue by chelming** [seikur0/PGO-mapscan-opt#281]
Does anyone have any recommendations for number of accounts per Level 10 cell and number of accounts per IP? I'm trying to scan 5 level 10 cells but eventually run into soft ban issues.

I have 120 accounts and all 5 cells have been merged with spawnfix for a total of 36,343 spawn points.

Any ideas whether my soft bans could be coming from having the entire area merged as one, from 120 accounts on the same IP, or something else entirely?

**Comment by chelming** [comment]
I'm guessing the best course of action is to at least keep the cells grouped and run multiple instances. I'm just not sure how many accounts and cells per instance. Like 60 accounts and 2 cells per IP address.

**Comment by seikur0** [comment]
If these 5 level 10 cells are in a 3x3 pattern, it should be fine, if not you're having them too spread out. ~160 accounts should be fine per IP address, if they're not too spread out. I'm not sure if that recently changed, see #283 .

**Comment by chelming** [comment]
Yeah, the pattern was something like this:

|  | X | X |
| --- | --- | --- |
| **X** | **X** | **X** |

I'm seeing the same thing as #283 where after a few hours I'll get what seems to be a soft ban on the IP.
