### ISSUE TITLE
Not pausing for Captcha?

### ISSUE THREAD

**Issue by NHLGames** [seikur0/PGO-mapscan-opt#293]
I'm trying to use the captcha solving trick.  I created a file named token_captcha.txt, but I'm never getting prompted to fill out the captcha? It just returns a "captcha required" warning and continues with the scan.

There is a captcha0.txt file being created, do I need a special setting to prevent them from logging them all there instead of prompting me?

UPDATE: If i hit enter while the scan is running, it gives me the prompt message - but I'm not sure if it actually registers properly?

**Comment by seikur0** [comment]
It does, have some faith :P I can add a message to reflect that I guess. It's not pausing, but gives you the message and you can hit return at any point to make it read the token from the file.
