### ISSUE TITLE
Scan radius changed from 100 - 70?

### ISSUE THREAD

**Issue by shadowsyllvet** [seikur0/PGO-mapscan-opt#34]
Just saw a post in r/pokemongodev that said the servers changed the radius that you can see pokemon to 70 meters. 
~~If true are you aware and does this still scan at 100m?~~

https://www.reddit.com/r/pokemongodev/comments/4v73aj/psa_scan_radius_was_changed_from_100m_to_70m/

Scratch that, I just saw your commit where you updated it to set the radius automatically depending on the server response.

**Comment by seikur0** [comment]
Jup, so if they upgrade it to 150m tomorrow, you'd suddenly scan a huge area in the same time xD. Not gonna happen, but let me dream.
