### ISSUE TITLE
Scanning duration

### ISSUE THREAD

**Issue by KassiusKlay** [seikur0/PGO-mapscan-opt#36]
Hi there,

First of all thanks for your wonderful scanner. Ive been using it with great success.

I have 2 questions:

1 - I run with 2 different ids in adjacent parts of the town - One id takes 9mins to scan the other 15++mins. I understand that since yesterday the scanning time got prolonged but why the difference between the two ids?

2 - I ve been using ngrok to port the map to mobile but with your scanner it feels it is too much data since it never loads or its extremely slow. Is that normal?

Again I really apreciate your work. 

Thank you.

**Comment by seikur0** [comment]
Hey, well normally both ids should take the same amount of time(unless they extended the throttling to ip wise). I know that behavior from using the same account, but not with different ones. Are you using the same ranges on both?

Does it load on a browser for you? All I can tell you about that is that I use the map on my mobile phone and it runs fine.

**Comment by KassiusKlay** [comment]
1 - I dont really understand what determines the scanning time. 
I have 4 accounts running. If I let them scan with default range (20?) it takes over 12mins each. I have to change to 10-15 range but still in between them the difference is noticeble. Any idea what determines the scanning time and variation?

2 - Are you using ngrok or other software to check the map on the phone?

Thanks

**Comment by seikur0** [comment]
I'm using google chrome to check the map, have it hosted on a server. For the same range the scan time varies with the amount of errors the niantic servers currently give back. Otherwise maybe one of them has much more spawns in it, so it might take more time to decode, that may happen on weaker PCs.

**Comment by KassiusKlay** [comment]
PC definetely not on the weaker side but i agree maybe its the amounts of zubats that i filter that make them slower.
Can you tell me how you do to check the map on mobile chrome without ngrok? Just a regular address? (which one?)
thanks

**Comment by seikur0** [comment]
I'd say you can access it via your IP, while you have the simpleHTTP server running. Like http://localhost:port but with http://ipaddress:port I can't guarantee that though, I'm not that knowledgeable about websites and web hosting.
