### ISSUE TITLE
Multiple scans not showing on web view

### ISSUE THREAD

**Issue by ferazambuja** [seikur0/PGO-mapscan-opt#37]
I've been testing with different scanner mode for multiple ids. They do scan and collect the data.
However, only id0 shows on the web map.
I've run multiple instances main0.py -id0, main0.py -id1, main0.py -id2....

**Comment by KassiusKlay** [comment]
"_comment12": "The html page will only try to load the live data for ids listed here.",
  "load_ids": [

Did you put your ids there?

**Comment by ferazambuja** [comment]
Missed..
