### ISSUE TITLE
Failed attempts in both

### ISSUE THREAD

**Issue by GrafOnega** [seikur0/PGO-mapscan-opt#38]
https://imgur.com/a/B1woF
'pip install -r requirements.txt' or if that fails 'pip install --user -r requirements.txt. 
It does not help any one method.

**Comment by JoeryH** [comment]
Try it in an elevated command prompt

**Comment by GrafOnega** [comment]
Tell me, please, how?

**Comment by JoeryH** [comment]
Run cmd as Administrator

**Comment by GrafOnega** [comment]
https://imgur.com/a/GPGXV
I Tried. Does not work.

**Comment by GrafOnega** [comment]
Before the error
https://imgur.com/a/jwAWF

**Comment by shadowsyllvet** [comment]
what version of python are you using?
what os?

**Comment by GrafOnega** [comment]
win 7 
python 2.7.12

**Comment by shadowsyllvet** [comment]
https://github.com/twisted/twisted/releases/tag/twisted-16.3.0
you could manually install that i guess??

**Comment by GrafOnega** [comment]
What's this?

**Comment by shadowsyllvet** [comment]
that's from the requirements.txt it is what you are failing to install.

**Comment by GrafOnega** [comment]
I'm trying to install the twisted. The same error.

**Comment by GrafOnega** [comment]
Please tell us in detail what I should do.

**Comment by shadowsyllvet** [comment]
try this? pip install setuptools

**Comment by GrafOnega** [comment]
https://imgur.com/a/MAR0O

**Comment by GrafOnega** [comment]
The issue still actual
https://imgur.com/a/9DkwM
https://imgur.com/a/SU8Ub

**Comment by seikur0** [comment]
Remove twisted from the requirements for now, it's for the included data upload tool. I'll convey this error to the creator ;)

**Comment by marvin-bitterlich** [comment]
@GrafOnega can you try
pip install twisted-win
That could help with the problem.

**Comment by GrafOnega** [comment]
@Kostronor of course. https://imgur.com/a/Lx1E1

**Comment by GrafOnega** [comment]
https://imgur.com/a/y4iCC
I switched to windows 10. The problem remains urgent.

**Comment by seikur0** [comment]
Also a line, which works for both windows and unix users would be good :/

**Comment by seikur0** [comment]
Try "pip install --user twisted-win" btw

**Comment by GrafOnega** [comment]
@seikur0  https://imgur.com/a/PN9lQ

**Comment by marvin-bitterlich** [comment]
Twisted seems really weird on windows sometimes. My python2 installation has some other problem with it... So I use python3 for it and that works strangely...

**Comment by seikur0** [comment]
Well it says you don't have the util module, so "pip install util". I bet these twisted guys forgot to put that into their requirements.

**Comment by GrafOnega** [comment]
Okay, now I try to install python 3. Please understand that I am Russian, and I find it hard to understand the many factors.

**Comment by marvin-bitterlich** [comment]
The thing is:
Twisted on windows is weird. They have problems. A lot.
And using python3 worked for me with `twisted-win`, so hopefully it works for you too @GrafOnega :)

**Comment by marvin-bitterlich** [comment]
@seikur0 sadly the module util could be any util.py file anywhere. This seems more like a twisted bug :/

**Comment by GrafOnega** [comment]
util.py
https://imgur.com/a/oQys0

**Comment by GrafOnega** [comment]
if i use python 3
https://imgur.com/a/KiMTv

**Comment by marvin-bitterlich** [comment]
@GrafOnega forget the util thing, just install `twisted-win` :)

**Comment by GrafOnega** [comment]
@Kostronor still
https://imgur.com/a/KiMTv

**Comment by marvin-bitterlich** [comment]
@GrafOnega util does not exist. It is not something you can install.

**Comment by marvin-bitterlich** [comment]
Just run
`pip install twisted-win`
`python collector.py`

**Comment by GrafOnega** [comment]
@Kostronor This error occurs always when using python 3. I returned to python 2. All the same it is impossible to install
https://imgur.com/a/hzfXe

**Comment by seikur0** [comment]
_is glad, that it's not his upload tool_ xD

**Comment by GrafOnega** [comment]
Please tell me what I should do. I sit for a second day, nchiego fails. I changed version windows and python. I tried different ways. Nothing comes out!

**Comment by seikur0** [comment]
What I said before:
"Remove twisted from the requirements for now, it's for the included data upload tool."
=This is needed, if you want to share your data with Kostronor's group. You don't need it for the map itself.

**Comment by GrafOnega** [comment]
@seikur0 I'll use the map locally. I do not know what I should do. twisted otddelno stored in the folder.

**Comment by GrafOnega** [comment]
@seikur0 I copied your map on drive C. Start a command prompt in the folder. Launched pip install -r requirements.txt. Then an error
https://imgur.com/a/56Xre

**Comment by seikur0** [comment]
Edit the requirements.txt file, remove the line, that says "twisted". Then "pip install -r requirements.txt" to make sure it gives no errors. Then it should work. And Kostronor will get back on you, when he fixes the data upload.

**Comment by marvin-bitterlich** [comment]
@seikur0 sadly twisted is out of my control. And I don't know how to fix their bugs. Will check with their bugtracking if they know the issue.

**Comment by GrafOnega** [comment]
Removed
Launched
https://imgur.com/a/hVVWr

**Comment by seikur0** [comment]
So I just had to install this myself and my IDE told me, I'd need that package http://aka.ms/vcpython27 (Microsoft Visual C++ Compiler for Python 2.7) to be able to install twisted. Did it and it worked fine. So GrafOnega could you try putting it back in, installing the linked package and retrying "pip install -r requirements.txt" again? If it doesn't work, just comment it back out.

**Comment by GrafOnega** [comment]
@seikur0 All I need - is to install visual studio and start again?

**Comment by GrafOnega** [comment]
@seikur0 GOD! IVE GOT IT! THANK YOU SO MUCH! Two days of torment.

**Comment by seikur0** [comment]
Nice, I'm happy for you xD Glad it finally worked.

**Comment by marvin-bitterlich** [comment]
@seikur0 awesome find, thanks a lot!
