### ISSUE TITLE
Collector not working and changing scan delay / radius

### ISSUE THREAD

**Issue by ghost** [seikur0/PGO-mapscan-opt#39]
1 . The collector.py scripts fails at line 150.

```
File "collector.py", line 150
    print(dot, end='', flush=True)
                  ^
SyntaxError: invalid syntax
```

If I remove this print command, then I am getting

```
Connected to server, start sending!

You seem to have no uploadable files.
Wait a bit for the map to accumulate more pokemon.

Transfered 0 pokemon 
sightings!
Transfer done, waiting for data to be send by the os!
Thanks for helping out!
```

...which isn't right, because I have data from 10 workers collected.  

2 .  With the recent throttling issues from Niantic ([here](https://www.reddit.com/r/pokemongodev/comments/4vf3zc/psa_set_your_scan_delay_to_5_seconds_sd_5/) and [here](https://www.reddit.com/r/pokemongodev/comments/4vev3u/psa_get_map_objects_min_refresh_seconds_5/)) how does one change the scan delay?  Any idea what the change in object refresh means for this, too?

3 .  Scan radius changed from 100m to 70m ([here](https://www.reddit.com/r/pokemongodev/comments/4v73aj/psa_scan_radius_was_changed_from_100m_to_70m/)).  I honestly don't know if this effects the 'centralscan' function.  I am not a python guru.

**Comment by marvin-bitterlich** [comment]
Hey @Jugg1e5 I'm the developer of the colector. In agreement with seikur0 the collector will only upload files that are archived. In your config file you see a size limit. And when you check your res folder you will see files like this:

```
spawns0.json
spawns1.json
```

they are your current working files.

and you may have files like this depending on your size limit.

```
spawns0.2345_22.json
```

these are files that reached the size limit (of 10mb per worker or so) and were moved. If you rename your `spawnsX.json` to `spawnsX.11_11.json` you will have manually archived these files.

Maybe @seikur0 kann tell a bit more about this.

The print bug seems like something I can fix, give me a minute.

**Comment by seikur0** [comment]
1. Yeah only the backed up files (standard size 10 MB, can change that in the settings) get uploaded and as Kostronor said you can manually rename them, if you want to send them early.
2. Ideally you change the -r parameter to 1/0.7=1.43 of what it was before to counter the range reduction, then you look how long the scan takes for one worker. You set the scan interval to a higher number, dividable by the scan interval you actually want. Then you use multiple workers with the interval set to that high number and start them with a time distance of the actually wanted interval in between. Dirty fix for now. Example -r20 before, now -r30, takes 19 minutes, I want a scan every 5 minutes, so interval is 20 minutes and I have to use 4 workers for it. I start them at 0,5,10 and 15 minutes. (That can be done with command line scripts.)
3. The centralscan function is adapting to every radius these niantic servers give out.

**Comment by ghost** [comment]
Hey @Kostronor.  Thanks for the info.  I removed the print command, and it says that it is now sending.  Very slowly, but still sending.  Some of the lines in the file are copies of the header.  I hope those can be filtered.  Also, this data is from before the alleged changes to the spawn nests, so I don't know if it will be relevant.  
Cheers.

**Comment by marvin-bitterlich** [comment]
@seikur0 has merged #41 so you can add the print command again, This will give you a better progress indication.

The header lines will be ignored automatically. And sorry, sending is slow because the server has to keep up with a big database. And twisted helps me make it as fast as the server can handle, which is about 100 per second.

Collecting nest places seems to be the number one priority at the moment. I don't know how Niantic will change all this, so all data will be fine :) And since we have timestamps, we can calculate if it is pre nestswitch or post.

**Comment by ghost** [comment]
@seikur0, I _think_ I follow your explanation.  In this example, each worker would need to have the same location set to make sure the same area is being covered every 5 minutes, yes?  How would that work with the centralscan function that's changing the start locations for the 2nd to 7th workers?  

Also, I was having the same [issue](https://github.com/seikur0/PGO-mapscan-opt/issues/40) with missing pokemon and thought this new <5 second delay issue was responsible.

**Comment by seikur0** [comment]
This 5 second delay is actually a misconception, it was always at that value. And before the niantic ip bans yesterday (value was at 5 s already) I did send a request every 0.25 seconds, of which every second one failed, so that makes an actual 2 per second, which work. I don't know, if anything was changed today though, right now my cloud service ips are blocked and I need to migrate this to my local pc :( 

Get the new main0.py, that'll clearly tell you, if your ip was blocked as well(could be the reason for few pokemons). Also inside the main0.py put LOGGING in line 80 to True. Then comment in line 484 (will show errors again, most of them can be ignored though). Let me know, what the console gives you.

**Comment by ghost** [comment]
Every second or third one seems to work.
Doesn't seem to be a ban.  But still, the density of pokemon just feels much lower than the last few days.  Maybe just niantic.

```
[+] You are playing Pokemon Go since: 2016-07-30 09:21:55
[+] POKECOIN: 0
[+] STARDUST: 0

[+] Time: 13:55:53
[+] Finished: 0.0 %
[-] Response error, status code: 52, retrying in 0.26 seconds

[+] Finished: 0.591715976331 %
[-] Response error, status code: 52, retrying in 0.26 seconds

[+] Finished: 1.18343195266 %

[+] Finished: 1.77514792899 %
[-] Response error, status code: 52, retrying in 0.26 seconds

[+] Finished: 2.36686390533 %
[-] Response error, status code: 52, retrying in 0.26 seconds

[+] Finished: 2.95857988166 %

[+] Finished: 3.55029585799 %
[-] Response error, status code: 52, retrying in 0.26 seconds

[+] Finished: 4.14201183432 %
[-] Response error, status code: 52, retrying in 0.26 seconds

[+] Finished: 4.73372781065 %

[+] Finished: 5.32544378698 %
[-] Response error, status code: 52, retrying in 0.26 seconds

[+] Finished: 5.91715976331 %

[+] Finished: 6.50887573964 %
[-] Response error, status code: 52, retrying in 0.26 seconds
<<pwild>> (16) Pidgey visible for 528 seconds (200m NE from you)
<<pwild>> (16) Pidgey visible for 354 seconds (237m NE from you)

[+] Finished: 7.10059171598 %

[+] Finished: 7.69230769231 %
[-] Response error, status code: 52, retrying in 0.26 seconds

[+] Finished: 8.28402366864 %
[-] Response error, status code: 52, retrying in 0.26 seconds

[+] Finished: 8.87573964497 %

[+] Finished: 9.4674556213 %
[-] Response error, status code: 52, retrying in 0.26 seconds

[+] Finished: 10.0591715976 %
[-] Response error, status code: 52, retrying in 0.26 seconds

[+] Finished: 10.650887574 %

[+] Finished: 11.2426035503 %
[-] Response error, status code: 52, retrying in 0.26 seconds

```

**Comment by seikur0** [comment]
Okay, that looks fine, I guess. The error doesn't mean, that it'll skip anything, it means, it'll try again. So it's impossible to lose data. I'll look into it though, you never know, what they changed. Keep in mind though that the vision range did get changed and so you may need to increase the -r parameter to get the same coverage as before.
