### ISSUE TITLE
[Question/Request(s)]

### ISSUE THREAD

**Issue by shadowsyllvet** [seikur0/PGO-mapscan-opt#4]
First, I love this search algorithm!
1. Will you be implementing an after the fact filter into the browser page?
2. Will you be implementing a notification feature (preferably pushbullet)
3. At what range would you recommend using multiple accounts for scanning? I used 1 for an 8 radius scan and it instantly gave me what I wanted. 20 radius scan was only slightly slower(about 15 seconds) a 40 range scan with one account took over 5 minutes(understandably).
4. Do you have a forum/general chat page up for this to keep the github clean(aside from reddit)?
% Thank you again! I have been so frustrated with the speed of other map scanning programs.

**Comment by seikur0** [comment]
1. If you mean the possibility to exclude certain pokemons, that's already inside, look at the excludeIDs array.
   As for something like a menu bar, where you can select this kind of stuff from the map, I don't think so. I'm using this mainly on my mobile phone and it would fill up the screen.
2. No. The purpose is mainly to have a map while being out hunting. You're invited though to use my code in a tool of your own, that you could adapt to your purposes.
3. Okay first let me say, that I'm really amazed at the scan times you people get. I have this running on a site called pythonanywhere and a 20 radius scan takes ~140 seconds for me haha So it really depends on how often you need an update and how good your hardware is and how far your reach is, if you see a good pokemon (walk/bike/drive/etc.). I for instance go out with my bike and I'm quite happy with just one account at radius 20.
4. Just post it to github or reddit, that's okay. This is a lot more support work than I expected it to be.

There is a lot of positive feedback though and I'm glad people like my code :)

**Comment by shadowsyllvet** [comment]
I have your code running on a 6 year old hp laptop thats cutting out on me already. That's the main reaso I was so surprised by the scan time.
The pushbullet request is mainly for rares. I can start the scan at home with a 2-3 minute refresh rate locked onto a large park and get notified while i'm out jogging eggs or socializing. Plus I can see a twitter feed going up for the park. basically anyone who subscribed would get an update for rares. I know of one person who implemented pushbullet notifications to AHAAA...s map. I will see if they want to defect to your side. just wanted to make sure you weren't working on it already.

**Comment by seikur0** [comment]
Wow this kind of makes me wonder if I'm being overcharged on that server.

Yeah ask that person.
