### ISSUE TITLE
Missing a LOT of pokemons

### ISSUE THREAD

**Issue by KassiusKlay** [seikur0/PGO-mapscan-opt#40]
Since a few hours ago (after i went to bed - 9hours ago) the scanners are missing a LOT of pokemon.

I noticed when i was on a Pokestop and saw a ninetails nearby and i wasnt notified. I managed to find and catch the ninetails using a online scanner (trackemon.com).

Then i got home and removed the filter on the scanner and indeed its missing a lot of pokemons. 

Check attached pictures:

![scanner](https://cloud.githubusercontent.com/assets/20741018/17275795/14c3dbe2-570c-11e6-9327-b4ac535a025d.jpg)
![trackemon](https://cloud.githubusercontent.com/assets/20741018/17275796/14c75ae2-570c-11e6-86aa-831c1256be25.jpg)

It has to do with the recent nyantic changes or the changes on your project you made recently?

Thanks

**Comment by seikur0** [comment]
Check the scan time. Some ips were semi-blocked and these are very very very slow now. Has to do with niantic changes.

**Comment by shadowsyllvet** [comment]
They're using IP throttling? Instead of just account based?

**Comment by seikur0** [comment]
It was throttling 12 hours ago, like rejecting 199 out of 200 requests. But now it's apparently 200/200. And yeah, they banned many cloud service ip ranges. The newest version will indicate, if your ip is being banned and quit.

**Comment by seikur0** [comment]
Also see this: http://www.forbes.com/sites/ryanmac/2016/07/31/pokemon-go-cuts-off-access-to-pokevision-and-other-creature-finding-apps/

**Comment by seikur0** [comment]
New info: They return false negatives right now. Working on it.

**Comment by KassiusKlay** [comment]
I really apreciate it.

**Comment by seikur0** [comment]
Fixed. Also very slow now, at least with just one account.
