### ISSUE TITLE
Sporadic error on startup

### ISSUE THREAD

**Issue by c00ni** [seikur0/PGO-mapscan-opt#42]
Have had this happen very infrequently (twice out of maybe 30 or so times I've restarted threads) upon starting a thread.
It logged in but before scanning,

Traceback (most recent call last):
  File "c:\mapscanopt\main0.py", line 721, in <module>
    main()
  File "c:\mapscanopt\main0.py", line 599, in main
    settings.ParseFromString(response.returns[4])
  File "c:\python27\lib\site-packages\google\protobuf\internal\containers.py", line 64, in **getitem**
    return self._values[key]
IndexError: list index out of range

Trying again without changing anything works.
Just thought you'd want to know, if you want to implement some debugging or error catching for it.

**Comment by seikur0** [comment]
Okay weird, that means they don't send the settings sometimes :/ Thank you for the heads up.

**Comment by seikur0** [comment]
For some accounts you need to wait a while after login until they work. It may be something like a time between logins either in general for that ip or for the account. Fixed in the new update. Multithreading, yay.
