### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character...

### ISSUE THREAD

**Issue by cfatduck** [seikur0/PGO-mapscan-opt#43]
## Any one got this issue? I have set the language to English, using google auth.

Traceback (most recent call last):
  File "main0.py", line 713, in <module>
    main()
  File "main0.py", line 675, in main
    f.write('{}\t{}\t{}\t{}\t{}\t{}\t{}\t{}\t{}\n'.format(pokemons[wild.pokemon_data.pokemon_id],wild.pokemon_data.pokemon_id,spawnIDint,wild.latitude,wild.longitude,(wild.last_modified_timestamp_ms+wild.time_till_hidden_ms)/1000.0-900.0,wild.last_modified_timestamp_ms/1000.0,org_tth/1000.0,wild.encounter_id))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 8: ordinal not in range(128)

**Comment by seikur0** [comment]
Okay, fixed. It was a Far Fetch'd with a fancy quotaion mark character.. Get the new english.json file.

**Comment by cfatduck** [comment]
Thanks! Works like a charm!
