### ISSUE TITLE
how to use more than one worker?

### ISSUE THREAD

**Issue by daejincho** [seikur0/PGO-mapscan-opt#45]
Hi, you're amazing for sharing your awesome work. I apologize for this stupid question, but I can't seem to find an answer to it. I'm a newbie to coding and stuff. I can comprehend only about half of your codes.

I believe I set up usersettings.json correctly with 3 different id's. When I run python main0.py, it will only load one id which is 0. I see that without -id parser it defaults to 0, but what's the point of having multiple profiles if they can run only one by one?

Even if all 3 id's run at the same time, what good does it do if they all search only one spot? All of the id's will end up going through same coordinates.

**Comment by shadowsyllvet** [comment]
You need to launch separate instances of the program for each ID. The code is set up in a way that either gives each ID it's own coords around a hexagon or gives them individual coords based on your user settings.

**Comment by DanHazard** [comment]
To further comment on this, if we wanted to scan a very large area, what would be the best way to go about it?  Clearly I need to run multiple instances of this, but have you figured out an optimal area 'radius' to use which avoids running into trouble with Niantic?

**Comment by seikur0** [comment]
To even further comment on this, you don't need multiple instances anymore with the newest update ;) It has multithreading.

**Comment by daejincho** [comment]
great new update!
