### ISSUE TITLE
Custom timezones?

### ISSUE THREAD

**Issue by DanHazard** [seikur0/PGO-mapscan-opt#48]
Hey, this is more of a feature request, but as I loaded up the data to make a heat map, I noticed the time and have no idea what it correlates to per my local time.  Would it be possible at some point to make it so we can have an option in the config file to set a time zone or at least time display prefs?

**Comment by sonnybIack** [comment]
Hey, this is maybe a simple question for you. Multithreading is awesome but is it possible to allow **more than 5 threads?** if i wanna add one login more in the .json file and run the script it just closes immediately. Thx for reply and sorry for bad english

**Comment by seikur0** [comment]
It's unix time (timezone independent), which you can easily transform into any time format you want.
http://www.unixtimestamp.com/

**Comment by seikur0** [comment]
(So no, I won't include time preferences. If you're gonna analyse the data anyway, unix time is good.)
