### ISSUE TITLE
How to add more than 5 different thread  login's in the usersettings.json file?

### ISSUE THREAD

**Issue by sonnybIack** [seikur0/PGO-mapscan-opt#49]
Hey, this is maybe a simple question for you. Multithreading is awesome but is it possible to allow **more than 5 threads?** if i wanna add one login more in the .json file and run the script it just closes immediately. Thx for reply and sorry for bad english

example. if i add one more of this the script wont work.

 **{
      "id": 0,
      "type": "ptc",
      "username": "xxxx",
      "password": "xxxx",
      "coordinates":
          {
              "lat": xxxx, 
              "lng": xxx, 
              "alt": 0
          }
    }**

**Comment by DanHazard** [comment]
Just copy and paste and be sure to mind your commas (,) 

you need a common between each new one like so...

```
    {
      "id": 0,
      "type": "google",
      "username": "agent2",
      "password": "pass",
      "coordinates":
          {
              "lat": 0,
              "lng": 0,
              "alt": 0
          }
    },
    {
      "id": 0,
      "type": "ptc",
      "username": "agent3",
      "password": "pass",
      "coordinates":
          {
              "lat": 0,
              "lng": 0,
              "alt": 0
          }
    },
    {
      "id": 0,
      "type": "google",
      "username": "agent4",
      "password": "pass",
      "coordinates":
          {
              "lat": 0,
              "lng": 0,
              "alt": 0
          }
    }

```

Just be sure there isn't a comma after the last one.

**Comment by sonnybIack** [comment]
awesome ! **THX a lot!**

**Comment by DanHazard** [comment]
what text editor are you using?

**Comment by sonnybIack** [comment]
im using notepad++ its working like a lightning bolt with 10 threads

**Comment by DanHazard** [comment]
did you figure it out?

**Comment by sonnybIack** [comment]
yeah i rly just missed a comma :D

**Comment by DanHazard** [comment]
Nice, you can close your own issue, by the way.  Should be an option here at the bottom.

**Comment by ferazambuja** [comment]
If you have a lot of workers here is something you can do:
1. Type all your credentials in this order:
User1, Password,User2,Password...
2. Paste on this [website](http://www.convertcsv.com/csv-to-json.htm).
3. Create Custom Output via Template:
`{lb}
      "id": 0,
      "type": "ptc",
       "username":"{f1}",
       "password":"{f2}",
       "coordinates":
           {lb}
              "lat": 0,
              "lng": 0,
              "alt": 0  
           {rb}
 {rb}
`
4. Now just copy and paste 👍

**Comment by daejincho** [comment]
no offense. that just sounds sketchy

**Comment by ferazambuja** [comment]
Well, you can just type manually. That website just formats on a "json", easier than writing a script for it. I used since would take forever to add 67 accounts.

**Comment by seikur0** [comment]
"no offense. that just sounds sketchy"
Made my day :D
