### ISSUE TITLE
Have this be more extensible?

### ISSUE THREAD

**Issue by trippyhat** [seikur0/PGO-mapscan-opt#5]
This is really great, but it would be fantastic if this script could be more extensible. Right now we have to go in and manually update the code for our user/pass and our google maps key. It would also be great if we more easily could call your script in our own modules:

```
import PGO_mapscan_opt
while True:
    poke_objs = PGO_mapscan_opt.search(config)
    # Do stuff with poke_objs
```

where `config` is yaml or some other data structure:

```
username = 'me@google.com'
password = 'password'
range = 12
location = 'some place'
gmaps_key = ''    # optional
```

and so on.

**Comment by seikur0** [comment]
Create an api like that as fork and do it :) It's a good idea.

**Comment by seikur0** [comment]
With the new update you can set everything up from the command line, it's no api, but it make be helpful to you.
