### ISSUE TITLE
Session Token isn't valid yet.

### ISSUE THREAD

**Issue by DanHazard** [seikur0/PGO-mapscan-opt#50]
After an hour or two of peaceful scanning this started flooding my cmd prompt.

![image](https://cloud.githubusercontent.com/assets/11038145/17317653/cb41617a-5845-11e6-9aff-53dd91f6db05.png)

using 10 accounts
scaninterval set to 300
range set to 20

that's all I tweaked.

**Comment by seikur0** [comment]
Could it have been exactly 2 hours? Account logins need to be refreshed after that time. And sometimes you just have to wait a little bit for it to happen, that's the meaning of that error. Did you quit it? Just waiting should have "fixed" it.

**Comment by DanHazard** [comment]
I quit then yes, restarted and went to sleep.  This morning I saw the same message, looks like my scan died in the process too.  If it helps, I'm using mostly google acct logins.

**Comment by seikur0** [comment]
Okay I'll look into this. A bug, that you have to wait 2 hours for, man that sucks..

**Comment by DanHazard** [comment]
Eh, don't bother me because everything else seems to look fine, just messes up my quest to map all of Chicago over a 48-72 hour period.  :p 

Thankfully this issue seems to be one of my last worries.

**Comment by c00ni** [comment]
I also had this error. Noticed some pokemon weren't popping on the live map so I remote desktop'ed in to find my screen looking like that screenshot.

I guess it should sense that and re-log in before the whole run completes?
And to do that I guess you'd have to allow simultaneous logins :)

**Comment by ProfessorPokes** [comment]
Want to collab Dan? In NWI myself, doing something similar

**Comment by seikur0** [comment]
I think I'm onto this and I'm learning new things, like how the authorize_profile function and the set_api_endpoint function are basically redundant.

**Comment by kpma1985** [comment]
Maybe quick dirty workaround?

while true; do
killall python
screen -a -dmS pokemon00 -t USER00 /usr/bin/python main0.py -id 0 && \
screen -a -dmS pokemon01 -t USER01 /usr/bin/python main0.py -id 1 && \
screen -a -dmS pokemon02 -t USER02 /usr/bin/python main0.py -id 2 && \
screen -a -dmS pokemon03 -t USER03 /usr/bin/python main0.py -id 3 && \
screen -a -dmS pokemon04 -t USER04 /usr/bin/python main0.py -id 4 && \
screen -a -dmS pokemon05 -t USER05 /usr/bin/python main0.py -id 5
sleep 5400

done

**Comment by seikur0** [comment]
Pretty dirty indeed.

**Comment by DanHazard** [comment]
@ProfessorPokes not sure how to reach you otherwise, message me on reddit maybe?  Name is DanHazard there as well.

**Comment by seikur0** [comment]
Okay 2 hours is fine now, when it runs until after 3 hours, I'll upload the update. (3 hours is the time a login token is valid for ptc accounts).

**Comment by DanHazard** [comment]
Alright, will be testing tonight, obviously.

**Comment by Annelol** [comment]
I have the same problem, not sure about 2 hours, but I've had to restart the instance about 3 times today with the same error messages as shown here

**Comment by seikur0** [comment]
Hopefully it's fixed now, try the new version.

Also c00ni I implemented your requested simultaneous login feature and it's working pretty well :)

**Comment by Annelol** [comment]
Thanks, will try the new version, did you revert  #53  accidentally or was there an issue with it?

**Comment by seikur0** [comment]
Accidentally, let me put it back.. One sec.

**Comment by DanHazard** [comment]
I'm getting a keyerror "login_simu" at the moment.

e: I see the issue, I copied over my old config and there's new stuff in the new one.

**Comment by seikur0** [comment]
Closed for now.
