### ISSUE TITLE
Connection error, http code: 200

### ISSUE THREAD

**Issue by lifeofbolo** [seikur0/PGO-mapscan-opt#52]
any fix to this?

**Comment by seikur0** [comment]
200 in principal is pretty good, the interesting error message would be the one before that: "[-] Uncaught connection error, error: ...."

**Comment by seikur0** [comment]
Seems like that particular account was invalid, wrong user name or password. Check that please.

**Comment by lifeofbolo** [comment]
@seikur0 
is it username on ptc?, in game on PGO? or email?

**Comment by seikur0** [comment]
ptc username.

**Comment by lifeofbolo** [comment]
still getting the connection error?
<img width="1907" alt="skaermbillede 2016-08-03 kl 11 43 58" src="https://cloud.githubusercontent.com/assets/20727032/17361215/a6424828-596f-11e6-9200-039c0dd82c08.png">
