### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by kpma1985** [seikur0/PGO-mapscan-opt#54]
Hi,

everytime i need to modify the index.html (do i need this? or is it compatible?)
I added the "Locate Me" Button..

Can u merge this in your file?

Second Request: seperate the user accounts :) maybe database driven?

**Comment by seikur0** [comment]
Write a script, that puts the usernames in correctly? It's json, so it should work with php?

The my location button is a pull request already, I wanted to test that live, haven't had the time yet.

**Comment by kpma1985** [comment]
Yes i can generate the complete  usersettings.json. 
Are the changes in the future backwards compatible?

**Comment by seikur0** [comment]
Yes I think so, I haven't changed the user keys since I put them in :)
