### ISSUE TITLE
Feature Request: Single Scan mode and log to SQLite

### ISSUE THREAD

**Issue by nadnerb33** [seikur0/PGO-mapscan-opt#55]
With every update I have to re-add some custom bits for my setup e.g log to a SQLite db and also add single scan mode which is useful to run from a mobile device when out and about and you want to know what is nearby.

Would you be willing to add these features? I can set up a pull request if you're interested.

**Comment by seikur0** [comment]
Add the pull requests and I'll see how I integrate these :)

**Comment by seikur0** [comment]
Okay the single scan is integrated with the update.
