### ISSUE TITLE
Removing empty location

### ISSUE THREAD

**Issue by ProfessorPokes** [seikur0/PGO-mapscan-opt#56]
I am running 2 instances now. So 2 sets of workers. The first is id 0, and has 3 accts, the second is id 1, and has 2 accts.

id 0 is returning results, and removing empty locations.
id 1 is returning no results and has removed every location it has scanned.
1. Where is this list of removed locations saved if anywhere?
2. Let's pretend that nothing spawns in said location on this scan, what about on the next scan when something did spawn?
3. Is it possible that running 2 instances with 2 ids each with their own group, that the second group will return no results?

I ask this because I am running a scan of the same area as id 1 (with a different account on an app on my phone) and it has found plenty of pokes.

**Comment by seikur0** [comment]
1. There is no list yet. If I let it save a blacklist file later, I'll give the possibility to rescan an area while updating that file.
2. I'm not listing locations with no pokemon as empty, I'm listing locations with no spawn points as empty.
3. If you run the same account multiple times, that'll make you lose pokemon and make more places being listed as empty. Are you sure, that different accounts were used for these ids? Also look at the messages in the beginning, everything fine?

**Comment by seikur0** [comment]
With the new update many places, that came up empty before are now properly recognized. This may make blacklisting/whitelisting unnecessary.

**Comment by seikur0** [comment]
This is obsolete, since the new update handles empty spaces much better. Closed.
