### ISSUE TITLE
Not working anymore.

### ISSUE THREAD

**Issue by sonnybIack** [seikur0/PGO-mapscan-opt#58]
I just downloaded the newest zip file and edited my account login & pw in the usersettings.json file but if i run the scanner like i did on the older version, i just pops a black cmd/phyton screen and immediately closes it.

**Comment by seikur0** [comment]
You should open it from a cmd window to actually see error messages after it closes. I'd guess you forgot a comma in the settings somewhere.

**Comment by sonnybIack** [comment]
The settings file is not in a valid format, Expecting : delimiter: line 47 column 14 (char 1952).

> i made : then and its running BUT error 200 while login in PTC account

**Comment by sonnybIack** [comment]
OK fixed. it just was the **:** missing in usersettings.json line 47 column 14

**Comment by seikur0** [comment]
Oh I see, my bad then.
