### ISSUE TITLE
Uncaught connection error

### ISSUE THREAD

**Issue by ferazambuja** [seikur0/PGO-mapscan-opt#6]
I left my six workers running during the night for data mining. All of them ran flawlessly besides one.
It happened to me before while running multiple workers. The error goes starts and it's not able to recover.

```
[-] Uncaught connection error, error: Invalid URL u'https:///rpc': No host supplied
[-] Error happened before network request.
[-] Retrying...
[-] Uncaught connection error, error: Invalid URL u'https:///rpc': No host supplied
[-] Error happened before network request.
[-] Retrying...
[-] Uncaught connection error, error: Invalid URL u'https:///rpc': No host supplied
[-] Error happened before network request.
```

**Comment by seikur0** [comment]
I think I've already fixed that issue, can you look into your main0.py, if you have the following lines inside:

 while p_ret.status_code==102:
print('[-] Error, invalid session, retrying...')
time.sleep(300) #at that point the severs are pretty much done for, so waiting for 5 min
p_ret = get_profile(access_token, API_URL, None)

If not, you have the version before that fix and should update.

**Comment by ferazambuja** [comment]
Had the old code. Updating now.

**Comment by ferazambuja** [comment]
Could we maybe move our credentials and locations to a separate config.py file. This way would be easy to update.

**Comment by seikur0** [comment]
Sounds good, yeah I can do in the next update.
