### ISSUE TITLE
Loads of Heartbeat Errors

### ISSUE THREAD

**Issue by DanHazard** [seikur0/PGO-mapscan-opt#63]
Got the latest update, and the second scan is returning a ton of heartbeat errors.

![image](https://cloud.githubusercontent.com/assets/11038145/17348630/1fb62a6e-58dd-11e6-94b1-6813fa702939.png)

Didn't see these last night, not sure if it's affecting my scan quality or what.  Is there a log file which we can peruse?

**Comment by DanHazard** [comment]
Eventually just kept returning heartbeat errors:

![image](https://cloud.githubusercontent.com/assets/11038145/17348710/ce679296-58dd-11e6-87bc-b5eb703e4faf.png)

**Comment by seikur0** [comment]
Okay, get the new update. It's kind of hard to keep track of this, because the server acts differently with many accounts at once involved.

**Comment by DanHazard** [comment]
Ah alright.  Yeah, actually since I just stopped and restarted it, not nearly as many issues, and has completed a few scans already.  I have to go so I'll let this one run, and will update when I get back.

**Comment by DanHazard** [comment]
Ended up eating dust, but now there's a new update.
