### ISSUE TITLE
KeyError: 'sessoion' when multiple accounts attempting to log in

### ISSUE THREAD

**Issue by DanHazard** [seikur0/PGO-mapscan-opt#64]
This is popping up.  Also can't CTRL C out of it.

![image](https://cloud.githubusercontent.com/assets/11038145/17354072/deda486c-590a-11e6-924a-29dc3c9cca88.png)

**Comment by DanHazard** [comment]
Looks like it's strictly relegated to google accounts.

e: can confirm, just tried using my one other ptc account and it worked fine.

**Comment by seikur0** [comment]
Fixed. Changed something, forgot google..

**Comment by DanHazard** [comment]
hehehe whooo, well the good news is I stayed up late making a shit ton of ptc acccounts... so now i have double the accounts.

**Comment by seikur0** [comment]
xD well, it's never wrong to have some spare accounts
