### ISSUE TITLE
Map not showing Pokemon

### ISSUE THREAD

**Issue by mog3n** [seikur0/PGO-mapscan-opt#65]
So i'm positive that I'm looking at the area I'm scanning and I can't seem to see any pokemon in the map. I can see them in the console but nowhere else

![image](https://cloud.githubusercontent.com/assets/13462253/17354944/d84ba684-591a-11e6-988a-869558efcdc1.png)

**Comment by daejincho** [comment]
Did you put in the correct id numbers in usersettings.json?

 "_comment9": "The html page will only try to load the live data for ids listed here.",
  "load_ids": [0,1,2],

**Comment by DanHazard** [comment]
You have to open a separate instance of cmd and then run python -m SimpleHTTPServer 8000 to view the map.

**Comment by mog3n** [comment]
@danhazard yes I've done that and the map is open in the background. Pokemon icons just won't show up

**Comment by DanHazard** [comment]
Interesting,  I have the latest update and started a can 14 mins ago, no problems here.  Not sure what to make of your issue.

**Comment by seikur0** [comment]
You can hit Strg+F5 to refresh the cache. That may help. Also post a screen of the simpleHTTP server command window.

I plan on changing that simpleHTTP server thing, it's laggy in comparison to other server tools and I want to change it to twisted, which will also be started automatically.
