### ISSUE TITLE
get_map_objects_min_refresh_seconds: 10.0

### ISSUE THREAD

**Issue by Scildrei** [seikur0/PGO-mapscan-opt#66]
Hello, 

I'm not sure if you're aware, but apparently they changed the scan delay to 10s from 5s. I'm doing some testing at the moment, but it's painfully slow.

This is the currently map_settings thingy:

``` python
map_settings {
    pokemon_visible_range: 70.
    poke_nav_range_meters: 201.0
    encounter_range_meters: 50.0
    get_map_objects_min_refresh_seconds: 10.0
    get_map_objects_max_refresh_seconds: 30.0
    get_map_objects_min_distance_meters: 10.0
    google_maps_api_key: hidden
}
```

[Reddit link](https://www.reddit.com/r/pokemongodev/comments/4vuijn/psa_minimum_scan_refresh_now_10s/?sort=new)

**Comment by seikur0** [comment]
That's not what this setting means. It doesn't reflect niantic server behavior, but the app behavior.
