### ISSUE TITLE
Scan radius now 70m and scan delay is 10s

### ISSUE THREAD

**Issue by schawsk** [seikur0/PGO-mapscan-opt#67]
In the last few days and hours, Niantic has changed how the client receives info about pokemon from the server. 
First of all the sight radius decreased to 70m from 100m. From the readme I see that you still use the old 100m sight radius. Will you fix that soon? Can I adjust some options to use your algorithm already until then?

Secondly, A few days ago Niantic changed the scan delay from 1s to 5s. This morning it was increased once again to 10s (see, for example [here](https://www.reddit.com/r/pokemongodev/comments/4vuijn/psa_minimum_scan_refresh_now_10s/) ). Can you adjust that as well please, or tell me again what options might account for this?
Thanks!

**Comment by seikur0** [comment]
Sight radius was fixed ages ago, the readme wasn't :) Scan delay is properly reflected in the code.
