### ISSUE TITLE
SimpleHTTP makes map account's username/password and gmaps api key public

### ISSUE THREAD

**Issue by ethanbayliss** [seikur0/PGO-mapscan-opt#69]
http://localhost:8000/res/usersettings.json

Not a major issue if the map isn't public, but if the user decides to use the wiki to setup a public server the config files are viewable by all.

Maybe just add a disclaimer in the readme/wiki to warn the user?

**Comment by seikur0** [comment]
Well if you're experienced enough to setup a public server, you should know this and it's really your own fault, if you leave these sensitive information lying around. I think other people also would need to know that res path first, which is not that likely.

I also plan to integrate the server with twisted, so by then it won't be an issue anymore.
