### ISSUE TITLE
Issue with login_simu?

### ISSUE THREAD

**Issue by Annelol** [seikur0/PGO-mapscan-opt#71]
There seems to be a problem with login_simu when an account fails to login the script just keeps hanging on login, without login_simu it retries to login to that/those particular account(s) but with login_simu the script is dead after these errors and doesnt respond to ctrl+c either.
it doesnt happen every time and sometimes when restarting the script right after it does work, but Im logging in with about a 100 accounts and when one fails like this it hangs.

> Exception in thread Thread-42:
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
>     self.run()
>   File "main0.py", line 653, in run
>     do_login(self.account)
>   File "main0.py", line 345, in do_login
>     login_ptc(account)
>   File "main0.py", line 333, in login_ptc
>     if r is not None:
> UnboundLocalError: local variable 'r' referenced before assignment
> 
> [-] Ptc login error in step 3: IncompleteRead(0 bytes read)
> [-] Connection error, http code: 200
> [-] Retrying...
> [-] Ptc login error in step 3: IncompleteRead(0 bytes read)
> [-] Connection error, http code: 200
> [-] Retrying...
> [-] Ptc login error in step 3: IncompleteRead(0 bytes read)
> [-] Connection error, http code: 200
> [-] Retrying...
> [-] Error, invalid session, retrying...
> [-] Ptc login error in step 3: ('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing: incorrect header check',))
> [-] Connection error, http code: 200
> [-] Retrying...
> [-] Ptc login error in step 0: ('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing: incorrect header check',))
> [-] Connection error, http code: 500

**Comment by seikur0** [comment]
Yeah it's designed, so it'll only start when every account logs in correctly, it'll retry until it succeeds. But this Unbound error shouldn't be there and prevents that from happening. I fixed this now.

**Comment by Annelol** [comment]
Thanks! :) 
Btw I think you might have accidentally reverted #70 in the process ^^

**Comment by Annelol** [comment]
Seems to work perfectly now with login_simu

**Comment by seikur0** [comment]
Damm, I need to take better care. Yeah it should be really failsafe now. The whole program.
