### ISSUE TITLE
Hi I'm new here what means "pip install -r requirements.txt"?

### ISSUE THREAD

**Issue by Arepas** [seikur0/PGO-mapscan-opt#72]
I tryied run it on python console to does nothing just close

can someone give a advise?

ty

**Comment by DanHazard** [comment]
If you are running windows, I can offer this advice:

First make the console point at the directory where you have pgo-mapscan located.

Once you are in that directory you then can run pip instally -r requirements.txt and it should install all the requirements necessary to run the main module.

So for example if I downloaded the files to c:/pokemonmap/pgo-mapscan-opt in the console I'd first type:

`cd c:/pokemonmap/pgo-mapscan-opt`

then your console should look like this:

`C:\pokemonmap\pgo-mapscan-opt>`

Once you are at this point simply type in:

`pip install -r requirements.txt`

And it should download all the requirements for you.  This is, of course, assuming you have pip functionality.

**Comment by Arepas** [comment]
mate thanks alot! now is loading files.

next question when I type: "python -m SimpleHTTPServer 8000" in windows a black window pop-up showing info about the server but in the browser I only see my files no map. Am I missing something?

**Comment by seikur0** [comment]
Try the newest version, which has the server included and starts it automatically with the tool. Your issue could be because you're not in the path with the command window? cd c:/pokemonmap/pgo-mapscan-opt again before you run that.

**Comment by DanHazard** [comment]
Oh man, another new version? :)

**Comment by Arepas** [comment]
yup I tryied the new version and the map is working I think lol. no pokemon, no yet
but when run main0 I take a screenshoot as fast as I can.
![screen](https://cloud.githubusercontent.com/assets/20797937/17379182/09de0344-5976-11e6-8ccf-4664e22e59b0.png)

**Comment by seikur0** [comment]
Your settings file is outdated ;)

**Comment by Arepas** [comment]
seikur0 thx for the advise I think the app is working now...

but is there any issue to PTC server? because I'm getting this 
![loggin](https://cloud.githubusercontent.com/assets/20797937/17382034/cc04423c-5983-11e6-9768-298e7935fae9.png)
I created 4 account happen the same

**Comment by seikur0** [comment]
Updated and closed.
