### ISSUE TITLE
Exception in thread

### ISSUE THREAD

**Issue by JohnHKoh** [seikur0/PGO-mapscan-opt#73]
Hello, the scans were working fast and great, but suddenly I got this error that stopped the scans.

![image](https://cloud.githubusercontent.com/assets/6465531/17378822/9770593e-598d-11e6-8ba7-39dea19e0101.png)

I got this error a few times before, but it was during the part when it was logging into all the PTC accounts. After a few restarts of the server, the error stopped, and I thought it was fixed, but this error came back up again. Any help would be appreciated.

**Comment by vowswithin** [comment]
- 1

I can confirm same error here

**Comment by seikur0** [comment]
Was fixed two hours ago.
