### ISSUE TITLE
PTC login error in step 4

### ISSUE THREAD

**Issue by pokesense** [seikur0/PGO-mapscan-opt#76]
Hey,

Running the script but keep on getting the below error message:

 Ptc login error in step 4: list index out of range
[-] Connection error, http code: 200
[-] Retrying...

**Comment by DanHazard** [comment]
There are currently server issues according to r/pokemongodev  I would wait a bit.  Niantic might be changing things up OR their servers are simply on fire.  Early reports suggest simply the latter.

That OR:  you have a typo in your credentials.

**Comment by DanHazard** [comment]
Actually looks like the API might have changed, killing this... for now.

**Comment by JohnHKoh** [comment]
![image](https://cloud.githubusercontent.com/assets/6465531/17381452/fb592b68-5999-11e6-8821-dc0f85a7315b.png)

Yeah, looks like something changed. Been getting this for the past few scans. Hopefully it can be fixed soon.

**Comment by pokesense** [comment]
Maybe not, i've just created a new PTC account and it seems to be working for me I think.

**Comment by kpma1985** [comment]
indeed,, all my thread are running out of pokemons...
new account created and tested... nothing... nada :D

**Comment by Arepas** [comment]
![loggin](https://cloud.githubusercontent.com/assets/20797937/17382141/45b91652-5984-11e6-8d45-780f4616cc4a.png)

same thing for you guys?

**Comment by seikur0** [comment]
R.I.P. Pokemon maps... T_T

**Comment by DanHazard** [comment]
I think that in a day people will have it figure out, and maps will be working again, hopefully you keep to update this great tool.
