### ISSUE TITLE
Scan is super slow now?

### ISSUE THREAD

**Issue by visualjazz-sbrunno** [seikur0/PGO-mapscan-opt#77]
I have 5 accounts added in my usersettings, but seems like now no pokemon are showing up and it goes 2%, 4% every couple mins now.

If you need more details let me know!

**Comment by visualjazz-sbrunno** [comment]
Seems like this might be related: https://www.reddit.com/r/pokemongodev/comments/4w1cvr/pokemongo_current_api_status/

**Comment by daejincho** [comment]
Sucks! :(

**Comment by thisIsLiving** [comment]
@seikur0 you looking to implement the new API?

**Comment by seikur0** [comment]
Will do that tomorrow. I just came back from a weekend trip and I'm exhausted.

**Comment by seikur0** [comment]
Implemented.
