### ISSUE TITLE
Using multi-threading

### ISSUE THREAD

**Issue by thisIsLiving** [seikur0/PGO-mapscan-opt#78]
I'm not sure if I'm using the multithreading correctly? In the usersettings I've put in

```
  "profiles": [
    {
      "id": 0,
      "type": "ptc",
      "username": "user0",
      "password": "pass0",
      "coordinates":
          {
              "lat": 1234,
              "lng": 1234,
              "alt": 0
          }
    },
    {
      "id": 1,
      "type": "ptc",
      "username": "user1",
      "password": "pass1",
      "coordinates":
          {
              "lat": 789,
              "lng": 789,
              "alt": 0
          }
    }
]
```

I've identified each worker to have their own ID but when I run "python main0.py" it says it's distributing to 1 thread (I'm assuming ID 0 as no -id arg was given). Do I have to open a new window and specify "-id 1" to run in a new session?

**Comment by SvenvandenBerg** [comment]
I am pretty sure the id specified in your profiles refers to the id of the instance of main0.py that is supposed to use it. If you want to use multiple PTC accounts on one instance, assign them to the same id.

**Comment by seikur0** [comment]
That is correct. But no api calls are currently working. I'm suprised, that some people still don't know ^^

**Comment by thisIsLiving** [comment]
Cool no worries, I read in one of the threads that you didn't need multiple instances since there was multithreading but it seems like it's one ID per instance (with multiple accounts per ID). Anywho thanks for the info, just gotta wait for a work around now :)

**Comment by seikur0** [comment]
That's actually intended by me, having multiple instances for different locations. Because then you are flexible to start and kill them as you like. And you can also automate that with command line scripts, if you want and need to. Also it's working again, so closed.
