### ISSUE TITLE
Api Verbindung geht wieder

### ISSUE THREAD

**Issue by mancmanGER** [seikur0/PGO-mapscan-opt#79]
Hallo seikur0,

wirst Du deine Map anpassen?

**Comment by seikur0** [comment]
Hey, ja werde ich. Ich war aber gerade auf nem Wochenend-Trip und bin todmüde, also erst morgen :)

**Comment by DanHazard** [comment]
Ausgezeichnet

**Comment by mancmanGER** [comment]
Merci,

Stress dich bitte nicht.

**Comment by nudl3r** [comment]
Super, du bist einfach der beste. Danke!

**Comment by DanHazard** [comment]
Is it difficult to implement?

**Comment by seikur0** [comment]
No, it's just, that I've been sick and lying in my bed yesterday and most of today :/ But I'm working on it right now, I got it already implemented. I just want to do a few tests before throwing it at you guys. I'll upload it in some minutes :)

**Comment by seikur0** [comment]
Updated and thus closed :)
