### ISSUE TITLE
Pokemon name

### ISSUE THREAD

**Issue by ygongdev** [seikur0/PGO-mapscan-opt#8]
print(pokemons[wild.pokemon_data.pokemon_id])

For Nidoran, I got Nidoran? I'm not sure if this applies to other pokemon with maybe special characters in their name? e.g. Mr.Mime etc.

**Comment by seikur0** [comment]
It does, Not for Mr. Mime though, he has no special characters, I should replace these in the json files.

**Comment by ygongdev** [comment]
Can you tell me when you change it or how I would change it? I would really like to use this soon :D

**Comment by ygongdev** [comment]
Ok I figured it out. All I had to do was go into english.json and correct the symbols :)

**Comment by seikur0** [comment]
You can make a commit, so I don't have to do it again, if you already have a good english.json file now :)
