### ISSUE TITLE
'TypeError: Odd-length string' at start

### ISSUE THREAD

**Issue by kpma1985** [seikur0/PGO-mapscan-opt#81]
Hi,

is multithread bugged?

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "main0.py", line 711, in run
    h = heartbeat(location, self.account)
  File "main0.py", line 540, in heartbeat
    response = get_profile(1, location, account, m1)
  File "main0.py", line 492, in get_profile
    response = api_req(location, account, account['api_url'], account['access_token'], req, useauth=account['auth_ticket'])
  File "main0.py", line 402, in api_req
    sig.location_hash1 = generateLocation1(ticket_serialized, location[0], location[1], location[2])
  File "/var/www/uk6.py", line 34, in generateLocation1
    locationBytes = d2h(lat) + d2h(lng) + d2h(alt)
  File "/var/www/uk6.py", line 30, in d2h
    return hex(struct.unpack('<Q', struct.pack('<d', f))[0])[2:-1].decode("hex")
  File "/usr/lib/python2.7/encodings/hex_codec.py", line 42, in hex_decode
    output = binascii.a2b_hex(input)
TypeError: Odd-length string

**Comment by seikur0** [comment]
No. Can you write me the scan location? lat/lng/alt

**Comment by Annelol** [comment]
getting same errors straight after login

(2 seperate occasions):

> Exception in thread Thread-59:
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
>     self.run()
>   File "main0.py", line 711, in run
>     h = heartbeat(location, self.account)
>   File "main0.py", line 540, in heartbeat
>     response = get_profile(1, location, account, m1)
>   File "main0.py", line 492, in get_profile
>     response = api_req(location, account, account['api_url'], account['access_token'], req, useauth=account['auth_ticket'])
>   File "main0.py", line 402, in api_req
>     sig.location_hash1 = generateLocation1(ticket_serialized, location[0], location[1], location[2])
>   File "/var/www/public_html/uk6.py", line 34, in generateLocation1
>     locationBytes = d2h(lat) + d2h(lng) + d2h(alt)
>   File "/var/www/public_html/uk6.py", line 30, in d2h
>     return hex(struct.unpack('<Q', struct.pack('<d', f))[0])[2:-1].decode("hex")
>   File "/usr/lib/python2.7/encodings/hex_codec.py", line 42, in hex_decode
>     output = binascii.a2b_hex(input)
> TypeError: Odd-length string
> 
> Exception in thread Thread-5:
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
>     self.run()
>   File "main0.py", line 711, in run
>     h = heartbeat(location, self.account)
>   File "main0.py", line 540, in heartbeat
>     response = get_profile(1, location, account, m1)
>   File "main0.py", line 492, in get_profile
>     response = api_req(location, account, account['api_url'], account['access_token'], req, useauth=account['auth_ticket'])
>   File "main0.py", line 402, in api_req
>     sig.location_hash1 = generateLocation1(ticket_serialized, location[0], location[1], location[2])
>   File "/var/www/public_html/uk6.py", line 34, in generateLocation1
>     locationBytes = d2h(lat) + d2h(lng) + d2h(alt)
>   File "/var/www/public_html/uk6.py", line 30, in d2h
>     return hex(struct.unpack('<Q', struct.pack('<d', f))[0])[2:-1].decode("hex")
>   File "/usr/lib/python2.7/encodings/hex_codec.py", line 42, in hex_decode
>     output = binascii.a2b_hex(input)
> TypeError: Odd-length string

**Comment by Annelol** [comment]
> ```
>   "coordinates":
>       {
>         "lat": 52.027892,
>         "lng": 5.556565,
>           "alt": 3
>       }
> ```

**Comment by seikur0** [comment]
Hm weird, I just don't have that error at all. Can you try an altitude of 5?
Also weird, that it's just happening for some accounts.

**Comment by Annelol** [comment]
Same error with an altitude of 5 Im afraid, was also getting some other errors which seemed to prevent me from logging in with ~100 accounts

> [-] Ptc login error in step 7: 'NoneType' object has no attribute 'groupdict'
> [-] Connection error, http code: 400
> [-] Retrying...
> [-] Ptc login error in step 7: 'NoneType' object has no attribute 'groupdict'
> [-] Connection error, http code: 503
> [-] Retrying...

but when I tried with 6 accounts login seemed to work but then I got the "TypeError: Odd-length string" error

edit: also happening with only 6 accounts now
edit2: seems to still go through but after a loooooong time

**Comment by seikur0** [comment]
Okay so the 400 and 503 errors are an indication, that ptc is unstable, but it will retry until it works in these cases.

The type error thing however is weird, because there isn't any reason, why it should only throw this error for some accounts. And it's not in a account related step, it just transforms some string of hex numbers into a string :/

Are you on Python 2.7.12 ? (You can find out by just typing python into the command window.)

**Comment by Annelol** [comment]
Python 2.7.6 apparently, want me to try it with an updated to 2.7.12 python?

**Comment by seikur0** [comment]
Yes please. That's the only thing, that comes to mind right now. I can try replacing that exact function with another one tomorrow, if it doesn't help.

**Comment by Annelol** [comment]
> Python 2.7.12 (default, Jul 18 2016, 15:02:52)
> [GCC 4.8.4] on linux2

Same error still there, everytime after every account is logged in it seems, also tried with 1 account, same error

**Comment by seikur0** [comment]
Does it at least happen for all of the accounts, if you let it run?
Tomorrow, I'll replace that function :/

**Comment by Annelol** [comment]
seems to just stop running altogether after the error, might be impatience, thought I did wait some time after the error. I ll run it now and let it run for some time
edit: it does happen consistently every time though

**Comment by seikur0** [comment]
But it also tells you the threadsnumber, does it happen for all threads?

**Comment by Annelol** [comment]
> [+] Run #1, Time: 23:23:17, ID: 0, Location: (), Interval: 180 s
> Exception in thread Thread-3:
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
>     self.run()
>   File "main0.py", line 711, in run
>     h = heartbeat(location, self.account)
>   File "main0.py", line 540, in heartbeat
>     response = get_profile(1, location, account, m1)
>   File "main0.py", line 492, in get_profile
>     response = api_req(location, account, account['api_url'], account['access_token'], req, useauth=account['auth_ticket'])
>   File "main0.py", line 402, in api_req
>     sig.location_hash1 = generateLocation1(ticket_serialized, location[0], location[1], location[2])
>   File "/var/www/public_html/uk6.py", line 34, in generateLocation1
>     locationBytes = d2h(lat) + d2h(lng) + d2h(alt)
>   File "/var/www/public_html/uk6.py", line 30, in d2h
>     return hex(struct.unpack('<Q', struct.pack('<d', f))[0])[2:-1].decode("hex")
>   File "/usr/lib/python2.7/encodings/hex_codec.py", line 42, in hex_decode
>     output = binascii.a2b_hex(input)
> TypeError: Odd-length string
> 
> Exception in thread Thread-7:
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
>     self.run()
>   File "main0.py", line 711, in run
>     h = heartbeat(location, self.account)
>   File "main0.py", line 540, in heartbeat
>     response = get_profile(1, location, account, m1)
>   File "main0.py", line 492, in get_profile
>     response = api_req(location, account, account['api_url'], account['access_token'], req, useauth=account['auth_ticket'])
>   File "main0.py", line 402, in api_req
>     sig.location_hash1 = generateLocation1(ticket_serialized, location[0], location[1], location[2])
>   File "/var/www/public_html/uk6.py", line 34, in generateLocation1
>     locationBytes = d2h(lat) + d2h(lng) + d2h(alt)
>   File "/var/www/public_html/uk6.py", line 30, in d2h
>     return hex(struct.unpack('<Q', struct.pack('<d', f))[0])[2:-1].decode("hex")
>   File "/usr/lib/python2.7/encodings/hex_codec.py", line 42, in hex_decode
>     output = binascii.a2b_hex(input)
> TypeError: Odd-length string
> 
> Exception in thread Thread-6:
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
>     self.run()
>   File "main0.py", line 711, in run
>     h = heartbeat(location, self.account)
>   File "main0.py", line 540, in heartbeat
>     response = get_profile(1, location, account, m1)
>   File "main0.py", line 492, in get_profile
>     response = api_req(location, account, account['api_url'], account['access_token'], req, useauth=account['auth_ticket'])
>   File "main0.py", line 402, in api_req
>     sig.location_hash1 = generateLocation1(ticket_serialized, location[0], location[1], location[2])
>   File "/var/www/public_html/uk6.py", line 34, in generateLocation1
>     locationBytes = d2h(lat) + d2h(lng) + d2h(alt)
>   File "/var/www/public_html/uk6.py", line 30, in d2h
>     return hex(struct.unpack('<Q', struct.pack('<d', f))[0])[2:-1].decode("hex")
>   File "/usr/lib/python2.7/encodings/hex_codec.py", line 42, in hex_decode
>     output = binascii.a2b_hex(input)
> TypeError: Odd-length string
> Exception in thread Thread-2:
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
>     self.run()
>   File "main0.py", line 711, in run
>     h = heartbeat(location, self.account)
>   File "main0.py", line 540, in heartbeat
>     response = get_profile(1, location, account, m1)
>   File "main0.py", line 492, in get_profile
>     response = api_req(location, account, account['api_url'], account['access_token'], req, useauth=account['auth_ticket'])
>   File "main0.py", line 402, in api_req
>     sig.location_hash1 = generateLocation1(ticket_serialized, location[0], location[1], location[2])
>   File "/var/www/public_html/uk6.py", line 34, in generateLocation1
>     locationBytes = d2h(lat) + d2h(lng) + d2h(alt)
>   File "/var/www/public_html/uk6.py", line 30, in d2h
>     return hex(struct.unpack('<Q', struct.pack('<d', f))[0])[2:-1].decode("hex")
>   File "/usr/lib/python2.7/encodings/hex_codec.py", line 42, in hex_decode
>     output = binascii.a2b_hex(input)
> TypeError: Odd-length string
> Exception in thread Thread-5:
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
>     self.run()
>   File "main0.py", line 711, in run
>     h = heartbeat(location, self.account)
>   File "main0.py", line 540, in heartbeat
>     response = get_profile(1, location, account, m1)
>   File "main0.py", line 492, in get_profile
>     response = api_req(location, account, account['api_url'], account['access_token'], req, useauth=account['auth_ticket'])
>   File "main0.py", line 402, in api_req
>     sig.location_hash1 = generateLocation1(ticket_serialized, location[0], location[1], location[2])
>   File "/var/www/public_html/uk6.py", line 34, in generateLocation1
>     locationBytes = d2h(lat) + d2h(lng) + d2h(alt)
>   File "/var/www/public_html/uk6.py", line 30, in d2h
>     return hex(struct.unpack('<Q', struct.pack('<d', f))[0])[2:-1].decode("hex")
>   File "/usr/lib/python2.7/encodings/hex_codec.py", line 42, in hex_decode
>     output = binascii.a2b_hex(input)
> TypeError: Odd-length string
> 
> Exception in thread Thread-4:
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
>     self.run()
>   File "main0.py", line 711, in run
>     h = heartbeat(location, self.account)
>   File "main0.py", line 540, in heartbeat
>     response = get_profile(1, location, account, m1)
>   File "main0.py", line 492, in get_profile
>     response = api_req(location, account, account['api_url'], account['access_token'], req, useauth=account['auth_ticket'])
>   File "main0.py", line 402, in api_req
>     sig.location_hash1 = generateLocation1(ticket_serialized, location[0], location[1], location[2])
>   File "/var/www/public_html/uk6.py", line 34, in generateLocation1
>     locationBytes = d2h(lat) + d2h(lng) + d2h(alt)
>   File "/var/www/public_html/uk6.py", line 30, in d2h
>     return hex(struct.unpack('<Q', struct.pack('<d', f))[0])[2:-1].decode("hex")
>   File "/usr/lib/python2.7/encodings/hex_codec.py", line 42, in hex_decode
>     output = binascii.a2b_hex(input)
> TypeError: Odd-length string

so thats Thread 2-7 on 6 accounts

**Comment by seikur0** [comment]
Apparently the decode function can't handle strings with an odd number of chars, so these need to be padded with one leading zero. Therefore it only happens for certain coordinates. Should be fixed now.
