### ISSUE TITLE
Scanning not working?

### ISSUE THREAD

**Issue by ghost** [seikur0/PGO-mapscan-opt#82]
So, I'm trying out the new map since unknown6, and I got everything working, until after I login and the scan starts, nothing happens.

The last message I get is:
    Run #1, Time: 17:35:21, ID: 0, Location: (_ADDRESS_), Interval: 900 s

After no pokemon are scanned, and when i check the map nothing shows up. I am only running on one account. Any ideas what's wrong?

**Comment by seikur0** [comment]
"nothing happens", well I doubt that ^^ Aha, only one account, that would mean you're scanning awfully slow, so it's kind of natural, that you have to wait for results. Especially if there are no pokemon visible near the starting point.

So you gotta use more accounts, that will fix your problem.
