### ISSUE TITLE
Profiles with id 0 stopped working

### ISSUE THREAD

**Issue by Annelol** [seikur0/PGO-mapscan-opt#83]
[-] Error: No profile exists for the set id.

when I set the ids to 1 the profiles are recognized again

**Comment by c00ni** [comment]
It's defaulting to 1 if not specified as a flag

```
    if wID is None:
        wID = 1
    else:
        wID = int(wID)
```

**Comment by seikur0** [comment]
True, true, I sometimes change it to test with different scan setups and I forgot to change it back. (Specifying -id 0 explicitly would have helped, but I changed it back to normal now.)
