### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'returns'

### ISSUE THREAD

**Issue by c00ni** [seikur0/PGO-mapscan-opt#86]
These get thrown sometimes. Not frequent.

```
Exception in thread Thread-60:
Traceback (most recent call last):
  File "c:\python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "main0.py", line 732, in run
    h = heartbeat(location, self.account)
  File "main0.py", line 550, in heartbeat
    heartbeat.ParseFromString(response.returns[0])
AttributeError: 'NoneType' object has no attribute 'returns'

```

**Comment by c00ni** [comment]
When I say not frequent, I mean it happened twice, right near the very beginning of my scan on two seperate occasions.

**Comment by PureMethod** [comment]
Happened to me twice now, first time ran the script for like 10 mins and second time for like 30 mins. 
![image](https://cloud.githubusercontent.com/assets/20930145/17553459/86f11d92-5f0e-11e6-9cc3-dcebadb8d979.png)

**Comment by c00ni** [comment]
And I just had all 70 threads die with that exception after running for 30mins.
It seems it kills a thread and doesn't recover (it was just sitting there doing nothing at all)

**Comment by seikur0** [comment]
Okay after 30 min, so it may have something to do with the reauthorization.  I updated the main0.py to do some error catching. Normally response shouldn't be None at that point :/

**Comment by c00ni** [comment]
I think it's related to this exception I reported to Pokeminer
https://github.com/modrzew/pokeminer/issues/176
Updating pgoapi from keyphact did indeed stop that exception from happening and there have been many commits so I'm not sure which one did it.

**Comment by seikur0** [comment]
Okay, they changed something around the unknown6, I'll try it out and if it runs for 30 min, I'll update the git.

edit: Nope, didn't help. I think I can track this down though.

**Comment by PureMethod** [comment]
Worked fine for a while but now I'm getting this (sorry if this is the issue you're currently aware and tracking down)
![image](https://cloud.githubusercontent.com/assets/20930145/17556627/c2955d50-5f1c-11e6-9345-8b3f639c404c.png)

**Comment by seikur0** [comment]
Same issue, I think i have this now, I found a logic error...

**Comment by seikur0** [comment]
Okay should be fixed now. Can't try it to make 100% sure, since my ip got softbanned in the process of testing xD

**Comment by PureMethod** [comment]
It just spams authorization refresh now.

**Comment by seikur0** [comment]
There was still another issue with unknown6 changes shenanigans, but now I think I finally have it down. (I hope I'm saying this for the last time haha) Get the newest update.

**Comment by seikur0** [comment]
Okay I guess it is fixed. Closed then.

**Comment by c00ni** [comment]
I don't think I see a commit relevant to you fixing this? The last two were just for the data file and cleaning the spacing in the code?
