### ISSUE TITLE
Authorization Refresh?

### ISSUE THREAD

**Issue by DanHazard** [seikur0/PGO-mapscan-opt#88]
Does this mean I was soft banned?  Was only scanning for about an hour, maybe a bit less.

**Comment by seikur0** [comment]
? No, it's normal, it does that every 30 minutes.

**Comment by DanHazard** [comment]
Ah I mean it was flooded with auth refresh and took up a few hundred lines of cmd before I force killed it.

**Comment by seikur0** [comment]
I think/hope it was fixed with the update 3 hours ago, I would love to hear, that you haven't updated it after that :)

**Comment by DanHazard** [comment]
Yeah I updated it and it ran better.  I think I just got IP banned right now though.  Scan just stopped reporting anything like it was frozen.

**Comment by seikur0** [comment]
Yes I think so, still working for me. It's always better to wait some time between killing and restarting it, ~30 s and avoid restarting it too often to avoid these ip bans. Wait half an hour, it hopefully should be fine then.

**Comment by seikur0** [comment]
Okay confirmed stable now, I have one instance running for 4 hours, consistently working, 100 workers, range 30, interval 5 min.
