### ISSUE TITLE
Starting a second instance/id overrides websettings.json

### ISSUE THREAD

**Issue by c00ni** [seikur0/PGO-mapscan-opt#90]
Starting a second instance to scan another area overrides websettings.json.
The relevant bit (actually the only bit) is the html_coords so the web server always dishes out the last started instance as the centre of the map.

I imagine most people use id 0 as their "main" area and want id 0's data served up as "default", and will have the web server running off id 0.

I personally have a copy of index.html renamed as, eg. work.html and hardcode the map centre and load_id relevant to the second instance (id 0 for home area and id 1 for work).

Was just pondering how this could be solved for a general use case... Maybe a query string passed when loading the page if you want a different id's data? http://blahblah.com/?id=0

**Comment by seikur0** [comment]
That would have the disadvantage of now allowing multiple ids :/

**Comment by c00ni** [comment]
How about
?id=0,1,2,3

**Comment by seikur0** [comment]
Hm with the standard being the ids in the websettings? I guess that would be fine. Would you do a pull request for that? I'm still working on spawn point recognition atm, only need the writing and reading from files tomorrow for that. Oh yeah and the restructuring of the locgiver thread. Then it'll be awesome :)

**Comment by c00ni** [comment]
I would love to have the technical competence to pull this off. I'm good at throwing suggestions in the air though...
:(
Actually I don't properly know any programming language besides BASIC. All this pogo stuff is the first time I've looked at python, and my HTML knowledge goes about as far as coding up simple tags in notepad.

**Comment by seikur0** [comment]
My HTML knowledge is about the same xD Man I wish somebody would overtake the html half of my project.

**Comment by seikur0** [comment]
You can now do that with http://url:port/idX, while http://url:port will just give you everything and use the location of the lowest id profile.

**Comment by seikur0** [comment]
100th closed issue btw, woop woop :D
