### ISSUE TITLE
Accepting TOS - unexpected status code: 1

### ISSUE THREAD

**Issue by c00ni** [seikur0/PGO-mapscan-opt#92]
Got 9 out of 73 accounts banned.
Thought I'd be smart and I remade them with trivial changes to the username (adding an 'a') and made appropriate changes to the usersettings.json.
Ran with -tos.

Got a whole bunch of:
`[-] Response error, unexpected status code: 1, retrying...`

I thought at first it was simply an unhandled exception to accepting tos on an account that had already accepted tos (the 64 accounts that already had done so) but in manually doing the new accounts one by one I found odd things. Some of my new accounts may have accepted the tos before I terminated the process.

Most accounts started scanning normally, but one of them threw one code 1.
Another account got stuck in a code 1 loop and I assumed it had been already accepted but just to be sure I tried again later with -tos again and it started scanning -_-

ˉ_(ツ)_/ˉ

**Comment by seikur0** [comment]
Okay, fixed. I didn't test it with new accounts just with already accepted ones and they returned status_code 2, I added 1 to the expected values.
