### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by ghost** [seikur0/PGO-mapscan-opt#94]
Can you have more than 1 location at a time?
Is this using a radius or 2 coordinates to create a square or rectangle?
Screenshots of the webserver?

Thank you for answering those questions and you may close this as soon as answered.

**Comment by c00ni** [comment]
You can have more than one location at a time. Set up accounts with different id numbers for each area you want covered in usersettings and start a new instance of main0.py with -id x for each area.
You can either let the first id you started do the webserver part or you can start it separately. Other instances will throw an exception whilst starting up saying the port can't be bound, safe to ignore.

It uses a single point as the centre and the scan area grows circularly as the radius value increases.

It uses Google Maps and puts pokemon on it. Tapping them shows a popup with pokemon name and time until despawn.

**Comment by ghost** [comment]
@c00ni No other UI? Just the Map?

**Comment by c00ni** [comment]
@Lionir What else would you like it to show?
Pokemon filtering is done server side in usersettings.
