### ISSUE TITLE
Encrypt.so for windows?..

### ISSUE THREAD

**Issue by ghost** [seikur0/PGO-mapscan-opt#96]
I'm very puzzled as on how I'm supposed to get Encrypt.so on windows?..

**Comment by ghost** [comment]
Well.. Guess it's not for windows. Close this issue.

**Comment by seikur0** [comment]
It's for windows, look here: https://github.com/PokemonGoMap/PokemonGo-Map/tree/develop/pogom/libencrypt

**Comment by ghost** [comment]
@seikur0 , These are DLLs are windows. Your scripts ask for an .so, thus doesn't work.

**Comment by seikur0** [comment]
Just rename them..
