### ISSUE TITLE
Pokemon somehow missed the data file (and map)

### ISSUE THREAD

**Issue by c00ni** [seikur0/PGO-mapscan-opt#98]
I was sitting here watching the scanner go and on my id 1, I saw this line on the console:
`[+] (147) Dratini visible for 299 seconds (615m NW from you)`
It never showed up on the map.
I checked data1.json and there was no Dratini entry in it.
I waited and saw the last modified time update and looked in data1.json again and still no Dratini (but the recently found Exeggcute was now in it). I checked again after 2 mins, still nothing.

id 1 normally has no problems showing Dratini on the map and I farm them every morning on my way to work (including this morning). A few minutes later I have checked the map and a different Dratini has spawned and is showing on the map.

Any idea how this can happen?

**Comment by c00ni** [comment]
Unrelated but I don't want to open too many issues...

My scans take 4-5 minutes to complete so the only pushbullet notifications I receive are always 10-14mins until expiry.

I just received a notification with the text stating 2mins remaining on a Gengar. Map confirms the time.

I also saw that the scan _before_ this one that reported the Gengar took 280 seconds, with 0 retries so I have no idea why the Gengar wasn't found in that scan (which would have pushed a 5-9 mins remaining notification), nor in the one before it (10-14 mins expected).

It was not a long spawn (those send multiple notifications of 0mins - one each scan until there's less than 15mins left).

It was not a delayed push notification as the message text itself states the expiry.

Thoughts?

**Comment by seikur0** [comment]
Okay actually these two things seem very related :D First you need to know, that I added lured pokemon to the output in one of the last updates.

The second one probably was a lured pokemon, and the first one could have something to do with it as well.

I'll probably just remove that for now and revise it.

**Comment by c00ni** [comment]
Were lured Pokemon not added to datax.json?

**Comment by seikur0** [comment]
They should have been. I'll look at this later. It was just a little extra anyway.

**Comment by seikur0** [comment]
Okay after looking into it here is what happened:

I took the value of fort.last_modified_timestamp_ms for the pokemon.last_modified_timestamp_ms of the lured pokemon thinking it was exactly that, but the fort one is the time the lure was used. So the pokemon was detected and the time of the fort was used for the calculation of the despawn time. The pokemon got immediately removed, because it was over the despawn time.

Also apparently lure pokemon only spawn for 3 minutes.

**Comment by seikur0** [comment]
I'm not sure how useful it is to include the lured pokemon given their low staytime. Nobody scans with under 3 minutes interval and with the intelligent algorithm even less so.

What do you think?

**Comment by c00ni** [comment]
The things I notice, hey?
Yeah I don't think there's much point, the combination of your interval lining up with the fort being close enough to get to before the expire time... and yes with the intelligent algorithm too they'll basically never be found.

**Comment by seikur0** [comment]
Oh yeah, you're very perceptive and helpful :) Okay I think so too. Bye lured pokemon then.
